solop-develop/adempiere-grpc-server

build-docker/docker-compose.yml, build-docker/stack.yml
- Support to Docker Compose file for deploy backend with database
- Support to Docker Stack file for deploy backend with database
=> Add Docker Compose and Stack for Deploy Backend with Database

src/main/java/org/spin/grpc/service/BusinessDataServiceImplementation.java, src/main/proto/business.proto
Delete selection records on Smart Browser.
```bash
curl --location --request POST 'http://20.12.0.113:8080/api/adempiere/common/api/delete?token=be50159c-29c9-4968-9527-cab667fcaa55&language=es' \
--data-raw '{"table_name": "AD_User", "ids":[1000006, 1000007,101]}'
```
=> feat: Add ids list to delete entities.

.github/workflows/publish.yml, build-docker/docker-compose.yml, build-docker/stack.yml
- Docker Compose file 
- Docker Stack File
=> Fix Docker Compose

src/main/java/org/spin/base/util/ContextManager.java, src/main/java/org/spin/base/util/RecordUtil.java, src/main/java/org/spin/base/util/ValueUtil.java, src/main/java/org/spin/grpc/service/BusinessDataServiceImplementation.java, src/main/java/org/spin/grpc/service/DictionaryServiceImplementation.java, src/main/java/org/spin/grpc/service/UserInterfaceServiceImplementation.java, src/main/proto/business.proto
Update records in smart browser
1. Login with `System` role.
2. Open `Smart Browser` window and lookup `User Browser` record.
3. Set `Table` and check Is `Updateable` fields.
5. Login with `Garden Admin` role.
6. Open `User Browser` smart browser.
7. Select any record and change.
8. Click in `Update` button.
https://user-images.githubusercontent.com/20288327/172236164-7facdcce-dfd8-4309-a8b2-004c2f6a8b5b.mp4
8. Double click on the row.
https://user-images.githubusercontent.com/20288327/172236156-7956a9f1-9ccf-455a-bcd6-6ef51a6ddc5e.mp4
=> feat: Update browser entity on Smart Browser.

src/main/java/org/spin/grpc/service/UserInterfaceServiceImplementation.java, src/main/proto/business.proto
This new service is made to replace the `api/adempiere/common/api/entity` service, which gets the entity using the table name, plus the id and uuid of the record, however the existing service does not return the display columns.
Now with this new service in the path `api/adempiere/user-interface/window/entity` the entity is obtained through the uuid of the tab, in addition to the id and uuid of the record.
Both work through the http `GET` request method.
http://localhost:8085/api/adempiere/user-interface/window/entity?tab_uuid=a49f84ca-fb40-11e8-a479-7a0060f0aa01&uuid=02b8fa30-24b2-4ece-a0c3-ddf9356cbd0c&token=d1a03358-efea-4b6e-a1c8-ea4d1bf2e08c&language=en
```json
{
"code": 200,
"result": {
"id": 103,
"uuid": "02b8fa30-24b2-4ece-a0c3-ddf9356cbd0c",
"table_name": "C_BP_Group", …
```
=> feat: Add get entity with tab uuid.

build.gradle, src/main/java/org/spin/base/util/ContextManager.java, src/main/java/org/spin/base/util/DictionaryUtil.java, src/main/java/org/spin/base/util/RecordUtil.java, src/main/java/org/spin/base/util/ReferenceInfo.java, src/main/java/org/spin/base/util/ReferenceUtil.java, src/main/java/org/spin/base/util/Services.java, src/main/java/org/spin/base/util/ValueUtil.java, src/main/java/org/spin/client/UserInterface.java, src/main/java/org/spin/grpc/service/BusinessPartnerServiceImplementation.java, src/main/java/org/spin/grpc/service/DictionaryServiceImplementation.java, src/main/java/org/spin/grpc/service/InOutServiceImplementation.java, src/main/java/org/spin/grpc/service/InvoiceServiceImplementation.java, src/main/java/org/spin/grpc/service/OrderServiceImplementation.java, src/main/java/org/spin/grpc/service/PaymentServiceImplementation.java, src/main/java/org/spin/grpc/service/ProductServiceImplementation.java, src/main/java/org/spin/grpc/service/UserInterfaceServiceImplementation.java, src/main/java/org/spin/server/AllInOneServices.java, src/main/proto/business.proto, src/main/proto/business_partner.proto, src/main/proto/dictionary.proto, src/main/proto/in_out.proto, src/main/proto/invoice.proto, src/main/proto/order.proto, src/main/proto/payment.proto, src/main/proto/product.proto
Search by:
* Table name.
* Table id.
* Table uuid.
http://localhost:8085/api/adempiere/dictionary/identifier-fields?table_name=C_ConversionType&token=e9a5e69b-137f-496b-ae0c-b245defb68c5&language=en
```json
{
"code": 200,
"result": {
"records": [
{
"id": 10267,
"uuid": "8bd567ca-fb40-11e8-a479-7a0060f0aa01",
"name": "Name",
"description": "Alphanumeric identifier of the entity",
"help": "The name of an entity (record) is used as an default search option in addition to the search key. The name is up to 60 characters in length.",
"sequence": 1,
"column_name": "Name",
"element_name": "Name",
"is_displayed": false,
"is_displayed_grid": false,
"is_read_only": false,
"is_allow_copy": true,
"is_encrypted": false,
"is_same_line": false,
"is_heading": …
```
=>  feat: Get identifiers fields to GeneralInfo Search

src/main/java/org/spin/base/util/ReferenceUtil.java, src/main/java/org/spin/grpc/service/UserInterfaceServiceImplementation.java
1. Open `Payment Selection` window.
2. List `Client`, `Organization`, and `Document Type`.
3. Show web browser console.
https://user-images.githubusercontent.com/20288327/181847338-2b9d635c-3472-4616-914a-b1d61c6e7c59.mp4
https://user-images.githubusercontent.com/20288327/181847348-10efd489-a487-4333-ad9b-6623ac894d2e.mp4
Request:
http://localhost:8085/api/adempiere/user-interface/window/lookup-items?field_uuid=8dba66d0-fb40-11e8-a479-7a0060f0aa01&search_value=&column_name=C_DocType_ID&token=66749c50-9eba-4597-b11f-f065bcfeb728&language=en
Response:
```json
{
"code": 200,
"result": {
"records": [
{
"id": 1000000,
"uuid": "d3e24fb5-75a3-49c5-91e9-d7eb4f4eb9cc",
"table_name": "C_DocType",
"values": { …
```
=> fix: Reference and dynamic validation on lookups.

build-docker/Dockerfile.prod, build-docker/docker-compose.yml, build-docker/stack.yml, resources/standalone.yml, src/main/java/org/spin/server/AllInOneServices.java
The services were not found as they must be set in the enabled services definitions in order for the server to deploy them, this includes the default value in the SERVICES_ENABLED environment variable in the doc definition file, the docker compose file and the stack.yml.
- business_partner
- in_out
- invoice
- order
- payment
- product
=> fix: Services not found.

build-docker/Dockerfile.prod, build-docker/docker-compose.yml, build-docker/stack.yml, build.gradle, resources/standalone.yml, src/main/java/org/spin/base/util/LookupUtil.java, src/main/java/org/spin/base/util/RecordUtil.java, src/main/java/org/spin/base/util/Services.java, src/main/java/org/spin/base/util/ValueUtil.java, src/main/java/org/spin/grpc/service/PayrollActionNoticeServiceImplementation.java, src/main/java/org/spin/grpc/service/UserInterfaceServiceImplementation.java, src/main/java/org/spin/server/AllInOneServices.java, src/main/proto/payroll_action_notice.proto
- List Payroll Process
http://localhost:8085/api/adempiere/form/addons/payroll-action-notice/list-payroll-process?token=ec47d2ed-39e7-44bc-a595-5188131c1cad&language=en&search_value=Prueba
```json
{
"code": 200,
"result": {
"records": [
{
"id": 1000000,
"uuid": "9342c245-0c80-468d-834c-b9355120aed1",
"table_name": "HR_Process",
"values": {
"DisplayColumn": "100000-Prueba de Nómina con Incidencias",
"KeyColumn": 1000000
}
}
]
}
}
```
- List Employees Valid
http://localhost:8085/api/adempiere/form/addons/payroll-action-notice/list-employee-valid?token=ec47d2ed-39e7-44bc-a595-5188131c1cad&language=en&context_attributes[]={"key":"HR_Process_ID","value":1000000}
```json
{
"code": 200,
"result": {
"records": [
{ …
```
=> feat: Add payroll action notice services.

src/main/java/org/spin/base/util/ReferenceInfo.java
http://0.0.0.0:8085/api/adempiere/user-interface/window/lookup-items?table_name=C_BankAccount&column_name=BankAccountType&token=ec47d2ed-39e7-44bc-a595-5188131c1cad&language=es
```json
{
"code": 500,
"result": "Referencia * No encontrado *\nReferencia * No encontrado *"
}
```
```json
{
"code": 200,
"result": {
"records": [
{
"id": 0,
"uuid": "a45727ac-fb40-11e8-a479-7a0060f0aa01",
"table_name": "AD_Ref_List",
"values": {
"DisplayColumn": "Ahorros",
"KeyColumn": "S",
"ValueColumn": "S"
}
},
{
"id": 0,
"uuid": "a455ea90-fb40-11e8-a479-7a0060f0aa01",
"table_name": "AD_Ref_List",
"values": {
"DisplayColumn": "Cuenta Corriente",
"KeyColumn": "C",
"ValueColumn": "C"
}
}
]
}
}
```
=> fix: Lookup list with Table and Column Name.

src/main/java/org/spin/base/util/ReferenceInfo.java, src/main/java/org/spin/grpc/service/DictionaryServiceImplementation.java, src/main/proto/dictionary.proto
Add Field attributes
- column_id
- column_uuid
- element_id
- element_uuid
Add Reference attributes
- id
- uuid
=> feat: Add field and reference attributes.

src/main/java/org/spin/base/util/DictionaryUtil.java, src/main/java/org/spin/grpc/service/DictionaryServiceImplementation.java, src/main/proto/dictionary.proto
Generate Dependent Fields List
```json
{
...
"dependent_fields":[
{"container_id":53111,"container_uuid":"a4a25786-fb40-11e8-a479-7a0060f0aa01","container_name":"Concept","id":54997,"uuid":"8d27698e-fb40-11e8-a479-7a0060f0aa01","column_name":"IsDefault"},
{"container_id":53113,"container_uuid":"a4a3533e-fb40-11e8-a479-7a0060f0aa01","container_name":"Concept Attributes","id":55024,"uuid":"8d1d36bc-fb40-11e8-a479-7a0060f0aa01","column_name":"AD_Rule_ID"},{"container_id":53113,"container_uuid":"a4a3533e-fb40-11e8-a479-7a0060f0aa01","container_name":"Concept Attributes","id":55025,"uuid":"8d9cd354-fb40-11e8-a479-7a0060f0aa01","column_name":"Amount"},
{"container_id":53113,"container_uuid":"a4a3533e-fb40-11e8-a479-7a0060f0aa01","container_name":"Concept …
```
=> feat: Add dependent fields list.

src/main/java/org/spin/base/util/ReferenceInfo.java
Not loolups list with tableName and column, this reference is ID.
http://0.0.0.0:8085/api/adempiere/user-interface/window/lookup-items?search_value=&table_name=C_Country&column_name=C_Country_ID&token=ec47d2ed-39e7-44bc-a595-5188131c1cad&language=es
```json
{"code":500,"result":"Referencia * No encontrado *\nReferencia * No encontrado *"}
```
```json
{"code":200,"result":{"record_count":247,"next_page_token":"ec47d2ed-39e7-44bc-a595-5188131c1cad-2","records":[{"id":110,"uuid":"a5654476-fb40-11e8-a479-7a0060f0aa01","table_name":"C_Country","values":{"DisplayColumn":"Afganistán","KeyColumn":110}},{"id":111,"uuid":"a5658418-fb40-11e8-a479-7a0060f0aa01","table_name":"C_Country","values":{"DisplayColumn":"Albania","KeyColumn":111}},{"id":101,"uuid":"a565 …
```
=> fix: Lookups list with tableName and columnName.

src/main/java/org/spin/grpc/service/PayrollActionNoticeServiceImplementation.java
If save values on null not updated.
Return Entity.Builder with save values.
=> fix: Save null values on payroll movement.

src/main/java/org/spin/base/util/WorkflowUtil.java, src/main/java/org/spin/grpc/service/AccessServiceImplementation.java, src/main/java/org/spin/grpc/service/DictionaryServiceImplementation.java, src/main/proto/business.proto, src/main/proto/dictionary.proto
http://localhost:8085/api/adempiere/dictionary/workflow?uuid=a5266fee-fb40-11e8-a479-7a0060f0aa01&token=ca853590-5415-4b10-944d-7d3c82538533&language=es
=> feat: Get workflow definition.

src/main/java/org/spin/grpc/service/PointOfSalesServiceImplementation.java, src/main/proto/point_of_sales.proto
On `PrintTicket` service replace `PrintTicketResponse` response to `ProcessLog`.
=> feat: POS Print ticket output process log.

src/main/java/org/spin/grpc/service/BusinessDataServiceImplementation.java, src/main/java/org/spin/grpc/service/PointOfSalesServiceImplementation.java, src/main/proto/point_of_sales.proto
- Add preview print ticket.
- Add stocks request.
=> feat: Add stocks request.

src/main/java/org/spin/grpc/service/PointOfSalesServiceImplementation.java, src/main/proto/point_of_sales.proto
`is_create_lines_from_order` flag is add to create all shipment lines from order
=> feat: POS Create shipment lines from order flag.

src/main/java/org/spin/grpc/service/PointOfSalesServiceImplementation.java
Overwrite IsDisplayTaxAmount and IsDisplayDiscount columns doest exists on C_POSSellerAllocation_ID
=> fix: POS user allocate attributes overwrite.

src/main/java/org/spin/grpc/service/PointOfSalesServiceImplementation.java, src/main/proto/point_of_sales.proto
===========> PointOfSalesServiceImplementation.printTicket: PrintTicket - Error Printing Ticket [174]
=> fix: POS Print ticket handler.

src/main/java/org/spin/grpc/service/BusinessDataServiceImplementation.java, src/main/java/org/spin/grpc/service/PointOfSalesServiceImplementation.java
- Fix print preview column name flag.
- Set process uuid on process log response to open report viewer on front-ent.
=> fix: POS IsAllowsPreviewDocument flag column name. 

src/main/java/org/spin/grpc/service/PointOfSalesServiceImplementation.java, src/main/proto/point_of_sales.proto
Change available payment method:
Add payment method structure.
=> feat: Add payment method.

src/main/java/org/spin/grpc/service/PointOfSalesServiceImplementation.java
```log
PointOfSalesServiceImplementation.printTicket: Esta acción no es permitida en este contexto [36]
```
=> fix: POS Is Allows Print Ticket flag name.

src/main/java/org/spin/grpc/service/PointOfSalesServiceImplementation.java
```log
===========> PointOfSalesServiceImplementation.updateOrderLine: Orden de Venta IsDrafted [20]
-----------> Msg.translate: NOT found: IsDrafted [20]
```
=> fix: POS Order is processed message.

src/main/java/org/spin/base/util/ConvertUtil.java, src/main/java/org/spin/grpc/service/PointOfSalesServiceImplementation.java, src/main/proto/point_of_sales.proto
Change payment reference with payment method structure.
=> feat: POS PaymentReference PaymentMethod structure

src/main/java/org/spin/base/util/ConvertUtil.java, src/main/java/org/spin/base/util/DictionaryUtil.java, src/main/java/org/spin/base/util/ValueUtil.java, src/main/java/org/spin/grpc/service/BusinessDataServiceImplementation.java, src/main/java/org/spin/grpc/service/WorkflowServiceImplementation.java, src/main/proto/workflow.proto
https://user-images.githubusercontent.com/45974454/185167298-be906c6e-dd97-4399-acc6-45f1ae00c65b.mp4
=> feat: (WF) Run Document Action service.

src/main/java/org/spin/grpc/service/PointOfSalesServiceImplementation.java
Add validate pin with supervisor id.
https://user-images.githubusercontent.com/45974454/186994834-19d27b4e-c33c-4e33-98a5-6a9b6432bc54.mp4
=> feat: Add validate pin with supervisor id.

src/main/java/org/spin/base/util/ConvertUtil.java, src/main/proto/point_of_sales.proto
Payment add currency structure:
https://user-images.githubusercontent.com/45974454/186997404-7a65a93d-f3a7-4eaa-b201-8870dd31ba0c.mp4
=> feat: Add currency structure payment.

src/main/proto/core_functionality.proto, src/main/proto/point_of_sales.proto
- Order line structure add procut uom conversion attributes.
- Update order line request add attributes: quantity_ordered, price_actual.
- Order structure add attribute charge_amount.
=> feat: Add uom conversion proto attributes.

src/main/java/org/spin/base/util/ConvertUtil.java, src/main/java/org/spin/grpc/service/CoreFunctionalityImplementation.java, src/main/proto/core_functionality.proto
http://0.0.0.0:8085/api/adempiere/common/list-product-conversion?product_id=1008567&token=e0e47ea8-d8d1-4ba3-8bc4-1af3dc4d5162&language=es
=> feat: Product conversion service.

src/main/java/org/spin/base/util/ConvertUtil.java
http://0.0.0.0:8085/api/adempiere/form/addons/point-of-sales/orders?pos_uuid=c2828298-607f-49e9-b0c1-54ab020890d6&sales_representative_uuid=efb66dc8-fd44-40a4-9d16-00d6ee3c7c78&page_token=50c71b91-8b5c-4a5e-b188-1e989430c470-1&token=50c71b91-8b5c-4a5e-b188-1e989430c470&language=es
=> feat: Charge amount.

src/main/java/org/spin/base/util/ConvertUtil.java
Add on order line:
- UOM conversion product.
- UOM conversion product to.
=> feat: Product conversion into order line.

src/main/java/org/spin/base/util/ConvertUtil.java, src/main/proto/point_of_sales.proto
=> feat: POS Order credit amount.

src/main/java/org/spin/grpc/service/PointOfSalesServiceImplementation.java, src/main/proto/point_of_sales.proto
http://0.0.0.0:8085/api/adempiere/form/addons/point-of-sales/available-cash?pos_uuid=c2828298-607f-49e9-b0c1-54ab020890d6&token=77570c78-8a1d-425e-90ee-0111f9fc33b7&language=es
=> feat: POS Available cash.

src/main/java/org/spin/base/util/ConvertUtil.java, src/main/java/org/spin/grpc/service/DictionaryServiceImplementation.java
Valudate null values before convert grpc object to prevent Null Pointer Exception.
=> fix: Validate convert values to prevent NPE.

src/main/java/org/spin/base/util/ConvertUtil.java
http://0.0.0.0:8085/api/adempiere/common/list-product-conversion?pos_uuid=524eef27-59a9-43a3-bcb3-5c112245a836&product_id=1007771&token=088e80c1-7507-4853-893c-58e30d0ce5ca&language=es
Response
```json
{
"code": 200,
"result": {
"records": [
{
"uuid": "",
"id": 0,
"multiply_rate": 1,
"divide_rate": 1,
"uom": {
"uuid": "85010bd0-8965-11e9-843b-0242ac140011",
"id": 1000240,
"code": "SM",
"symbol": "m²",
"name": "Metro cuadrado",
"starndard_precision": 2,
"costing_precision": 0
},
"product_uom": {
"uuid": "85010bd0-8965-11e9-843b-0242ac140011",
"id": 1000240,
"code": "SM",
"symbol": "m²",
"name": "Metro cuadrado",
"starndard_precision": 2,
"costing_precision": 0
}
},
{
"uuid": "ARG1012L85CH71010_100_1000240", …
```
=> fix: UOM Translate values.

.classpath, src/main/java/org/spin/base/util/ConvertUtil.java, src/main/proto/point_of_sales.proto
http://0.0.0.0:8085/api/adempiere/form/addons/point-of-sales/order-lines?pos_uuid=25eb0e31-0ba9-40e4-81db-ea1b8cf47d00&order_uuid=588b42ed-6605-4365-a2b5-b06e0cd472a3&token=d0a74e43-a3cf-412b-ac17-cff095778d0b&language=es
=> feat: Add available quantity in order line.

src/main/java/org/spin/base/util/ConvertUtil.java
Change order line attributes:
- uom: Set uom values from order line.
- product uom: Set uom values from product on order line.
=> fix: POS Order Line uom and product uom values.

src/main/java/org/spin/base/util/ConvertUtil.java, src/main/java/org/spin/grpc/service/PointOfSalesServiceImplementation.java, src/main/proto/point_of_sales.proto
- Add order currency rate on payment reference
=> feat: Add order currency rate on payment reference

src/main/java/org/spin/base/util/ConvertUtil.java
- Calculate charge amount.
- Calculate credit amount.
=> fix: Charge and credit payment amount.

src/main/java/org/spin/grpc/service/PointOfSalesServiceImplementation.java
When creating a customer business partner, the price list of the business partner group is set.
When creating a point of sale business partner you should not set any price list.
=> feat: BP Customer Price List with BPGroup Price List.

src/main/java/org/spin/grpc/service/PointOfSalesServiceImplementation.java, src/main/proto/point_of_sales.proto
Add flag to validate pin with modify discount
https://user-images.githubusercontent.com/45974454/189436736-629a0660-7fb7-436b-894f-3ece2dcc7ee0.mp4
=> feat: Add flag to validate discount.

src/main/java/org/spin/grpc/service/PointOfSalesServiceImplementation.java
Fix List Sales Orders:
- List sales orders without point of sales.
- List sales orders with other organization.
=> fix: POS List sales orders with other organization.

src/main/java/org/spin/base/util/LookupUtil.java, src/main/java/org/spin/base/util/ReferenceUtil.java, src/main/java/org/spin/grpc/service/UserInterfaceServiceImplementation.java
http://localhost:8085/api/adempiere/user-interface/window/default-value?context_attributes[]=%7B%22key%22:%22%23AD_Client_ID%22,%22value%22:0%7D&field_uuid=8d5702a2-fb40-11e8-a479-7a0060f0aa01&id=4270&value=0&token=25733eea-10e2-456c-aad1-7c52a9f5cd86&language=es
```json
{
"code": 200,
"result": {
"id": 0,
"uuid": "8b2f5420-fb40-11e8-a479-7a0060f0aa01",
{
"value": "System"
},
{
"value": 0
},
{
"key": "UUID",
"value": "8b2f5420-fb40-11e8-a479-7a0060f0aa01"
}
]
}
}
```
http://localhost:8085/api/adempiere/user-interface/window/lookup-items?field_uuid=8d5702a2-fb40-11e8-a479-7a0060f0aa01&search_value=&column_name=AD_Client_ID&token=25733eea-10e2-456c-aad1-7c52a9f5cd86&language=es
```json
{
"code": 200,
"result": { …
```
=> fix: Set UUID on lookup and default value.

build-docker/Dockerfile.prod, build-docker/docker-compose.yml, build-docker/stack.yml, resources/standalone.yml, src/main/java/org/spin/base/util/Services.java, src/main/java/org/spin/grpc/service/GeneralLedgerServiceImplementation.java, src/main/java/org/spin/server/AllInOneServices.java, src/main/proto/general_ledger.proto
Add new services to General Ledger:
- List accouting Combinations.
- Get Accouting Combination.
- Save Accouting Combination.
=> feat: Add accouting combination.

src/main/java/org/spin/base/util/ConvertUtil.java
http://localhost:8085/api/adempiere/form/addons/point-of-sales/order-lines?pos_uuid=9097abdb-7d9c-45b2-92f9-ef2512f7e7e4&order_uuid=30541bc7-e121-4cd1-8309-32e6258548d5&token=6b32ffb5-bac8-4947-a4a4-0fea057a150a&language=es
=> fix: NPE Order lines wihout product.

src/main/java/org/spin/grpc/service/GeneralLedgerServiceImplementation.java
Get `Accouting Combination` record using value as `Combination` column.
http://localhost:8085/api/adempiere/general-ledger/accounting-combination?token=7ce97e21-7704-4810-9260-4cf4c0a084b0&language=es&value=HQ-12110-_-_-Standard-_
Error Case:
```json
{
"code": 500,
"result": "Error:  Combinación Contable No encontrado"
}
```
Success Case:
```json
{
"code": 200,
"result": {
"id": 1000007,
"uuid": "79973871-eb10-42da-8285-73404f90e5b8",
"table_name": "C_ValidCombination",
{
"key": "AD_Client_ID",
"value": 11
},
{
"key": "AD_Org_ID",
"value": 11
},
{
"key": "Account_ID",
"value": 518
},
{
"key": "Alias",
"value": "Project Standard"
},
{
"key": "C_AcctSchema_ID",
"value": 101
},
{
"key": "C_Project_ID",
"value": 100
},
{
"key": "C_ValidCombination_ID",
"value": 1000007
},
{ …
```
=> feat: Get Accouting Combination with value as combination column.

src/main/java/org/spin/base/util/DictionaryUtil.java, src/main/java/org/spin/base/util/ReferenceUtil.java, src/main/java/org/spin/grpc/service/UserInterfaceServiceImplementation.java
When querying a table that has a translation table and the display column does not exist in the translation table, this generates an error when querying the data.
http://0.0.0.0:8085/api/adempiere/user-interface/window/entities?window_uuid=a52177c8-fb40-11e8-a479-7a0060f0aa01&tab_uuid=a4a0c3e4-fb40-11e8-a479-7a0060f0aa01&search_value=&page_token=0d0c73f8-c8ca-4d5b-b5c0-b2f8c1befc13-1&page_size=15&token=0d0c73f8-c8ca-4d5b-b5c0-b2f8c1befc13&language=es
Error Response
```json
{
"code": 200,
"result": {
"record_count": 5,
"records": []
}
}
```
Successfully Response
```json
{
"code": 200,
"result": {
"record_count": 5,
"records": [
{
"id": 117,
"uuid": "a564dda6-fb40-11e8-a479-7a0060f0aa01",
"table_name": "C_Conversion_Rate",
{ …
```
=> fixed: List entities with translations.

src/main/java/org/spin/base/util/ValueUtil.java, src/main/java/org/spin/grpc/service/UserInterfaceServiceImplementation.java
http://0.0.0.0:8085/api/adempiere/user-interface/window/run-callout?token=e4582708-8cd1-47b8-9fba-00644bf9fa20&language=es
```json
{
"code": 200,
"result": {
"result": "",
"values": {
"DeliveryRule": "R",
"DocumentNo": "<30000>",
"HasCharges": false,
"IsDropShip": false,
"OrderType": "PR",
"PaymentRule": "P"
}
}
}
```
Depends on https://github.com/solop-develop/gRPC-API/pull/45
=> fix: Callout get boolean values on attributes.

build-docker/Dockerfile.prod, build-docker/docker-compose.yml, src/main/java/org/spin/base/util/Services.java, src/main/java/org/spin/base/util/ValueUtil.java, src/main/java/org/spin/grpc/service/GeneralLedgerServiceImplementation.java, src/main/java/org/spin/grpc/service/MaterialManagementServiceImplementation.java, src/main/java/org/spin/server/AllInOneServices.java, src/main/proto/general_ledger.proto, src/main/proto/material_management.proto
Open tab info with accouting info:
=> feat: Accouting Fact Details.

build-docker/Dockerfile.prod, resources/standalone.yml, src/main/java/org/spin/base/util/Services.java, src/main/java/org/spin/grpc/service/MaterialManagementServiceImplementation.java
https://user-images.githubusercontent.com/45974454/193291633-6101af5c-6ea5-4c95-be9a-0abd21b98503.mp4
=> feat: Add product storage info.

build-docker/Dockerfile.prod, build-docker/docker-compose.yml, resources/standalone.yml, src/main/java/org/spin/base/util/Services.java, src/main/java/org/spin/grpc/service/TimeControlServiceImplementation.java, src/main/java/org/spin/server/AllInOneServices.java, src/main/proto/time_control.proto
Add services:
- Create Resource Assigment.
- List Resources Assigment
- Update Resource Assigment
- Delete Resource Assigment
=> feat: Time control

src/main/java/org/spin/grpc/service/AccessServiceImplementation.java
https://user-images.githubusercontent.com/20288327/193599682-c2a3821f-5dfd-4c4a-9889-fed86855392c.mp4
fixes https://github.com/solop-develop/frontend-core/issues/432
=> fix: Login with GardenAdmin user.

src/main/java/org/spin/grpc/service/TimeControlServiceImplementation.java, src/main/proto/time_control.proto
https://user-images.githubusercontent.com/20288327/193693074-77af41de-0eb7-476f-b433-d93f77586b02.mp4
=> feat: Add confirm Resource Assignment.

src/main/java/org/spin/base/util/DictionaryUtil.java, src/main/java/org/spin/grpc/service/BusinessPartnerServiceImplementation.java, src/main/java/org/spin/grpc/service/InOutServiceImplementation.java, src/main/java/org/spin/grpc/service/InvoiceServiceImplementation.java, src/main/java/org/spin/grpc/service/OrderServiceImplementation.java, src/main/java/org/spin/grpc/service/PaymentServiceImplementation.java, src/main/java/org/spin/grpc/service/ProductServiceImplementation.java, src/main/java/org/spin/grpc/service/UserInterfaceServiceImplementation.java
If the field has dynamic validation involving fields of the same table, it generates the sql ambiguous column error.
https://user-images.githubusercontent.com/20288327/194461167-b9d41a80-2b00-4dc0-9f10-85224745c873.mp4
```log
org.postgresql.util.PSQLException: ERROR: column reference "issotrx" is ambiguous Position: 5660
```
fixes: https://github.com/solop-develop/frontend-core/issues/277
=> fix: Field Search unparseable sql where clause.

src/main/java/org/spin/base/util/ConvertUtil.java, src/main/java/org/spin/grpc/service/PointOfSalesServiceImplementation.java, src/main/java/org/spin/grpc/service/TimeControlServiceImplementation.java, src/main/proto/point_of_sales.proto, src/main/proto/time_control.proto
https://user-images.githubusercontent.com/45974454/193930908-6993ecb9-66f8-4a8f-a979-2b6837a32ee8.mp4
=>  feat: Add resource to order line. 

src/main/java/org/spin/base/util/ContextManager.java
https://user-images.githubusercontent.com/20288327/194128186-fc84f092-96bf-4d42-b110-9e6a8e9155c7.mp4
https://user-images.githubusercontent.com/20288327/194128194-74fa264d-0b2e-4a75-82c8-6000fd4da1c5.mp4
Log message
```log
===========> UserInterfaceServiceImplementation.listLookupItems: class java.lang.Boolean cannot be cast to class java.lang.String (java.lang.Boolean and java.lang.String are in module java.base of loader 'bootstrap') [715]
```
Fixes: https://github.com/solop-develop/frontend-core/issues/439
=> fix: Set Boolean value on context.

src/main/java/org/spin/grpc/service/AccessServiceImplementation.java
https://user-images.githubusercontent.com/20288327/194333921-bc5f0e95-e8ed-4b26-a21e-0daf5f001b2e.mp4
https://user-images.githubusercontent.com/20288327/194333930-84ae15e3-61b6-4302-b350-f779aa012b19.mp4
=> fix: Revert login with role org assignment.

src/main/java/org/spin/grpc/service/AccessServiceImplementation.java, src/main/java/org/spin/grpc/service/CoreFunctionalityImplementation.java
When logging in with a role that has `Use User Org Access` checked and no organization access is added in the role but access is added in the user, it does not complete the login.
Likewise, if no organization access has been added in the role or user, but the `Access all Orgs` check is checked, it does not complete the login.
Before changes:
https://user-images.githubusercontent.com/20288327/194337514-f92bfbb5-a323-4c99-807d-f91e30d48a29.mp4
After changes:
https://user-images.githubusercontent.com/20288327/194337506-55b9295a-8dc6-4c7a-bd13-9d08e67c55ad.mp4
=> fix: Login with user organization access.

src/main/java/org/spin/grpc/service/UserInterfaceServiceImplementation.java
RV_InOutDetails Ship translation:
RV_InOutDetails Receive translation:
Zk Espanish:
https://user-images.githubusercontent.com/20288327/182394416-5db108a0-17b7-4c24-8321-e81f20daff11.mp4
Zk English:
https://user-images.githubusercontent.com/20288327/182394495-0da6804e-8661-4674-a47a-ab6680743de7.mp4
Proxy Request:
http://localhost:8085/api/adempiere/user-interface/process/report-views?table_name=RV_InOutDetails&process_uuid=a42b8480-fb40-11e8-a479-7a0060f0aa01&token=ec47d2ed-39e7-44bc-a595-5188131c1cad&language=es
Proxy Response:
```json
{
"code": 200,
"result": {
"records": [
{
"report_view_uuid": "a4883ee6-fb40-11e8-a479-7a0060f0aa01",
"name": "RV_InOutDetails Receive",
"table_name": "RV_InOutDetails"
},
{
"report_view_uuid": …
```
=> fix: Report View Traslated.

src/main/java/org/spin/base/util/ReferenceInfo.java
http://0.0.0.0:8085/api/adempiere/user-interface/window/lookup-items?field_uuid=8c043398-fb40-11e8-a479-7a0060f0aa01&reference_uuid=&search_value=&column_uuid=8c043398-fb40-11e8-a479-7a0060f0aa01&token=ce190db2-11b8-4bf8-baf2-45c1da98646e&language=es
https://user-images.githubusercontent.com/20288327/187748401-fd16a597-1e2a-4b9e-b6ca-668b8f17dc5c.mp4
```log
===========> UserInterfaceServiceImplementation.listLookupItems: Cannot invoke "org.compiere.model.MField.getAD_Field_ID()" because "field" is null [117]
```
https://user-images.githubusercontent.com/20288327/187748412-97bd472f-b413-44e5-917c-608c99d044fb.mp4
=> fix: WF Editor list workflow.

src/main/java/org/spin/grpc/service/DictionaryServiceImplementation.java
Zk Client:
Related on https://github.com/solop-develop/backend/issues/28
=> fix: Process/Report Parameters Translated.

src/main/java/org/spin/base/util/ConvertUtil.java, src/main/java/org/spin/base/util/ValueUtil.java
https://user-images.githubusercontent.com/20288327/196830721-661dab92-d264-47cd-b451-173a53721067.mp4
https://user-images.githubusercontent.com/20288327/196830779-7fea6762-5484-477c-9bb4-e9f237867032.mp4
fixes https://github.com/solop-develop/frontend-core/issues/481
Log error
```log
===========> MTest.set_Value: T_Number - Class invalid: class java.lang.Integer, Should be class java.math.BigDecimal: 1 [33]
```
=> fix: Set integer value as decimal value without presicion.

src/main/java/org/spin/grpc/service/TimeControlServiceImplementation.java, src/main/proto/time_control.proto
https://user-images.githubusercontent.com/20288327/194989611-c2178bb4-d3ad-4996-8fba-81361a15ce66.mp4
=> fix: List confirmed resource assigment.

src/main/java/org/spin/base/util/ReferenceUtil.java
Request:
http://0.0.0.0:8085/api/adempiere/user-interface/window/default-value?field_uuid=8ceb7a46-fb40-11e8-a479-7a0060f0aa01&value=109&token=aa30f777-045d-4639-a127-65828c77bf83&language=es
Response:
```json
{
"code": 200,
"result": {
"id": 109,
"uuid": "a575eb50-fb40-11e8-a479-7a0060f0aa01",
{
"value": "Monroe, CT06468, 40 Old Tannery Rd"
},
{
"value": 109
},
{
"key": "UUID",
"value": "a575eb50-fb40-11e8-a479-7a0060f0aa01"
}
]
}
}
```
Request:
http://0.0.0.0:8085/api/adempiere/user-interface/window/entities?window_uuid=a5212444-fb40-11e8-a479-7a0060f0aa01&tab_uuid=a4a0fdd2-fb40-11e8-a479-7a0060f0aa01&search_value=&page_token=aa30f777-045d-4639-a127-65828c77bf83-1&page_size=15&token=aa30f777-045d-4639-a127-65828c77bf83&language= …
=> feat: Add display column location address.

src/main/java/org/spin/grpc/service/WorkflowServiceImplementation.java
fixes https://github.com/solop-develop/frontend-core/issues/520
=> fix: Document statuses add initial status.

src/main/java/org/spin/grpc/service/AccessServiceImplementation.java
Support to start section with RoleUuid and organizationUuid
https://user-images.githubusercontent.com/45974454/197053122-7cc1152e-6f45-43b8-a45d-bc86d7aa12b7.mp4
Fixed: [#522](https://github.com/solop-develop/frontend-core/issues/522)
=> feat: Support to login with role uuid and organization uuid into url parameter

src/main/java/org/spin/base/util/ReferenceUtil.java
http://0.0.0.0:8085/api/adempiere/user-interface/window/default-value?field_uuid=8d070266-fb40-11e8-a479-7a0060f0aa01&value=1000001&token=aa30f777-045d-4639-a127-65828c77bf83&language=es
```json
{
"code": 200,
"result": {
"id": 1000001,
"uuid": "0ae57875-31f3-4d70-a1b3-9310a99860b1",
{
"value": "Asus_AMD_8_500"
},
{
"value": 1000001
},
{
"key": "UUID",
"value": "0ae57875-31f3-4d70-a1b3-9310a99860b1"
}
]
}
}
```
=> feat: Add support to display column on Product Set Attribute Instance.

src/main/java/org/spin/grpc/service/MaterialManagementServiceImplementation.java, src/main/proto/material_management.proto
```bash
curl --location --request POST 'http://0.0.0.0:8085/api/adempiere/material-management/list-product-attribute-set-instances?page_size=25&token=56155763-d50e-4b26-aef2-4172a8fc6970&language=es' \
--data-raw '{
"product_attribute_set_id": 1000000,
"product_id": 1234
}'
```
```json
{
"code": 200,
"result": {
"record_count": 3,
"records": [
{
"id": 1000000,
"uuid": "2082106e-f2aa-4011-b64d-9c5c696f9d73",
"description": "Asus_AMD_8_512",
"guarantee_date": 0,
"lot": "",
"lot_id": 0,
"serial": "",
"product_attribute_set": {
"id": 1000000,
"uuid": "e31d7cb6-df87-43a9-8720-ac8ba288c63c",
"name": "Computadora",
"is_instance_attribute": true,
"is_lot": false,
"is_lot_mandatory": false,
"lot_control_id": 0, …
```
=> feat: List Product Attribute Instances.

src/main/java/org/spin/grpc/service/PointOfSalesServiceImplementation.java, src/main/proto/point_of_sales.proto
https://user-images.githubusercontent.com/20288327/199141465-924aa644-d0d3-4614-b3d6-60a527e98aef.mp4
fixes https://github.com/solop-develop/frontend-core/issues/542
=> fix: POS set Sales Representative.

src/main/java/org/spin/grpc/service/DictionaryServiceImplementation.java
Additional context:
Fixes https://github.com/solop-develop/frontend-core/issues/543
=> fix: Duplicated process associated on tab.

src/main/java/org/spin/grpc/service/UserInterfaceServiceImplementation.java, src/main/proto/business.proto
1. Open `Print Format` window.
2. Displayed options on `Format Item` tab.
3. Select `Displayed Order` or `Sort Order`.
https://user-images.githubusercontent.com/20288327/200078575-78a108ac-0ab3-4df6-9281-31a8d0491560.mp4
```bash
curl --location --request POST 'http://0.0.0.0:8085/api/adempiere/user-interface/component/tab-sequence/list-tab-sequences?page_token=493edb1d-8f9c-44fe-9087-6665823b735e-1&page_size=15&token=493edb1d-8f9c-44fe-9087-6665823b735e&language=es' \
--data-raw '{
"tab_uuid": "a49f96b8-fb40-11e8-a479-7a0060f0aa01",
"context_attributes": [{
"value": 50338,
"key": "AD_PrintFormat_ID"
}]
}
'
```
```json
{
"code": 200,
"result": {
"record_count": 52,
"next_page_token": "493edb1d-8f9c-44fe-9087-6665823b735e-2",
"records": [
{
"id": …
```
=> feat: List Tab Sequence.

src/main/java/org/spin/grpc/service/UserInterfaceServiceImplementation.java, src/main/proto/base_data_type.proto, src/main/proto/business.proto
1. Open `Print Format` window.
2. Show tab obtions on `Format Item` tab child
3. Select `Display Order` sort tab.
https://user-images.githubusercontent.com/20288327/200404114-2f3ebfcc-8bd1-472a-92e7-1ef8c6983129.mp4
Fixes https://github.com/solop-develop/frontend-core/issues/554
=> feat: Save sequence on sort tab.

src/main/java/org/spin/grpc/service/DictionaryServiceImplementation.java
`Address 1` field on address location form
http://0.0.0.0:8085/api/adempiere/dictionary/field?uuid=8cee7c14-fb40-11e8-a479-7a0060f0aa01&token=85c57c1a-85ae-42c2-9442-ac760768fa34&language=es
`Alias` field on accouting combination form
http://0.0.0.0:8085/api/adempiere/dictionary/field?uuid=8cead820-fb40-11e8-a479-7a0060f0aa01&token=85c57c1a-85ae-42c2-9442-ac760768fa34&language=es
`Combination` field on accouting combination form
http://0.0.0.0:8085/api/adempiere/dictionary/field?uuid=8d54b3c6-fb40-11e8-a479-7a0060f0aa01&token=85c57c1a-85ae-42c2-9442-ac760768fa34&language=es
fixes: https://github.com/solop-develop/frontend-core/issues/560
=> fix: Failed load fields on form.

src/main/java/org/spin/grpc/service/MaterialManagementServiceImplementation.java, src/main/proto/material_management.proto
```bash
curl --location --request POST 'http://0.0.0.0:8085/api/adempiere/material-management/get-product-attribute-set-instance?page_size=25&token=56155763-d50e-4b26-aef2-4172a8fc6970&language=es' \
--data-raw '{
"id": 1000050,
"product_id": 50000
}'
```
```bash
curl --location --request POST 'http://0.0.0.0:8085/api/adempiere/material-management/save-product-attribute-set-instance?page_size=25&token=56155763-d50e-4b26-aef2-4172a8fc6970&language=es' \
--data-raw '{
{
"value": 100,
"key": "e9144606-69fd-417d-a4f9-93bfe21f838f"
},
{
"value": 102,
"key": "3c935f84-655d-416d-bcc5-f2293d5e0117"
},
{
"value": "ads",
"key": "94f4bde2-77b9-416f-aa99-2dbdde6f13c9"
}
],
"id": 1000050
}'
``` …
=> feat: Save and Get attribute set instance. 

.idea/runConfigurations/AllInOneServices.xml, src/main/java/org/spin/base/util/ContextManager.java, src/main/java/org/spin/base/util/ConvertUtil.java, src/main/java/org/spin/base/util/DictionaryUtil.java, src/main/java/org/spin/base/util/RecordUtil.java, src/main/java/org/spin/base/util/ReferenceInfo.java, src/main/java/org/spin/base/util/ReferenceUtil.java, src/main/java/org/spin/base/util/ValueUtil.java, src/main/java/org/spin/grpc/service/AccessServiceImplementation.java, src/main/java/org/spin/grpc/service/BusinessDataServiceImplementation.java, src/main/java/org/spin/grpc/service/BusinessPartnerServiceImplementation.java, src/main/java/org/spin/grpc/service/CoreFunctionalityImplementation.java, src/main/java/org/spin/grpc/service/DashboardingServiceImplementation.java, src/main/java/org/spin/grpc/service/DictionaryServiceImplementation.java, src/main/java/org/spin/grpc/service/InOutServiceImplementation.java, src/main/java/org/spin/grpc/service/InvoiceServiceImplementation.java, src/main/java/org/spin/grpc/service/LogsServiceImplementation.java, src/main/java/org/spin/grpc/service/MaterialManagementServiceImplementation.java, src/main/java/org/spin/grpc/service/OrderServiceImplementation.java, src/main/java/org/spin/grpc/service/PaymentServiceImplementation.java, src/main/java/org/spin/grpc/service/PayrollActionNoticeServiceImplementation.java, src/main/java/org/spin/grpc/service/PointOfSalesServiceImplementation.java, src/main/java/org/spin/grpc/service/ProductServiceImplementation.java, src/main/java/org/spin/grpc/service/UpdateImplementation.java, src/main/java/org/spin/grpc/service/UserInterfaceServiceImplementation.java, src/main/java/org/spin/grpc/service/WebStoreServiceImplementation.java, src/main/java/org/spin/grpc/service/WorkflowServiceImplementation.java, src/main/proto/base_data_type.proto, src/main/proto/business.proto, src/main/proto/material_management.proto
- Support to sort tab.
- Support to product set attribute fields.
- Add Display column on address location fields.
- Add IntelliJ Launcher
- Process parameter translation.
- Report view translation.
- Loaad form fields.
- Save window record with BigDecimal value without scale.
- Set boolean value on context by context column names.
- List all organizations when isAccessAllOrgs flag is true
Please acept this pull request with merge (no squash)
=> feat: Update 3.9.3 support with experimental branch

src/main/java/org/spin/grpc/service/UserInterfaceServiceImplementation.java
If the uuid of the tab is not sent or the uuid is nonexistent, there was no way to know it, since it still returned a default builder with empty values, implying that there were simply no changes in fields, when the truth is that the tab was not obtained and the callout was never executed.
=> fix: Callout throw execption when tab not found.

src/main/java/org/spin/base/util/DictionaryUtil.java, src/main/java/org/spin/base/util/RecordUtil.java, src/main/java/org/spin/grpc/service/UserInterfaceServiceImplementation.java
http://0.0.0.0:8085/api/adempiere/user-interface/window/lookup-items?field_uuid=8cee676a-fb40-11e8-a479-7a0060f0aa01&search_value=Ventana&column_name=AD_Table_ID&token=493edb1d-8f9c-44fe-9087-6665823b735e&language=es
```json
{
"code": 200,
"result": {
"record_count": 8,
"records": [
{
"id": 896,
"uuid": "a4a9f0f4-fb40-11e8-a479-7a0060f0aa01",
"table_name": "AD_Table",
"values": {
"DisplayColumn": "AD_InfoWindow_Trl_Ventana de información **",
"KeyColumn": 896,
"UUID": "a4a9f0f4-fb40-11e8-a479-7a0060f0aa01"
}
},
{
"id": 895,
"uuid": "a4a76d84-fb40-11e8-a479-7a0060f0aa01",
"table_name": "AD_Table",
"values": {
"DisplayColumn": "AD_InfoWindow_Ventana de información",
"KeyColumn": 895,
"UUID": "a4a76d84-fb40-11e8-a479-7a0060f0aa01"
}
},
{
"id": 467,
"uuid": …
```
=> fix: Search in lookup with other language.

src/main/java/org/spin/base/util/DictionaryUtil.java, src/main/java/org/spin/base/util/RecordUtil.java, src/main/java/org/spin/base/util/ReferenceUtil.java, src/main/java/org/spin/grpc/service/BusinessPartnerServiceImplementation.java, src/main/java/org/spin/grpc/service/GeneralLedgerServiceImplementation.java, src/main/java/org/spin/grpc/service/InOutServiceImplementation.java, src/main/java/org/spin/grpc/service/InvoiceServiceImplementation.java, src/main/java/org/spin/grpc/service/OrderServiceImplementation.java, src/main/java/org/spin/grpc/service/PaymentServiceImplementation.java, src/main/java/org/spin/grpc/service/ProductServiceImplementation.java, src/main/java/org/spin/grpc/service/UserInterfaceServiceImplementation.java
Testing windows:
* Currency Rate.
* Sales Order.
* Purchase Order.
* Business Partner.
* Product.
* Window.
* Table.
* View.
* Smart Browser.
* Address Location.
Testing on Reports:
* Open Items.
* Storage Detail.
* Transaction Detail.
Testing on Forms:
* Address Location.
* Order.
* Business Partner.
* Accouting Combination.
* Product.
fixes https://github.com/solop-develop/frontend-core/issues/476
fixes https://github.com/solop-develop/frontend-core/issues/404
=> fix: Translation search window and lookup fields.

src/main/java/org/spin/grpc/service/DictionaryServiceImplementation.java
https://user-images.githubusercontent.com/20288327/203587197-57f6011d-a44c-424a-8afa-811dff7b5237.mp4
https://user-images.githubusercontent.com/20288327/203587209-23becb25-74be-4dd1-8563-6581bce08e68.mp4
fixes https://github.com/solop-develop/frontend-core/issues/476
related https://github.com/solop-develop/backend/issues/28
=> fix: Load window field with other lang.

src/main/java/org/spin/base/util/RecordUtil.java, src/main/java/org/spin/grpc/service/UserInterfaceServiceImplementation.java
https://user-images.githubusercontent.com/31936815/204646686-07971c63-1e06-4ef0-9507-1de4421c32cc.mp4
https://user-images.githubusercontent.com/20288327/204688490-f5ceb8c3-f8b9-4db2-a0bf-dd9515bd86d0.mp4
fixes https://github.com/solop-develop/frontend-core/issues/612
=> fix: Search record on other lang.

src/main/java/org/spin/base/util/ContextManager.java, src/main/java/org/spin/base/util/ValueUtil.java
Fix values on callout with string values.
=> fix: Value Type on callout.

src/main/java/org/spin/grpc/service/UserInterfaceServiceImplementation.java
https://user-images.githubusercontent.com/20288327/204944923-78ed5e79-fa00-4e5a-9c52-e34b0f4d1c25.mp4
fixes https://github.com/solop-develop/frontend-core/issues/561
=> fix: Callout set context values.

src/main/java/org/spin/base/util/DictionaryUtil.java
Added regular expression to read for sql `IN`, `NOT IN`, `BETWEEN`, `NOT BETWEEN`, `LIKE`, `NOT LIKE`, `IS NULL`, IS NOT NULL` operators in dynamic validations as they must have the alias of the table to prevent ambiguous column errors.
```bash
curl --location --request GET 'http://0.0.0.0:8085/api/adempiere/grid/general-info?field_uuid=8db9739c-fb40-11e8-a479-7a0060f0aa01&table_name=A_Asset&column_name=A_Asset_ID&page_token=ae441cc7-0637-4f48-9747-13570e112dd3-1&page_size=15&token=ae441cc7-0637-4f48-9747-13570e112dd3&language=es'
```
Error:
```json
{
"code": 500,
"result": "org.postgresql.util.PSQLException: ERROR: column reference \"a_asset_status\" is ambiguous\n  Position: 2113, SQL=SELECT COUNT(*)  FROM A_Asset AS A_Asset LEFT JOIN AD_Ref_List AS A_Asset_Action_AD_Ref_List …
```
=> fix: Search with sql IN validation.

src/main/java/org/spin/grpc/service/PointOfSalesServiceImplementation.java, src/main/java/org/spin/pos/service/CashManagement.java, src/main/proto/point_of_sales.proto
- Add PrintShipmentPreview service
- Fixed error with cash opening
Add some validations:
- Cash Opening
- Previous Cash Opening
- WriteOffAmount based on custom currency
=> feat: Update experimental branch with 3.9.3 support branch.

src/main/java/org/spin/base/util/ContextManager.java, src/main/java/org/spin/base/util/DictionaryUtil.java, src/main/java/org/spin/base/util/RecordUtil.java, src/main/java/org/spin/base/util/ReferenceUtil.java, src/main/java/org/spin/base/util/ValueUtil.java, src/main/java/org/spin/grpc/service/BusinessPartnerServiceImplementation.java, src/main/java/org/spin/grpc/service/DictionaryServiceImplementation.java, src/main/java/org/spin/grpc/service/GeneralLedgerServiceImplementation.java, src/main/java/org/spin/grpc/service/InOutServiceImplementation.java, src/main/java/org/spin/grpc/service/InvoiceServiceImplementation.java, src/main/java/org/spin/grpc/service/OrderServiceImplementation.java, src/main/java/org/spin/grpc/service/PaymentServiceImplementation.java, src/main/java/org/spin/grpc/service/ProductServiceImplementation.java, src/main/java/org/spin/grpc/service/UserInterfaceServiceImplementation.java, src/main/proto/base_data_type.proto
- fix: Search with sql IN validation.
- fix: Callout set context values. 
- fix: Value Type on callout. 
- fix: Search record on other lang. 
- fix: Load window field with other lang. 
- fix: Translation search window and lookup fields. 
- fix: Search in lookup with other language. 
- fix: Callout throw execption when tab not found. 
- fix: Search text with like as default operator.
=> feat: Update 3.9.3 with experimental

src/main/java/org/spin/base/util/RecordUtil.java, src/main/java/org/spin/base/util/ReferenceUtil.java
https://stackoverflow.com/questions/37442358/match-a-pattern-and-write-the-stream-to-a-file-using-java-8-stream
=> fix: Matcher results Java 8 compatibility.

src/main/java/org/spin/grpc/service/FileManagementServiceImplementation.java, src/main/proto/file_management.proto
- Enclose setResourceReference into Trx.run.
- Replace `resetAttachmentCacheFromId(fileHandlerId, attanchmentId)` by `resetAttachmentReferenceCache(fileHandlerId, MADAttachmentReference)`
=> feat: Improve file management services.

README.md, build-docker/Dockerfile.prod, build-docker/docker-compose.yml, build-docker/stack.yml
Add `Time Zone` environment variable on container.
=> feat: Add time zone on container.

src/main/java/org/spin/grpc/service/UserInterfaceServiceImplementation.java, src/main/proto/business.proto
Get record count on references.
http://192.168.3.110:8085/api/adempiere/user-interface/window/exists-references?id=53761&uuid=8cc0fed8-fb40-11e8-a479-7a0060f0aa01&tab_uuid=a4a0c52e-fb40-11e8-a479-7a0060f0aa01&token=e8b63440-69e8-42f5-bc83-66a668a55e23&language=es
https://user-images.githubusercontent.com/45974454/209194764-b91aeb39-eaee-4d6d-a078-05768af6f216.mp4
fixes https://github.com/solop-develop/frontend-core/issues/486
=> feat: Exists record references

build-docker/Dockerfile.prod, build-docker/docker-compose.yml, build-docker/stack.yml, resources/standalone.yml, src/main/java/org/spin/base/util/ReferenceUtil.java, src/main/java/org/spin/base/util/Services.java, src/main/java/org/spin/grpc/service/PaymentPrintExportServiceImplementation.java, src/main/java/org/spin/server/AllInOneServices.java, src/main/proto/payment_print_export.proto
Create a new services:
- ListPaymentSelection
- GetPaymentSelection
- ListPaymentRules
- GetDocumentNo
- CreateEFTPayment
- ExportPayments
- PrintPayments
- ConfirmPrint
- PrintRemittance
=> feat: Payment Print/Export.

src/main/java/org/spin/grpc/service/PaymentPrintExportServiceImplementation.java, src/main/proto/payment_print_export.proto
Fix Servies:
- List Payment Rules.
- List Payments.
- Process.
http://0.0.0.0:8085/api/adempiere/form/addons/payment-print-export/process?token=ecd4bb2e-d779-4a73-b9a4-ac16243605b9&language=es
```json
{
"code": 200,
"result": {}
}
```
=> fix: Payment Print/Export services.

src/main/java/org/spin/grpc/service/PaymentPrintExportServiceImplementation.java, src/main/proto/payment_print_export.proto
Add final balance to preview amount on payment list.
=> feat: Add final balace on Payment List.

src/main/java/org/spin/grpc/service/CoreFunctionalityImplementation.java
When you list the organizations associated to a role that is inactive or you do not get the role, you will get the organization `*`, even if you do not have access or if the role does not exist.
The role used is `FA User` which besides being inactive, has no access to any organization, nor as a user, and is not marked as having access to all organizations.
http://localhost:8085/api/adempiere/common/organizations?role_uuid=a48d309a-fb40-11e8-a479-7a0060f0aa01&pageSize=15&token=f0307f9f-3ae1-41f5-b1dc-931c28f2d9d0&language=en
```json
{
"code": 200,
"result": {
"records": [
{
"id": 0,
"uuid": "a3e5c878-fb40-11e8-a479-7a0060f0aa01",
"name": "*",
"description": "All Organizations",
"is_read_only": false,
"duns": "0",
"tax_id": "0", …
```
=> fix: List Organization without role.

src/main/java/org/spin/base/util/ContextManager.java, src/main/java/org/spin/grpc/service/AccessServiceImplementation.java
https://user-images.githubusercontent.com/20288327/210658510-a471655c-5da9-4094-84f7-306747f9fd41.mp4
https://user-images.githubusercontent.com/20288327/210658589-4e33d6f0-e047-4d4a-a277-aa60010b172e.mp4
fixes https://github.com/solop-develop/frontend-core/issues/685
=> fix: Get request with session close.

src/main/java/org/spin/grpc/service/AccessServiceImplementation.java
https://user-images.githubusercontent.com/20288327/210654995-70924ce3-2122-4a3f-b390-747f66d17277.mp4
https://user-images.githubusercontent.com/20288327/210655017-eeea66b6-a1c1-4ff2-b8d5-dffc85df5464.mp4
fixes https://github.com/solop-develop/frontend-core/issues/684
=> fix: List roles without access.

src/main/java/org/spin/grpc/service/UserInterfaceServiceImplementation.java, src/main/proto/business.proto
1. Open `Organization` or `Element Account` window.
2. Change to `Single Record`.
https://user-images.githubusercontent.com/20288327/212406813-39b403a3-2c2f-47df-84ce-b8f8985d5728.mp4
https://user-images.githubusercontent.com/20288327/212406816-b41a29d4-92f8-4a58-91bb-a82821f82d38.mp4
- Your OS:
- Web Browser:
- Node.js version:
- Yarn version:
- adempiere-vue version: 
fixes https://github.com/solop-develop/frontend-core/issues/686
=> feat: List nodes on tab tree.

src/main/java/org/spin/grpc/service/UserInterfaceServiceImplementation.java, src/main/proto/business.proto
Add `Create Tab Entity` and `Update Tab Entity` with display columns returned on entity attributes.
- Create Tab Entity
```bash
curl --location --request POST 'http://0.0.0.0:8085/api/adempiere/user-interface/window/create-entity?token=ca1e69ba-709a-4144-9ccf-7b0907021090&language=es' \
--data-raw '{
"tab_uuid": "a49f84ca-fb40-11e8-a479-7a0060f0aa01",
{
"key": "AD_Client_ID",
"value": 11
},
{
"key": "AD_Org_ID",
"value": 50006
},
{
"key": "AD_PrintColor_ID",
"value": 100
},
{
"key": "IsConfidentialInfo",
"value": false
},
{
"key": "M_PriceList_ID",
"value": 101
},
{
"key": "C_Dunning_ID",
"value": 100
},
{
"key": "Name",
"value": "Test"
}
]
}
'
```
```json
{
"code": 200,
"result": {
"id": 1000002,
"uuid": …
```
=> feat: Create/Update Tab Entity with display columns.

build-docker/docker-compose.yml, build-docker/production-alpine.Dockerfile, build-docker/production.Dockerfile, build-docker/stack.yml, resources/standalone.yml, src/main/java/org/spin/base/util/Services.java, src/main/java/org/spin/base/util/ValueUtil.java, src/main/java/org/spin/grpc/service/IssueManagementServiceImplementation.java, src/main/java/org/spin/server/AllInOneServices.java, src/main/proto/issue_management.proto
Add new request services:
1. ListRequestTypes
2. ListSalesRepresentatives
3. ListPriorities
4. ListStatuses
5. ExistsIssues
6. ListIssues
7. CreateIssue
8. UpdateIssue
9. DeleteIssue
10. ListIssueComments
11. CreateIssueComment
12. UpdateIssueComment
13. DeleteIssueComment
related https://github.com/solop-develop/frontend-core/issues/485
=> feat: Add request services.

.vscode/launch.json, .vscode/settings.json
https://user-images.githubusercontent.com/20288327/213840666-36d6c4fd-1647-4b9b-a956-9ac9d3c45173.mp4
=> feat: Launch visual studio code.

src/main/java/org/spin/grpc/service/IssueManagementServiceImplementation.java
Issue status was not reaching the customer
```bash
curl --location --request POST 'http://0.0.0.0:8085/api/adempiere/user-interface/component/issue/list-issues?token=dba793a8-949c-4013-82b9-1005e1303213&language=en' \
--data-raw '{
"table_name": "C_BPartner",
"record_id": 113,
"record_uuid": "d430bdde-e5e4-476b-8dc9-4b0b5d5b02cc"
}
'
```
```json
{
"code": 200,
"result": {
"records": [
{
"id": 1000002,
"uuid": "a8782ac4-9cc8-4318-b32f-3703c3a75fb5",
"document_no": "10000002",
"subject": "Test 1",
"summary": "Prueba de algo",
"created": 1674338908000,
"last_updated": 1674338908000,
"request_type": {
"id": 100,
"uuid": "03a0da1b-71f7-4706-ade6-233d117f0165",
"name": "Request for Quotation",
"description": …
```
=> fix: Issue Status not found.

src/main/java/org/spin/base/util/WorkflowUtil.java, src/main/java/org/spin/grpc/service/WorkflowServiceImplementation.java, src/main/proto/workflow.proto
Add new services:
- Forward workflow activity.
```bash
curl --location --request POST 'http://0.0.0.0:8085/api/adempiere/workflow/forward-workflow-activity?token=dba793a8-949c-4013-82b9-1005e1303213&language=en' \
--data-raw '{
"id": 1,
"uuid": "",
"message": "test",
"user_id": 100,
"user_uuid": ""
}'
```
- Process workflow activity.
```bash
curl --location --request POST 'http://0.0.0.0:8085/api/adempiere/workflow/process-workflow-activity?token=dba793a8-949c-4013-82b9-1005e1303213&language=en' \
--data-raw '{
"id": 1,
"uuid": "",
"message": "test",
"is_approved": true
}'
```
Related https://github.com/solop-develop/frontend-core/issues/470
Related …
=> feat: Workflow Activity process and forward services.

src/main/java/org/spin/grpc/service/IssueManagementServiceImplementation.java
```bash
curl --location --request POST 'https://api-develop.solopcloud.com/api/adempiere/user-interface/component/issue/create-issue-comment?token=80196b5e-1a94-4c55-8667-cb37c2aff066&language=es' \
--data-raw '{
"issue_id": 1000011,
"issue_uuid": "63505cb8-4e5d-4a8b-b891-45650d3b6468",
"result": "epale"
}'
```
```log
ERROR: null value in column \"r_request_id\" of relation \"r_requestupdate\" violates not-null constraint\n  Detail: Failing row contains (1000011, 11, 0, Y, 2023-01-24 12:04:40, 100, 2023-01-24 12:04:40, 100, null, A, null, null, 0, 0, null, Prueba 15dasdasdasda, 38803858-c55c-4d75-a810-7ddcb260dbbe, null, null, N)."
````
=> fix: Update issue comment.

src/main/java/org/spin/grpc/service/DashboardingServiceImplementation.java, src/main/proto/dashboarding.proto
Add dashboard to activities notice:
- Notes.
- Requests.
- Workflow Activities.
http://localhost:8085/api/adempiere/dashboard/list-notifications?token=0d511d72-2b2d-47d6-ba6e-9ad40540e971&language=es&ts=1674586436406
```json
{
"code": 200,
"result": {
"records": [
{
"name": "Aviso",
"description": "Ver avisos del sistema",
"quantity": 0,
"action": 0,
"action_name": "WINDOW",
"action_uuid": "8e511986-fb40-11e8-a479-7a0060f0aa01"
},
{
"name": "Solicitud",
"description": "Trabajar en sus solicitudes",
"quantity": 9,
"action": 0,
"action_name": "WINDOW",
"action_uuid": "8e510176-fb40-11e8-a479-7a0060f0aa01"
},
{
"name": "Actividades de Flujo de Trabajo",
"description": "Actividades Flujo de Trabajo activas",
"quantity": 0,
"action": 4,
"action_name": …
```
=> feat: Add dashboard notice.

src/main/java/org/spin/grpc/service/IssueManagementServiceImplementation.java
Delete Request Actions and Request Updates before delete Request header.
fixes https://github.com/solop-develop/frontend-core/issues/779
=> fix: Delete request header.

build-docker/docker-compose.yml, build-docker/production-alpine.Dockerfile, build-docker/production.Dockerfile, build-docker/stack.yml, resources/standalone.yml, src/main/java/org/spin/base/util/Services.java, src/main/java/org/spin/grpc/service/UserCustomizationImplementation.java, src/main/java/org/spin/server/AllInOneServices.java, src/main/proto/user_customization.proto
Add new services to user customization:
- List Users.
- List Roles.
- List Customization Level.
- Save Window Customization.
- Save Process/Report Customization.
- Save Browse Customization.
https://documenter.getpostman.com/view/3549586/2s8ZDeSyK9#b9c55870-ecb9-4225-b040-16057df5f384
fixes https://github.com/solop-develop/frontend-core/issues/712
fixes https://github.com/solop-develop/frontend-core/issues/715
fixes https://github.com/solop-develop/frontend-core/issues/710
fixes https://github.com/solop-develop/frontend-core/issues/716
=> feat: Save customization (Window, Process, Browse).

src/main/java/org/spin/grpc/service/IssueManagementServiceImplementation.java
https://user-images.githubusercontent.com/20288327/215191880-d72bfab1-0285-40b0-965b-47d68dbe8250.mp4
fixes https://github.com/solop-develop/frontend-core/issues/794
=> fix: Issue (Request) set source values.

src/main/java/org/spin/grpc/service/UserCustomizationImplementation.java
https://user-images.githubusercontent.com/45974454/215189553-1d0b1360-9626-41db-8abf-228f9e33ac37.mp4
fixes: [#710](https://github.com/solop-develop/frontend-core/issues/710)
fixes: [#712](https://github.com/solop-develop/frontend-core/issues/712)
fixes: [#715](https://github.com/solop-develop/frontend-core/issues/715)
fixes: [#716](https://github.com/solop-develop/frontend-core/issues/716)
=> fix: Save customization (Process/Report/Browse/Window).

src/main/java/org/spin/base/util/ValueUtil.java, src/main/java/org/spin/grpc/service/IssueManagementServiceImplementation.java, src/main/proto/issue_management.proto
http://0.0.0.0:8085/api/adempiere/user-interface/component/issue/list-issue-comments?token=dba793a8-949c-4013-82b9-1005e1303213&language=en
```json
{
"code": 200,
"result": {
"records": [
{
"id": 1000015,
"uuid": "2526e6f7-14da-47e8-9c39-57744d878952",
"result": "New Comment ",
"created": 1674585318000,
"date_next_action": 0,
"user_id": 100,
"user_uuid": "a4bd438e-fb40-11e8-a479-7a0060f0aa01",
"user_name": "SuperUser",
"issue_comment_type": 0,
"issue_comment_type_name": "COMMENT",
"label": "",
"displayed_value": ""
},
{
"id": 1000039,
"uuid": "6a0646b6-cdb0-4631-b085-891331a094ec",
"result": "",
"created": 1675016990000,
"date_next_action": 0,
"user_id": 101,
"user_uuid": "bef95ce0-1b93-411f-8eb3-170040f94f96",
"user_name": "GardenAdmin", …
```
=> feat: Add request history as comment.

src/main/java/org/spin/grpc/service/UserInterfaceServiceImplementation.java
http://0.0.0.0:8085/api/adempiere/user-interface/window/default-value?field_uuid=8d2dec0a-fb40-11e8-a479-7a0060f0aa01&id=57505&value=D&token=0e2300de-4c5e-4776-bfac-741514937cdd&language=es&ts=1674577084088
```log
-----------> UserInterfaceServiceImplementation.getDefaultKeyAndValue: For input string: "D" [24]
-----------> UserInterfaceServiceImplementation.getDefaultKeyAndValue: For input string: "D" [24]
```
=> fix: Default value error.

src/main/java/org/spin/grpc/service/IssueManagementServiceImplementation.java
```log
===========> IssueManagementServiceImplementation.listIssues: Index: 291, Size: 0 [119]
```
```json
{
"code": 200,
"result": {
"record_count": 4,
"records": [
{
"id": 1000010,
"uuid": "f92919e8-b020-4311-a27c-2b7d50ef6154",
"document_no": "10000010",
"subject": "El Raton esta en la nevera",
"summary": " o En el Filtro del agua ",
"created": 1675014211000,
"last_updated": 1675014211000,
"request_type": {
"id": 101,
"uuid": "791f551d-faac-4be1-a0ba-342ba382788d",
"name": "Service Request",
"description": ""
},
"user_id": 100,
"user_uuid": "a4bd438e-fb40-11e8-a479-7a0060f0aa01",
"user_name": "SuperUser",
"sales_representative": {
"id": 102,
"uuid": "6f7f66e7-c2c2-4254-9965-3c9f516d218b",
"name": "GardenUser",
"description": …
```
=> fix: List Issues (Requests).

src/main/java/org/spin/grpc/service/UserInterfaceServiceImplementation.java, src/main/proto/business.proto
http://0.0.0.0:8085/api/adempiere/user-interface/component/list-mail-templates?token=dba793a8-949c-4013-82b9-1005e1303213&language=es&search_value&page_size&page_token
```json
{
"code": 200,
"result": {
"records": [
{
"id": 50001,
"uuid": "a607dc54-fb40-11e8-a479-7a0060f0aa01",
"name": "Password Reset",
"subject": "Password Reset",
"mail_text": "<div id=\":rv\" class=\"ii gt\"><div id=\":qd\" class=\"a3s aXjCH m150616a0629b2c50\"><u></u>\n  <div marginheight=\"0\" marginwidth=\"0\" style=\"background:#fafafa;color:#222222;font-family:'Helvetica','Arial',sans-serif;font-size:14px;font-weight:normal;line-height:19px;margin:0;min-width:100%;padding:0;text-align:left;width:100%!important\" bgcolor=\"#fafafa\">\n    <table …
```
=> feat: Add list mail template.

src/main/java/org/spin/grpc/service/IssueManagementServiceImplementation.java
http://0.0.0.0:8085/api/adempiere/user-interface/component/issue/list-issue-comments?token=dba793a8-949c-4013-82b9-1005e1303213&language=es
```json
{
"code": 200,
"result": {
"record_count": 4,
"records": [
{
"id": 1000019,
"uuid": "5a63a6ad-ca82-4cb2-bf20-dd0653ee759e",
"result": "",
"created": 1674585325000,
"date_next_action": 0,
"user_id": 100,
"user_uuid": "a4bd438e-fb40-11e8-a479-7a0060f0aa01",
"user_name": "SuperUser",
"issue_comment_type": 1,
"issue_comment_type_name": "LOG",
"label": "Agente Comercial",
"new_value": 101,
"displayed_value": "GardenAdmin"
},
{
"id": 1000020,
"uuid": "51a4a084-a9c1-4c12-b939-2140e6f4dbca",
"result": "",
"created": 1674585329000,
"date_next_action": 0,
"user_id": 100,
"user_uuid": "a4bd438e-fb40-11e8-a479-7a0060f0aa01", …
```
=> fix: Issue comment label translation.

src/main/java/org/spin/grpc/service/IssueManagementServiceImplementation.java
https://user-images.githubusercontent.com/45974454/216142572-fb1c1e20-1934-430d-aaf4-88936aac6aa3.mp4
fixes https://github.com/solop-develop/frontend-core/issues/782
fixes https://github.com/solop-develop/frontend-core/issues/781
=> fix: Edit/Delete issue comment created by same user.

src/main/java/org/spin/base/util/ValueUtil.java, src/main/java/org/spin/grpc/service/IssueManagementServiceImplementation.java, src/main/proto/issue_management.proto
Add `Due Type` and `Date Next Action` on issue, and `Due Date Tolerance` on request type.
```json
{
"code": 200,
"result": {
"records": [
{
"id": 1000027,
"uuid": "24496c8e-f550-45b3-aac0-0bab915115dc",
"document_no": "10000027",
"subject": "Test 1 Garden Admin",
"summary": "summary **test**",
"created": 1675350973000,
"last_updated": 1675350973000,
"request_type": {
"id": 101,
"uuid": "791f551d-faac-4be1-a0ba-342ba382788d",
"name": "Service Request",
"due_date_tolerance": 7
},
"user_id": 102,
"user_uuid": "6f7f66e7-c2c2-4254-9965-3c9f516d218b",
"user_name": "GardenUser",
"sales_representative": {
"id": 102,
"uuid": "6f7f66e7-c2c2-4254-9965-3c9f516d218b",
"name": "GardenUser",
"description": "GardenUser"
},
"status": {
"id": …
```
=> feat: Add date next action on request.

src/main/java/org/spin/grpc/service/IssueManagementServiceImplementation.java
When updating the application staus does not set the value.
fixes https://github.com/solop-develop/frontend-core/issues/778
=> fix: Update issue set status.

src/main/java/org/spin/base/util/WorkflowUtil.java, src/main/java/org/spin/grpc/service/WorkflowServiceImplementation.java, src/main/proto/workflow.proto
Add zoom window structure into workflow activity
http://localhost:8085/api/adempiere/workflow/workflow-activities?user_uuid=bef95ce0-1b93-411f-8eb3-170040f94f96&page_size=15&token=61c4788b-01f6-4502-886a-10824c93a2df&language=es&ts=1675364344633
fixes https://github.com/solop-develop/frontend-core/issues/812
=> feat: Add zoom window from workflow activity.

.idea/runConfigurations/AllInOneServices.xml, .project, .settings/org.eclipse.jdt.core.prefs, .vscode/launch.json, build.gradle, resources/standalone.yaml, tools/ADempiere Backend.launch
```bash
gradle run --args="'resources/standalone.yaml'"
```
https://user-images.githubusercontent.com/20288327/217367920-5943a3b7-edad-4c62-b99f-fee17a3fdfb4.mp4
=> feat: Run backend application with gradle.

.github/workflows/publish.yml, build-docker/backend.env, build-docker/development.Dockerfile, build-docker/docker-compose.yaml, build-docker/production-alpine.Dockerfile, build-docker/stack.yml
Build docker image as development
Run backend and database containers with docker-compose.
=> fix: Build docker image and docker compose.

README.md
- Add run with gradle.
- Add build docker image as development.
- Fix run with docker-compose.
=> docs: Update readme to run backend project.

.github/workflows/ci.yml, README.es.md, README.md
=> docs: Add spanish readme.

.github/workflows/ci.yml, .github/workflows/publish.yml, build.gradle
The `actions/setup-java@v3` implement gradle `8.0`
This change building with `gradle` 7.2 version
See https://github.com/EdwinBetanc0urt/adempiere-gRPC-Server/actions/runs/4226947914/jobs/7340921298
=> fix: CI/CD  with specific Gradle version.

src/main/java/org/spin/base/util/ReferenceUtil.java
fixes https://github.com/solop-develop/frontend-core/issues/865
=> feat: Add display column locator warehouse.

src/main/java/org/spin/grpc/service/MaterialManagementServiceImplementation.java, src/main/proto/material_management.proto
- Add list available warehouses.
Request:
```bash
curl --location --request POST 'http://0.0.0.0:8085/api/adempiere/material-management/list-available-warehouses?token=dba793a8-949c-4013-82b9-1005e1303213&language=es&search_value=hq' \
--data ''
```
Response:
```json
{
"code": 200,
"result": {
"record_count": 3,
"records": [
{
"id": 103,
"uuid": "36c24ddd-11ef-47ab-b554-f6966d0e5362",
"value": "HQ",
"name": "HQ Warehouse",
"is_in_transit": false
},
{
"id": 50000,
"uuid": "711f71f5-19b4-4f21-86a7-f5d8834ed9f3",
"value": "HQT",
"name": "HQ Transit",
"is_in_transit": true
},
{
"id": 1000000,
"uuid": "0035cc9c-68b2-48d5-8c3c-f93e9446675b",
"value": "10000000",
"name": "HQ Test",
"is_in_transit": false
}
]
}
}
``` …
=> feat: Warehouse Locator field services.

src/main/java/org/spin/base/util/ReferenceUtil.java, src/main/java/org/spin/grpc/service/DictionaryServiceImplementation.java
Add support zoom on custom field lookups.
- `Accouting Combinantion`.
- `Address Location`.
- `Attribute Set Instance`.
- `Warehouse Locator`
https://user-images.githubusercontent.com/20288327/221214651-2808822e-b36b-475f-a6aa-a9ac176303dd.mp4
fixes https://github.com/solop-develop/frontend-core/issues/870
=> feat: Add zoom custom lookups.

src/main/java/org/spin/grpc/service/MaterialManagementServiceImplementation.java, src/main/proto/material_management.proto
- Add support if field has dynamic validation.
fixes https://github.com/solop-develop/frontend-core/issues/867
fixes https://github.com/solop-develop/frontend-core/issues/872
fixes https://github.com/solop-develop/frontend-core/issues/864
=> feat: Add Dynamic validation on Warehouse Locator fields.

src/main/java/org/spin/grpc/service/MaterialManagementServiceImplementation.java
https://user-images.githubusercontent.com/20288327/221673387-84f8ffab-4d6b-4b4b-a3ca-029aeed50b37.mp4
https://user-images.githubusercontent.com/20288327/221673382-cd6b9b89-fa29-4548-ba07-ffe4239e1a66.mp4
=> feat: Warehouse locator client access.

src/main/java/org/spin/grpc/service/MaterialManagementServiceImplementation.java, src/main/proto/material_management.proto
Add search value on list attribute set instances
https://user-images.githubusercontent.com/20288327/221691882-dd7c4d30-b150-4970-a635-f9f4301135ef.mp4
=> feat: List attribute set instances with search value.

src/main/java/org/spin/grpc/service/BusinessDataServiceImplementation.java
https://user-images.githubusercontent.com/20288327/222617748-3d0b588c-148b-43ca-a023-f897b1650ed1.mp4
https://user-images.githubusercontent.com/20288327/222616811-4b243da9-4079-4ce8-8278-047a97094be7.mp4
Backend log
```log
===========> MPPMRP.set_Value: Qty - Class invalid: class java.lang.Integer, Should be class java.math.BigDecimal: 35 [47]
```
fixes https://github.com/solop-develop/frontend-core/issues/907
=> fix: Run Smart Browser process with selection.

src/main/java/org/spin/grpc/service/UserInterfaceServiceImplementation.java, src/main/proto/base_data_type.proto
https://user-images.githubusercontent.com/31936815/223167264-49256554-3a60-489d-8b4a-ba12bf40e94e.mp4
https://user-images.githubusercontent.com/20288327/224123384-5363868d-a0d3-4af9-b74b-bc81022434e2.mp4
fixes https://github.com/solop-develop/frontend-core/issues/911
=> fix: Zoom reference window.

build-docker/backend.env, build-docker/development.Dockerfile, build-docker/production-alpine.Dockerfile, build-docker/production.Dockerfile, resources/standalone.yaml, src/main/java/org/spin/base/util/Services.java, src/main/java/org/spin/grpc/service/TimeRecordServiceImplementation.java, src/main/java/org/spin/server/AllInOneServices.java, src/main/proto/time_record.proto
```bash
curl --location 'http://0.0.0.0:8085/api/adempiere/form/addons/time-record?token=1c7e7e6b-8608-4c23-9bf6-bc189315b3b0&language=es' \
--data '{
"name": "Test Garden Admin",
"description": "Test description",
"quantity": 12
}
'
```
Response
```json
{
"code": 200,
"result": {
"id": 1000000,
"uuid": "616d6e3b-0511-480a-a58f-6342110f7d99",
"resource": {
"id": 100,
"uuid": "29093f9a-676a-4f92-8786-3f347f58867c",
"resource_type": {
"id": 100,
"uuid": "1a82abae-9b35-45f2-b3f7-8f0ec99e2b75",
"value": "Consultant",
"name": "Consultant",
"unit_of_measure": {
"uuid": "a5aad752-fb40-11e8-a479-7a0060f0aa01",
"id": 101,
"code": "HR",
"symbol": "h  ",
"name": "Hora",
"starndard_precision": 2,
"costing_precision": 2 …
```
=> feat: Add time record.

src/main/java/org/spin/grpc/service/TimeRecordServiceImplementation.java, src/main/proto/time_record.proto
```bash
curl --location 'http://0.0.0.0:8085/api/adempiere/form/addons/time-record/projects?token=1c7e7e6b-8608-4c23-9bf6-bc189315b3b0&language=es'
```
```json
{
"code": 200,
"result": {
"records": [
{
"id": 100,
"uuid": "38fb2722-d2c1-4b0e-b32e-01b76ad1952a",
"value": "Standard",
"name": "Standard"
},
{
"id": 101,
"uuid": "3133fd78-8800-4b15-8401-b3686d434c46",
"value": "Landscape",
"name": "Landcape for New Complex"
}
]
}
}
```
```bash
curl --location 'http://0.0.0.0:8085/api/adempiere/form/addons/time-record/issues?token=1c7e7e6b-8608-4c23-9bf6-bc189315b3b0&language=es'
```
```json
{
"code": 200,
"result": {
"records": [
{
"id": 1000000,
"uuid": "83d443b5-2df1-4e99-933d-1639a2bbd837",
"document_no": …
```
=> feat: List issues and projects.

src/main/java/org/spin/authentication/AuthorizationServerInterceptor.java, src/main/java/org/spin/authentication/BearerToken.java, src/main/java/org/spin/base/util/ContextManager.java, src/main/java/org/spin/base/util/SessionManager.java, src/main/java/org/spin/grpc/service/AccessServiceImplementation.java
Validate bearer token with requests:
- change role.
- logout.
- session info.
- user info.
=> fix: Validate bearer token.

build.gradle, src/main/java/org/spin/grpc/service/FileManagementServiceImplementation.java
fixes https://github.com/solop-develop/frontend-core/issues/583
fixes https://github.com/solop-develop/frontend-core/issues/630
fixes https://github.com/solop-develop/frontend-core/issues/582
fixes https://github.com/solop-develop/frontend-core/issues/581
=> feat: Support attachment with JWT.

build-docker/backend.env, build-docker/development.Dockerfile, build-docker/docker-compose.yaml, build-docker/production-alpine.Dockerfile, build-docker/production.Dockerfile, resources/standalone.yaml, src/main/java/org/spin/authentication/AuthorizationServerInterceptor.java, src/main/java/org/spin/base/util/Services.java, src/main/java/org/spin/grpc/service/SecurityServiceImplementation.java, src/main/java/org/spin/server/AllInOneServices.java, src/main/proto/security.proto
Rename access for security due to a conflict with the web store proto
=> feat: Rename access to security

src/main/java/org/spin/grpc/service/SecurityServiceImplementation.java, src/main/proto/security.proto
Change session attribute (or global/accounting context), and reload bearer token.
Implement on:
- Change language.
- Change warehouse.
=> feat: Change session attibute service.

src/main/java/org/spin/base/util/SessionManager.java, src/main/java/org/spin/grpc/service/SecurityServiceImplementation.java, src/main/proto/security.proto
Change warehouse set correct warehouse on context.
=> fix: Set warehouse on session context.

README.es.md, README.md, build-docker/backend.env, build-docker/development.Dockerfile, build-docker/docker-compose.yaml, build-docker/production-alpine.Dockerfile, build-docker/production.Dockerfile, build-docker/start.sh, resources/standalone.yaml
Add default secret key on containers and standalone.yml file configuration.
=> feat: Add default secret key.

src/main/java/org/spin/base/util/RecordUtil.java, src/main/java/org/spin/grpc/service/BusinessDataServiceImplementation.java, src/main/java/org/spin/grpc/service/BusinessPartnerServiceImplementation.java, src/main/java/org/spin/grpc/service/CoreFunctionalityImplementation.java, src/main/java/org/spin/grpc/service/GeneralLedgerServiceImplementation.java, src/main/java/org/spin/grpc/service/InOutServiceImplementation.java, src/main/java/org/spin/grpc/service/InvoiceServiceImplementation.java, src/main/java/org/spin/grpc/service/LogsServiceImplementation.java, src/main/java/org/spin/grpc/service/OrderServiceImplementation.java, src/main/java/org/spin/grpc/service/PaymentPrintExportServiceImplementation.java, src/main/java/org/spin/grpc/service/PaymentServiceImplementation.java, src/main/java/org/spin/grpc/service/PayrollActionNoticeServiceImplementation.java, src/main/java/org/spin/grpc/service/PointOfSalesServiceImplementation.java, src/main/java/org/spin/grpc/service/ProductServiceImplementation.java, src/main/java/org/spin/grpc/service/TimeControlServiceImplementation.java, src/main/java/org/spin/grpc/service/UpdateImplementation.java, src/main/java/org/spin/grpc/service/UserInterfaceServiceImplementation.java, src/main/java/org/spin/grpc/service/WebStoreServiceImplementation.java, src/main/java/org/spin/grpc/service/WorkflowServiceImplementation.java
Change pagination of records.
https://user-images.githubusercontent.com/20288327/228625875-7601eeb1-17ef-4566-8081-9fa4353bd73d.mp4
fixes https://github.com/solop-develop/frontend-core/issues/950
=> fix: Change pagination.

build-docker/backend.env, build-docker/development.Dockerfile, build-docker/production-alpine.Dockerfile, build-docker/production.Dockerfile, build-docker/stack.yml, resources/standalone.yaml, src/main/java/org/spin/base/util/Services.java, src/main/java/org/spin/grpc/service/ExpressShipmentServiceImplementation.java, src/main/java/org/spin/server/AllInOneServices.java, src/main/proto/express_shipment.proto
- List Sales Orders.
- List Products.
- Delete Shipment.
- Delete Shipment Line.
https://user-images.githubusercontent.com/20288327/228974296-f2a35e83-c4d2-4325-9806-08acb78d2622.mp4
=> feat: Express Shipment form.

docker-compose/docker-compose.yml
=> Add compose file changes for image

.settings/org.eclipse.buildship.core.prefs, docker/Dockerfile
Only for test is create a default private key on image, this will be remove ASAP
=> Add a default private key NOTE: ¡¡¡¡ONLY FOR TEST!!!!

src/main/java/org/spin/grpc/service/ExpressShipmentServiceImplementation.java
Add support to services:
- Create shipment.
- Process Shipment.
- Create shipment line with order line.
- Update shipment line.
- Delete shipment line.
- List shipment lines.
=> feat: Express Shipment Services.

.github/workflows/publish.yml
Current tag generated:
- solopcloud/adempiere-backend:alpine
- solopcloud/adempiere-backend:alpine-1.8.1
New tag generated:
- solopcloud/adempiere-backend:1.8.1
=> feat: CD docker image.

.github/workflows/ci.yml, .github/workflows/publish.yml
=> Fix deploy token

docker/Dockerfile
=> Fixed error with docker env values

src/main/java/org/spin/grpc/service/ExpressShipmentServiceImplementation.java
- Create Shipment.
- Create Shipment Line.
=> fix: Express Shipment services.

src/main/java/org/spin/grpc/service/ExpressReceiptServiceImplementation.java, src/main/java/org/spin/grpc/service/ExpressShipmentServiceImplementation.java, src/main/proto/express_receipt.proto, src/main/proto/express_shipment.proto
- Add list bussiness partners.
- Add business parnert filter on list orders.
=> feat: Shiment/Receipt add Business Partner filter.

build.gradle, src/main/java/org/spin/grpc/service/PointOfSalesServiceImplementation.java, src/main/java/org/spin/pos/util/POSConvertUtil.java, src/main/proto/point_of_sales.proto
=> feat: POS Add command shortcuts.

src/main/java/org/spin/grpc/service/PointOfSalesServiceImplementation.java
`isPOSManager` on `AD_User` table is deprecated. Replaced by `IsAllowsPOSManager` on `C_POSSellerAllocation` table
=> feat: Change IsPOSManager to IsAllowsPOSManager.

.github/workflows/publish.yml, docker/Dockerfile.alpine
Add build image to alpine support
=> Add alpine support

.github/workflows/publish.yml, docker/alpine.Dockerfile, docker/focal.Dockerfile
Improved image downloading using the cache with the layer to add operating system dependencies.
Remove duplicate environment variable from TZ.
Rename the Dockerfile files to slim.Dockerfile, and Dockerfile.alpine to alpine.Dockerfile to keep the file extension correct.
=>  feat: Change layers of Dockerfile. 

src/main/java/org/spin/grpc/service/ExpressShipmentServiceImplementation.java
- Business Partner reutrn name on value field.
- List products as summary.
- Create shipment line with shipment is processed.
- Update shipment line return empty builder.
fixes https://github.com/solop-develop/frontend-core/issues/958
=> fix: Express shipment validations.

src/main/java/org/spin/grpc/service/ExpressReceiptServiceImplementation.java
- Business Partner reutrn name on value field.
- List products as summary.
- Create receipt line with receipt is processed.
- Update receipt line return empty builder.
fixes https://github.com/solop-develop/frontend-core/issues/960
=> fix: Express receipt validations.

README.es.md, README.md, src/main/java/org/spin/grpc/service/PaymentAllocationServiceImplementation.java, src/main/proto/payment_allocation.proto
- Convert Business Partner.
- Convert Organization.
- Convert Transaction Type.
- Convert Currency.
- Convert Charge.
=> feat: Payment allocation convert builders.

src/main/java/org/spin/base/util/ValueUtil.java, src/main/java/org/spin/dashboarding/DashboardingConvertUtil.java, src/main/java/org/spin/grpc/service/DashboardingServiceImplementation.java, src/main/proto/dashboarding.proto
```bash
curl --location 'http://localhost:8085/api/adempiere/dashboard/window/exists-charts?ts=1681759182029&window_id=100&tab_id=100' \
--header 'Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiIxMDAwODg5IiwiQURfQ2xpZW50X0lEIjoxMSwiQURfT3JnX0lEIjo1MDAwNiwiQURfUm9sZV9JRCI6MTAyLCJBRF9Vc2VyX0lEIjoxMDEsIk1fV2FyZWhvdXNlX0lEIjo1MDAwNiwiQURfTGFuZ3VhZ2UiOiJlc19NWCIsImlhdCI6MTY4MTc1NjU1OSwiZXhwIjoxNjgxODQyOTU5fQ.NuP5FhAQlouOxZmm6CMjuvZL6Wt9mWX1ClZW9OdykIM'
```
```json
{
"code": 200,
"result": 4
}
```
```bash
curl --location 'http://localhost:8085/api/adempiere/dashboard/window/charts?id=102&page_size=15&language=es&ts=1681759182029&window_id=0&tab_id=0' \
--header 'Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiIxMDAwODg5IiwiQURfQ2xpZW50X0lEIjoxMSwiQURfT3JnX0lEIjo1MDAwNiwiQURfUm9sZV9JRC …
```
=> feat: Window Charts.

.github/workflows/ci.yml, .github/workflows/publish.yml
When generate release the publish action fail on Publish to Maven Repository step.
=> fix: Release to publish maven without secrets.

src/main/java/org/spin/grpc/service/DashboardingServiceImplementation.java
Count records always is zero, and add support pagination.
```bash
http://localhost:8085/api/adempiere/dashboard/window/charts?id=50099&tab_id=53256&window_id=53089&language=es&ts=1682003629532
```
```json
{
"code": 200,
"result": {
"records": [
....
]
}
}
```
```json
{
"code": 200,
"result": {
"record_count": 4,
"records": [
....
]
}
}
```
=> fix: Window charts count list.

src/main/java/org/spin/dashboarding/DashboardingConvertUtil.java, src/main/java/org/spin/grpc/service/DashboardingServiceImplementation.java
Filter window charts allocated by role, window, and tab.
And return `context_column_names` and `transformation_script`
http://localhost:8085/api/adempiere/dashboard/window/charts?id=50004&tab_id=180&window_id=140&language=es&ts=1682102542010
```json
{
"code": 200,
"result": {
"records": [
{
"id": 1000000,
"uuid": "53f37921-ce8f-4b2c-b43b-976547dc5d59",
"name": "Ventas por Grupo de Producto",
"sequence": 1000002,
"is_collapsible": true,
"is_open_by_default": true,
"dashboard_type": "chart",
"chart_type": "AC",
"context_column_names": [
"M_Product_Group_ID"
],
"transformation_script": "console.log('hola mundo');"
}
]
}
}
```
=> feat: Window Chart filter by role, window and tab.

src/main/java/org/spin/dashboarding/DashboardingConvertUtil.java, src/main/java/org/spin/grpc/service/DashboardingServiceImplementation.java, src/main/proto/dashboarding.proto
- Change `WindowChart` to `WindowDashboard`
- Change `GetChart` to `GetMetrics`.
=> feat: Change chart to dashboard.

src/main/java/org/spin/dashboarding/DashboardingConvertUtil.java, src/main/java/org/spin/grpc/service/DashboardingServiceImplementation.java
```bash
curl --location 'http://localhost:8085/api/adempiere/dashboard/window/metrics?page_size=15&language=es&ts=1681759182029' \
--header 'Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiIxMDAwOTMxIiwiQURfQ2xpZW50X0lEIjoxMSwiQURfT3JnX0lEIjo1MDAwNiwiQURfUm9sZV9JRCI6MTAyLCJBRF9Vc2VyX0lEIjoxMDEsIk1fV2FyZWhvdXNlX0lEIjo1MDAwNiwiQURfTGFuZ3VhZ2UiOiJlc19NWCIsImlhdCI6MTY4MjM0NzA5NiwiZXhwIjoxNjgyNDMzNDk2fQ.AuycAARoOqWER8TRNFy4qA3sM-LIhOnMBtBE0uiudVU' \
--data '{
"id": 1000002,
"table_name": "M_Product",
"record_id": 0,
"record_uuid": "",
"context_attributes": [{
"key": "M_Product_Group_ID",
"value": 1000004
}]
}
'
```
```json
{
"code": 200,
"result": {
"id": 0,
"uuid": "",
"name": "",
"x_axis_label": "",
"y_axis_label": "", …
```
=> feat: Window Chart filter by context.

src/main/java/org/spin/grpc/service/PaymentAllocationServiceImplementation.java, src/main/proto/payment_allocation.proto
- List Payments table data.
- List Invoices table data.
https://user-images.githubusercontent.com/20288327/234636580-d66cd948-c373-4964-87f8-f314c28ba4fa.mp4
fixes https://github.com/solop-develop/frontend-core/issues/965
=> feat: Payment Allocation list table data.

src/main/java/org/spin/grpc/service/BankStatementMatchServiceImplementation.java
```
http://localhost:8085/api/adempiere/form/addons/bank-statement-match/payments?bank_account_id=100
```
```json
{
"code": 200,
"result": {
"record_count": 4,
"records": [
{
"id": 50008,
"uuid": "4a953c7e-414a-47ac-8d50-3105a06cb32e",
"transaction_date": 1691640000000,
"is_receipt": true,
"document_no": "400002",
"business_partner": {
"id": 113,
"uuid": "d430bdde-e5e4-476b-8dc9-4b0b5d5b02cc",
"value": "GardenAdmin",
"tax_id": "",
"name": "GardenAdmin BP",
"description": ""
},
"tender_type": {
"id": 401,
"uuid": "a45605fc-fb40-11e8-a479-7a0060f0aa01",
"value": "K",
"name": "Check",
"description": ""
},
"currency": {
"id": 50003,
"uuid": "87f26860-fcc8-4c4f-aca0-e35218543097",
"iso_code": "VED",
"description": "Bolivar Digital"
},
"amount": 1000
}, …
```
=> feat: Bank Statement Match list payments.

src/main/java/org/spin/grpc/service/SecurityServiceImplementation.java
List roles with OrgAccess or UserAccess with Organizations isSummary = true.
=> fix: List roles with org only summary.

src/main/java/org/spin/grpc/service/CoreFunctionalityImplementation.java, src/main/java/org/spin/grpc/service/SecurityServiceImplementation.java
When Role isAccessAllOrg true check, list all organizations includes isSummary true check (as example `Stores` organization).
fixes https://github.com/solop-develop/frontend-core/issues/985
=> fix: Role isAccessAllOrg=Y List Organizations with isSummary=Y.

src/main/java/org/spin/dashboarding/DashboardingConvertUtil.java, src/main/java/org/spin/grpc/service/DashboardingServiceImplementation.java, src/main/proto/dashboarding.proto
Add window chart parameters to filter on Window Metrics.
http://localhost:8085/api/adempiere/dashboard/window/dashboards?page_size=15&ts=1681759182029&window_id=140&tab_id=100
```json
{
"code": 200,
"result": {
"records": [
{
"id": 1000004,
"uuid": "9149ada4-a42b-403e-af88-2f513b79ae9a",
"name": "Ventas por Grupo de Producto",
"sequence": 30,
"is_collapsible": true,
"is_open_by_default": true,
"dashboard_type": "chart",
"chart_type": "AC",
"context_column_names": [],
"transformation_script": "// Chart Line Type\nconst xAxisValues = []\nlet seriesToShow = []\nlet legendToShow = []\nconst allData = data.series\nconst dataSet = data.series.map(b => b.data_set)\nconst allDataValue = dataSet.map(currentSet => {\n  return …
```
=> feat: Window Chart Parameters as filters.

src/main/java/org/spin/grpc/service/CoreFunctionalityImplementation.java
List only warehouses `IsInTransit = 'N'` to login.
fixes https://github.com/solop-develop/frontend-core/issues/990
=> fix: Login with transit warehouse.

build.gradle, src/main/java/org/spin/dashboarding/DashboardingConvertUtil.java, src/main/java/org/spin/grpc/service/DashboardingServiceImplementation.java, src/main/proto/dashboarding.proto
Currently a Map of filters is sent with String, BigDecimal, Integer, Boolean, Timestamp values associated to the ColumnSQL of the parameter as key of the Map.
However, when you need to use the `BETWEEN ? AND ?` or the `IN(?, ?, ?, ?)` operator is not possible since it only allows a single associated value.
To solve this, support is added in the Filter Map so that the value can read a List of Objects, and thus add in the same order of that list the multiple values for the query.
Depends on https://github.com/adempiere/adempiere-dashboard-improvements/pull/4
=> feat: Window Dashboard filters with multiple values.

src/main/java/org/spin/dashboarding/DashboardingConvertUtil.java, src/main/java/org/spin/grpc/service/DashboardingServiceImplementation.java
=> fix: Favorites empty list.

src/main/java/org/spin/grpc/service/DictionaryServiceImplementation.java
Add parent tab uuid on tabs list.
related issue https://github.com/solop-develop/frontend-core/issues/613
=> feat: Add parent tab on tabs list.

docker-compose/.env, docker/alpine.Dockerfile, docker/focal.Dockerfile, resources/standalone.yaml, src/main/java/org/spin/base/util/Services.java, src/main/java/org/spin/form/match_po_receipt_invoice/Util.java, src/main/java/org/spin/grpc/service/MatchPOReceiptInvoiceServiceImplementation.java, src/main/java/org/spin/server/AllInOneServices.java, src/main/proto/match_po_receipt_invoice.proto
related issue https://github.com/solop-develop/frontend-core/issues/1007
=> feat: Add initial services to Match PO-Receipt-Invoice form.

src/main/java/org/spin/grpc/service/IssueManagementServiceImplementation.java
This changes only remove unnecessary spaces on `IssueManagementServiceImplementation` class.
=> feat: Remove unnecessary spaces on Issue Management.

src/main/java/org/spin/form/match_po_receipt_invoice/Util.java, src/main/java/org/spin/grpc/service/MatchPOReceiptInvoiceServiceImplementation.java
Add mached quantity as assigned quantity.
=> feat: Add matched quantity as assigned.

src/main/java/org/spin/grpc/service/PaymentPrintExportServiceImplementation.java, src/main/proto/payment_print_export.proto
- Create EFT.
- Confirm Print.
- Export.
=> feat: Add create eft, export, confirm print services to Pay/Print/Export form.

build.gradle, src/main/java/org/spin/base/util/FileUtil.java, src/main/java/org/spin/grpc/service/PaymentPrintExportServiceImplementation.java
- Generate Export TXT file.
- Generate Print PDF file.
- Generate Remittance PDf file
=> feat: Payment Print/Export form generated PDF/TXT files.

src/main/java/org/spin/grpc/service/PaymentPrintExportServiceImplementation.java, src/main/proto/payment_print_export.proto
- Validate and get List Payment Selections checks with same payment rule.
- Validate print format to print by payment rule.
fixes https://github.com/solop-develop/frontend-core/issues/662
=> feat: Validate payment rules to payment selection checks.

build.gradle
fix: Get correct data source and set where. https://github.com/adempiere/adempiere-dashboard-improvements/pull/6
add: Business Processors to task's and schedulers.
=> feat: Update dependencies.

src/main/java/org/spin/grpc/service/BankStatementMatchServiceImplementation.java
=> fix: Validate bank account on Bank Statement Match form.

src/main/java/org/spin/grpc/service/PaymentAllocationServiceImplementation.java
if the date of the request is empty take the longest date of any of the selections.
=> fix: Get date to Payment Allocation form.

src/main/java/org/spin/grpc/service/PaymentAllocationServiceImplementation.java, src/main/proto/payment_allocation.proto
Process or save data on Payment Allocation form.
fixes https://github.com/solop-develop/frontend-core/issues/965
=> feat: Process on Payment allocation form.

src/main/java/org/spin/base/util/DictionaryUtil.java
```bash
curl --location 'http://localhost:8085/api/adempiere/user-interface/window/entities?page_token=1&page_size=15&ts=1685562330824' \
--header 'Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiIxMDAxMjg3IiwiQURfQ2xpZW50X0lEIjowLCJBRF9PcmdfSUQiOjAsIkFEX1JvbGVfSUQiOjAsIkFEX1VzZXJfSUQiOjEwMCwiTV9XYXJlaG91c2VfSUQiOjAsIkFEX0xhbmd1YWdlIjoiZW5fVVMiLCJpYXQiOjE2ODU1NjIyMjksImV4cCI6MTY4NTY0ODYyOX0.CojTX_3MGr2igJ_cuXPEl8XpDPk9stF6P-1T8OftGvA' \
--data '{
"window_uuid": "a5214370-fb40-11e8-a479-7a0060f0aa01",
"tab_uuid": "a4a0e4a0-fb40-11e8-a479-7a0060f0aa01",
"context_attributes": [],
"search_value": "",
"reference_uuid": "",
"filters": [],
"columns": []
}'
```
```json
{
"code": 200,
"result": {
"records": …
```
=> fix: Get list entities with column sql as lookup reference.

src/main/java/org/spin/grpc/service/IssueManagementServiceImplementation.java
* Corrected if the Next Action Date is greater than the system, it does not take into account the requests.
* Added sorted by Next Action Date.
fixes https://github.com/solop-develop/frontend-core/issues/1018
=> fix: Issues filter greater than current date.

src/main/java/org/spin/base/util/ContextManager.java, src/main/java/org/spin/grpc/service/UserInterfaceServiceImplementation.java
```bash
curl --location 'http://localhost:8085/api/adempiere/user-interface/smart-browser/browser-items?page_token=1&page_size=15&ts=1685719543625' \
--header 'Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiIxMDAxMzA5IiwiQURfQ2xpZW50X0lEIjoxMSwiQURfT3JnX0lEIjoxMDAwMDA1LCJBRF9Sb2xlX0lEIjoxMDIsIkFEX1VzZXJfSUQiOjEwMSwiTV9XYXJlaG91c2VfSUQiOjAsIkFEX0xhbmd1YWdlIjoiZW5fVVMiLCJpYXQiOjE2ODU2NzQ4ODQsImV4cCI6MTY4NTc2MTI4NH0.ekXG86oRC4PvQY7MCowNxQLSt8yOtNz-hFnesSeuUY8' \
--data '{
"uuid": "8aaef794-fb40-11e8-a479-7a0060f0aa01",
"filters": [
{
"column_name": "PS_C_Currency_ID",
"value": 100
},
{
"column_name": "INV_MatchRequirement",
"value": "N"
},
{
"column_name": "INV_DaysDue",
"value": -9999999
},
{
"column_name": "INV_DaysDue_To",
"value": 9999999 …
```
=> fix: SB Create Invoice From.

src/main/java/org/spin/base/util/DictionaryUtil.java, src/main/java/org/spin/grpc/service/UserInterfaceServiceImplementation.java
https://github.com/solop-develop/adempiere-grpc-server/assets/20288327/21660dc0-d5d3-4e73-9a4f-09f08658c518
fixes https://github.com/solop-develop/frontend-core/issues/1025
=> fix: List entities on `Employee (All)` window.

src/main/java/org/spin/base/util/RecordUtil.java
https://github.com/solop-develop/adempiere-grpc-server/assets/20288327/f56557d1-ef2e-407c-a404-a1eea810d619
fixes https://github.com/solop-develop/frontend-core/issues/692
=> fix: List Payment Selection Lines window.

src/main/java/org/spin/base/dictionary/DictionaryConvertUtil.java, src/main/java/org/spin/base/util/DictionaryUtil.java, src/main/java/org/spin/dashboarding/DashboardingConvertUtil.java, src/main/java/org/spin/grpc/service/DictionaryServiceImplementation.java, src/main/proto/dashboarding.proto
Add `Reference` definition on `WindowDashboardParameter`.
fixes https://github.com/solop-develop/frontend-core/issues/1029
=> fix: Window chart parameter with lookup list.

src/main/java/org/spin/base/util/DictionaryUtil.java
1. Login with `System` role.
2. Open `System Translation Check` window.
3. Select `Element Translation` tab.
```bash
curl --location 'http://localhost:8085/api/adempiere/user-interface/window/entities?page_token=1&page_size=15&ts=1686088732039' \
--header 'Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiIxMDAxMzQwIiwiQURfQ2xpZW50X0lEIjoxMSwiQURfT3JnX0lEIjoxMDAwMDA1LCJBRF9Sb2xlX0lEIjoxMDIsIkFEX1VzZXJfSUQiOjEwMSwiTV9XYXJlaG91c2VfSUQiOjAsIkFEX0xhbmd1YWdlIjoiZW5fVVMiLCJpYXQiOjE2ODYwNjY0NjAsImV4cCI6MTY4NjE1Mjg2MH0.0yGr_X0QympIV_5MJdlhA1iGxfnknwKeuZGLyxVxpBQ' \
--data '{
"columns": [],
"context_attributes": [
{
"key": "AD_Language",
"value": "es_MX"
}
],
"reference_uuid": "",
"search_value": "",
"tab_uuid": "a49ff572-fb40-11e8-a479-7a0060f0aa01", …
```
=> fix: Window with link column name.

src/main/java/org/spin/grpc/service/SecurityServiceImplementation.java
1. Login with admin role.
2. Set any organization and warehouse.
3. Change language.
The warehouse on global context is set to `0`.
fixes https://github.com/solop-develop/adempiere-grpc-server/issues/324
=> fix: Change warehouse on global context.

.vscode/settings.json, build.gradle
- Update `com.google.protobuf` plugin.
- Update `io.grpc:grpc-alts`.
- Update `io.grpc:grpc-netty-shaded`
- Update `io.grpc:grpc-protobuf`
- Update `io.grpc:grpc-stub`.
- Update `io.grpc:grpc-netty`.
=> feat: Update gRPC libraries.

src/main/java/org/spin/base/dictionary/DictionaryUtil.java, src/main/java/org/spin/grpc/service/BusinessDataServiceImplementation.java, src/main/java/org/spin/grpc/service/DictionaryServiceImplementation.java, src/main/java/org/spin/grpc/service/UserInterfaceServiceImplementation.java
Move get Reference ID from `org.spin.grpc.service.DicionaryServiceImplementation` to `org.spin.base.dictionary.DictionaryUtil`.
=> feat: Move get Reference ID.

src/main/java/org/spin/base/dictionary/DictionaryUtil.java, src/main/java/org/spin/grpc/service/BusinessDataServiceImplementation.java, src/main/java/org/spin/grpc/service/DictionaryServiceImplementation.java, src/main/java/org/spin/grpc/service/WorkflowServiceImplementation.java
Move `addToRecentItem` method from `org.spin.grpc.service.DicionaryServiceImplementation` and `org.spin.grpc.service.BusinessDataServiceImplementation` to `org.spin.base.dictionary.DictionaryUtil`.
=> feat: Move `addToRecentItem` method to `DictionaryUtil` class.

build.gradle
```log
ERROR StatusLogger Log4j2 could not find a logging implementation. Please add log4j-core to the classpath. Using SimpleLogger to log to the console...
Exception in thread "main" java.lang.IncompatibleClassChangeError: Method 'io.vavr.collection.List io.vavr.collection.List.of(java.lang.Object[])' must be Methodref constant
at org.compiere.model.POInfo.loadInfo(POInfo.java:187)
at org.compiere.model.POInfo.<init>(POInfo.java:139)
at org.compiere.model.POInfo.getPOInfo(POInfo.java:92)
at org.adempiere.core.domains.models.X_AD_Table.initPO(X_AD_Table.java:82)
at org.compiere.model.PO.<init>(PO.java:226)
at org.compiere.model.PO.<init>(PO.java:186)
at org.adempiere.core.domains.models.X_AD_Table.<init>(X_AD_Table.java:43)
at org.compiere.model.MTable.<init>(MTable.java:419)
at …
```
=> fix: Start server with `io.vavr.collection.List`.

src/main/java/org/spin/base/dictionary/DictionaryUtil.java, src/main/java/org/spin/base/ui/UserInterfaceConvertUtil.java, src/main/java/org/spin/grpc/service/UserInterfaceServiceImplementation.java, src/main/proto/business.proto
- Add where clause on List Tree Nodes.
- Add tree type on List Tree Nodes.
```json
{
"code": 200,
"result": {
"record_count": 5,
"records": [
...
]
"tree_type": {
"id": 284,
"uuid": "a456b2d6-fb40-11e8-a479-7a0060f0aa01",
"value": "OO",
"name": "Organization",
"description": ""
}
}
}
```
=> feat: Add tab where clause on `List Tree`.

src/main/java/org/spin/base/workflow/WorkflowUtil.java, src/main/java/org/spin/grpc/service/WorkflowServiceImplementation.java
when `runDocumentAction` service is called, the workflows are not being generated.
https://github.com/solop-develop/adempiere-grpc-server/assets/20288327/ce5629f5-5dc5-4df4-be05-dbe7b392e9ee
fixes https://github.com/solop-develop/adempiere-grpc-server/issues/338
=> fix: `Run Document Action` start Workflow nodes.

src/main/java/org/spin/base/dictionary/SearchInfoFields.java, src/main/java/org/spin/grpc/logic/DictionaryServiceLogic.java, src/main/java/org/spin/grpc/service/DictionaryServiceImplementation.java, src/main/proto/dictionary.proto
With a single service to obtain the fields of both the search criteria and the table to fields search form.
```bash
curl --location 'http://localhost:8085/api/adempiere/dictionary/search-info/fields?table_name=C_Currency&ts=1686688301758' \
--header 'Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiIxMDAxMzg3IiwiQURfQ2xpZW50X0lEIjoxMSwiQURfT3JnX0lEIjoxMDAwMDA1LCJBRF9Sb2xlX0lEIjoxMDIsIkFEX1VzZXJfSUQiOjEwMSwiTV9XYXJlaG91c2VfSUQiOjAsIkFEX0xhbmd1YWdlIjoiZW5fVVMiLCJpYXQiOjE2ODY3NTUzMjEsImV4cCI6MTY4Njg0MTcyMX0.8KD-CS_-yLxYGadUX-1VMH3fnBc128XE5EtK4Md3EAQ'
```
```json
{
"code": 200,
"result": {
"record_count": 13,
"records": [
{
"id": 403,
"uuid": "8d38edee-fb40-11e8-a479-7a0060f0aa01",
"name": "Currency",
"description": "The Currency for this record",
"help": …
```
=> feat: List Search Info fields.

src/main/java/org/spin/base/util/OperatorUtil.java, src/main/java/org/spin/base/util/QueryUtil.java, src/main/java/org/spin/base/util/RecordUtil.java, src/main/java/org/spin/base/util/ValueUtil.java, src/main/java/org/spin/grpc/service/UserInterfaceServiceImplementation.java, src/main/proto/base_data_type.proto
fixes https://github.com/solop-develop/frontend-core/issues/1066
=> feat: Add operators restriction to `BrowseItems`.

src/main/java/org/spin/base/db/CountUtil.java, src/main/java/org/spin/base/db/FromUtil.java, src/main/java/org/spin/base/util/RecordUtil.java, src/main/java/org/spin/grpc/service/BusinessDataServiceImplementation.java, src/main/java/org/spin/grpc/service/BusinessPartnerServiceImplementation.java, src/main/java/org/spin/grpc/service/GeneralLedgerServiceImplementation.java, src/main/java/org/spin/grpc/service/InOutServiceImplementation.java, src/main/java/org/spin/grpc/service/InvoiceServiceImplementation.java, src/main/java/org/spin/grpc/service/MaterialManagementServiceImplementation.java, src/main/java/org/spin/grpc/service/OrderServiceImplementation.java, src/main/java/org/spin/grpc/service/PaymentServiceImplementation.java, src/main/java/org/spin/grpc/service/PayrollActionNoticeServiceImplementation.java, src/main/java/org/spin/grpc/service/PointOfSalesServiceImplementation.java, src/main/java/org/spin/grpc/service/ProductServiceImplementation.java, src/main/java/org/spin/grpc/service/UserInterfaceServiceImplementation.java
Move `countRecord` method, from `src/main/java/org/spin/base/util/RecordUtil.java` class to `src/main/java/org/spin/base/db/CountUtil.java` class.
=> feat: Move `countRecord` method to `CountUtil`.

src/main/java/org/spin/base/db/ParameterUtil.java, src/main/java/org/spin/base/util/RecordUtil.java, src/main/java/org/spin/base/util/ValueUtil.java, src/main/java/org/spin/grpc/service/BusinessDataServiceImplementation.java, src/main/java/org/spin/grpc/service/PayrollActionNoticeServiceImplementation.java, src/main/java/org/spin/grpc/service/UserInterfaceServiceImplementation.java
Move `setParameterFromObject` and `setParametersFromObjectsList` from `src/main/java/org/spin/base/util/ValueUtil.java` class to `src/main/java/org/spin/base/db/ParameterUtil.java` class
=> feat: Move `setParameter` method to `ParameterUtil` class.

src/main/java/org/spin/base/db/OrderByUtil.java, src/main/java/org/spin/base/dictionary/WindowUtil.java, src/main/java/org/spin/base/util/DictionaryUtil.java, src/main/java/org/spin/grpc/service/DictionaryServiceImplementation.java
Move window, tab, and field helper methods to `src/main/java/org/spin/base/dictionary/WindowUtil.java`
=> feat: Move window, tab, field methods to `WindowUtil` class.

src/main/java/org/spin/base/db/QueryUtil.java
=> fix: Displayed Value on `DocAction` when is Button display type.

src/main/java/org/spin/base/db/CountUtil.java, src/main/java/org/spin/base/db/FromUtil.java, src/main/java/org/spin/base/db/LimitUtil.java, src/main/java/org/spin/base/db/OrderByUtil.java, src/main/java/org/spin/base/db/QueryUtil.java, src/main/java/org/spin/base/db/WhereClauseUtil.java, src/main/java/org/spin/base/util/ReferenceUtil.java
If table `C_Invoice`, when get list entities, add on attributes `DisplayColumn_C_Invoice_ID`.
=> feat: Add support to display column on ID references.

src/main/java/org/spin/grpc/service/GeneralLedgerServiceImplementation.java
Implementation of method `MAcctSchemaElement.getColumnName` in your site
=> feat: Remove duplicated method `getColumnNameFromElementType`.

src/main/java/org/spin/base/util/GeneralLedgerConvertUtil.java, src/main/java/org/spin/base/util/LookupUtil.java, src/main/java/org/spin/grpc/logic/GeneralLedgerServiceLogic.java, src/main/java/org/spin/grpc/service/GeneralLedgerServiceImplementation.java, src/main/proto/general_ledger.proto
Add services:
- `ListAccoutingSchemas`.
- `ListPostingTypes`.
- `ListAccoutingDocuments`.
- `ListOrganizations`.
fixes https://github.com/solop-develop/frontend-core/issues/1114
=> feat: Accouting viewer filters.

src/main/java/org/spin/grpc/service/DictionaryServiceImplementation.java
fixes https://github.com/solop-develop/adempiere-grpc-server/issues/363
=> fix: Role displayed accouting tab without access.

README.es.md, README.md, docker-compose/.env, docker/alpine.Dockerfile, docker/focal.Dockerfile, resources/standalone.yaml, src/main/java/org/spin/base/util/Services.java, src/main/java/org/spin/form/import_file_loader/ImportFileLoaderConvertUtil.java, src/main/java/org/spin/grpc/logic/ImportFileLoaderServiceLogic.java, src/main/java/org/spin/grpc/service/ImportFileLoaderServiceImplementation.java, src/main/proto/import_file_loader.proto
Support to services 
- ListCharsets
- ListImportFormats
- GetImportFromat
=> feat: Add `Import File Loader` form.

src/main/java/org/spin/grpc/service/ImportFileLoaderServiceImplementation.java, src/main/java/org/spin/server/AllInOneServices.java, src/main/proto/import_file_loader.proto
Add services definition to:
- Download file.
- Save records on import tables.
=> feat: Save records `Import File Loader` form.

src/main/java/org/spin/grpc/service/FileManagementServiceImplementation.java
https://github.com/solop-develop/adempiere-grpc-server/assets/20288327/16af5e81-3600-4f08-ac9a-4de6e5572a50
```json
{
"code": 200,
"result": {
"wrappers_": null,
"arrayIndexOffset_": -1,
"array": [],
"pivot_": 1.7976931348623157e+308,
"convertedPrimitiveFields_": {}
}
}
```
https://github.com/solop-develop/adempiere-grpc-server/assets/20288327/27ba4510-b4ff-4014-9799-42417e796219
```json
{
"code": 200,
"result": {
"resource_uuid": "e49600f2-1e3e-4a62-9ce7-8a68bf2bdd2a",
"file_name": "e49600f2-1e3e-4a62-9ce7-8a68bf2bdd2a-AccountingUS.csv",
"file_size": 354,
"text_msg": "",
"content_type": "text/csv"
}
}
```
=> feat: Attachment Upload file get resource reference.

src/main/java/org/spin/form/import_file_loader/ImportFileLoaderConvertUtil.java, src/main/java/org/spin/grpc/logic/ImportFileLoaderServiceLogic.java, src/main/java/org/spin/grpc/service/ImportFileLoaderServiceImplementation.java, src/main/proto/import_file_loader.proto
Delete services:
- LoadImportFile
- GetResource
Add serivces:
- ListImportProcesses
- ListImportTables
- ListClientImportFormats
=> feat: Import file loader form add services.

src/main/java/org/spin/grpc/service/FileManagementServiceImplementation.java, src/main/proto/file_management.proto
Add identifier to `Attachment` and to `ResourceReference`, and image uuid to `GetResourceReferenceRequest`. And reindex filed on proto file.
=> feat: Add ID to `Attachment` and `ResourceReference`.

src/main/java/org/spin/grpc/service/FileManagementServiceImplementation.java, src/main/proto/file_management.proto
Add services:
- Add attachment text message.
- Add attachment reference text message and description
=> feat: Attachment set description and text message.

src/main/java/org/spin/form/import_file_loader/ImportFileLoaderServiceLogic.java, src/main/java/org/spin/grpc/service/BusinessDataServiceImplementation.java, src/main/proto/import_file_loader.proto
- Add process before save records.
- Add `ProcessLog` on `SaveRecordsResponse`.
=> feat: `Import File Loader` form save records add process.

src/main/java/org/spin/grpc/service/WorkflowServiceImplementation.java
https://github.com/solop-develop/adempiere-grpc-server/assets/20288327/a0583954-d838-4334-9ea0-0e51a678d101
=> fix: Add transaction name on Workflow `runDocumentAtion`.

src/main/java/org/spin/grpc/service/UserInterfaceServiceImplementation.java
```bash
curl --location 'http://localhost:8085/api/adempiere/user-interface/smart-browser/browser-items?page_token=1&page_size=15&ts=1689780884975' \
--header 'Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiIxMDAxMTE5IiwiQURfQ2xpZW50X0lEIjoxMSwiQURfT3JnX0lEIjo1MDAwNiwiQURfUm9sZV9JRCI6MTAyLCJBRF9Vc2VyX0lEIjoxMDEsIk1fV2FyZWhvdXNlX0lEIjo1MDAwNiwiQURfTGFuZ3VhZ2UiOiJlc19NWCIsImlhdCI6MTY4OTc4MDQzNSwiZXhwIjoxNjg5ODY2ODM1fQ.usMrGc-6JA8amqMB04cEMCzP5KmnzZpbgJQNE_TYt2g' \
--data '{
"uuid": "8aaeeea2-fb40-11e8-a479-7a0060f0aa01",
"filters": [
{
"column_name": "CF_CreateFromType",
"value": "O",
"operator": "EQUAL"
},
{
"column_name": "CF_IsSameWarehouse",
"value": false,
"operator": "EQUAL"
},
{
"column_name": "CF_C_Order_ID",
"value": 1000046, …
```
=> fix: Smart Browser without records.

src/main/java/org/spin/grpc/service/FileManagementServiceImplementation.java, src/main/proto/file_management.proto
On `ResourceReference` structure add:
- Name.
- Created.
- Updated.
=> feat: `Created` and `Updated` on resource reference.

README.es.md, README.md, docker/alpine.Dockerfile, docker/env.yaml, docker/focal.Dockerfile, docker/start.sh, resources/standalone.yaml, src/main/java/org/spin/base/setup/Server.java
Add environment to enable all services and overwrite serives list.
The key is `IS_ENABLED_ALL_SERVICES` and default value is `true`.
=> feat: Add flag to enabled all services.

src/main/java/org/spin/grpc/service/BusinessDataServiceImplementation.java
```bash
curl --location 'http://0.0.0.0:8085/api/adempiere/common/api/process?ts=1690139768369' \
--header 'Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiIxMDAxMTM1IiwiQURfQ2xpZW50X0lEIjoxMSwiQURfT3JnX0lEIjo1MDAwMSwiQURfUm9sZV9JRCI6MTAzLCJBRF9Vc2VyX0lEIjoxMDIsIk1fV2FyZWhvdXNlX0lEIjo1MDAwMiwiQURfTGFuZ3VhZ2UiOiJlbl9VUyIsImlhdCI6MTY5MDEzOTg5NiwiZXhwIjoxNjkwMjI2Mjk2fQ.ApDL1F2pS_y9zs9ug_yGdwKLj2joEF5H40J5ik9wKhg' \
--data '{
"parameters": [
{
"key": "IsSOTrx",
"value": true
},
{
"key": "DaysDue",
"value": -99999
},
{
"key": "DaysDue_To",
"value": 99999
}
],
"report_type": "pdf",
"uuid": "a42b9c36-fb40-11e8-a479-7a0060f0aa01"
}'
```
```json
{
"code": 500,
"result": ""
}
```
```json
{
"code": 500,
"result": "You cannot create Reports for this …
```
=> fix: Report/Process without access and empty error message.

src/main/java/org/spin/base/db/ParameterUtil.java, src/main/java/org/spin/base/db/WhereClauseUtil.java, src/main/java/org/spin/base/dictionary/ReportUtil.java, src/main/java/org/spin/base/util/FileUtil.java, src/main/java/org/spin/form/import_file_loader/ImportFileLoaderServiceLogic.java, src/main/java/org/spin/grpc/service/BusinessDataServiceImplementation.java, src/main/java/org/spin/grpc/service/PointOfSalesServiceImplementation.java, src/main/java/org/spin/grpc/service/UserInterfaceServiceImplementation.java, src/main/proto/business.proto
https://github.com/solop-develop/adempiere-grpc-server/assets/20288327/c6fe63a8-d22b-4af5-be3a-64447d0079a5
https://github.com/solop-develop/adempiere-grpc-server/assets/20288327/4d27e513-b49a-4cc0-a11c-205824b9082c
fixes https://github.com/solop-develop/frontend-core/issues/1206
=> fix: Report Output without records.

src/main/java/org/spin/grpc/service/FileManagementServiceImplementation.java, src/main/proto/file_management.proto
```bash
curl --location --request PUT 'http://0.0.0.0:8085/api/adempiere/user-interface/component/resource/set-attachment-description' \
--header 'Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiIxMDAxMTM4IiwiQURfQ2xpZW50X0lEIjoxMSwiQURfT3JnX0lEIjo1MDAwNiwiQURfUm9sZV9JRCI6MTAyLCJBRF9Vc2VyX0lEIjoxMDEsIk1fV2FyZWhvdXNlX0lEIjo1MDAwNiwiQURfTGFuZ3VhZ2UiOiJlc19NWCIsImlhdCI6MTY5MDE0OTk2OSwiZXhwIjoxNjkwMjM2MzY5fQ.F96B_NLeSxL42QVUrbig5QYLlrn3E_kJdB-KDYAMkkA' \
--data '{
"id": 1000008,
"text_message": "a 1"
}'
```
```json
{
"code": 200,
"result": {
"id": 1000008,
"uuid": "0e4c5c9c-6b4e-4d5b-b775-a085b576b61a",
"attachment_uuid": "0e4c5c9c-6b4e-4d5b-b775-a085b576b61a",
"title": "zip",
"text_message": "a 1",
"resource_references_list": [
{
"id": …
```
=> feat: Set attachment description.

src/main/java/org/spin/grpc/service/FileManagementServiceImplementation.java, src/main/proto/file_management.proto
```bash
curl --location 'http://0.0.0.0:8085/api/adempiere/user-interface/component/resource/attachment?table_name=C_Order&id=1000044&uuid=93dec90c-b027-4cf2-b8ea-dabea984c286&ts=1690210516047' \
--header 'Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiIxMDAxMTQyIiwiQURfQ2xpZW50X0lEIjoxMSwiQURfT3JnX0lEIjo1MDAwNiwiQURfUm9sZV9JRCI6MTAyLCJBRF9Vc2VyX0lEIjoxMDEsIk1fV2FyZWhvdXNlX0lEIjo1MDAwNiwiQURfTGFuZ3VhZ2UiOiJlc19NWCIsImlhdCI6MTY5MDIzOTI0NCwiZXhwIjoxNjkwMzI1NjQ0fQ.0eEdKEoUkvPPAaWIIdhn4M7NV5GsjVu4CvpvyIMyaKo'
```
```json
{
"code": 200,
"result": {
"id": 1000008,
"uuid": "0e4c5c9c-6b4e-4d5b-b775-a085b576b61a",
"attachment_uuid": "0e4c5c9c-6b4e-4d5b-b775-a085b576b61a",
"title": "zip",
"text_message": "a 2s",
"resource_references_list": [
{
"reference_type": 0,
"reference_type_name": …
```
=> feat: Attachment Add Resource Reference Type.

src/main/java/org/spin/base/util/ReferenceUtil.java, src/main/java/org/spin/grpc/service/UserInterfaceServiceImplementation.java
```bash
curl --location 'http://0.0.0.0:8085/api/adempiere/user-interface/window/default-value?field_uuid=8d28d9b8-fb40-11e8-a479-7a0060f0aa01&value=109&ts=1690411078176' \
--header 'Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiIxMDAxMTQ2IiwiQURfQ2xpZW50X0lEIjoxMSwiQURfT3JnX0lEIjo1MDAwNiwiQURfUm9sZV9JRCI6MTAyLCJBRF9Vc2VyX0lEIjoxMDEsIk1fV2FyZWhvdXNlX0lEIjo1MDAwNiwiQURfTGFuZ3VhZ2UiOiJlc19NWCIsImlhdCI6MTY5MDQwMTg2OCwiZXhwIjoxNjkwNDg4MjY4fQ.gQbuaTaRcguoRciT29gjMuCbLbw696kZfnBBLDjxXAw'
```
```json
{
"code": 200,
"result": {
"id": 109,
"uuid": "28d2b4ec-e108-4810-a2e0-d94ca07b312d",
{
"value": "28d2b4ec-e108-4810-a2e0-d94ca07b312d-gwr_header.jpg"
},
{
"value": 109
},
{
"key": "UUID",
"value": …
```
=> feat: Add display column to `Image` display type.

src/main/java/org/spin/base/util/FileUtil.java, src/main/java/org/spin/grpc/service/FileManagementServiceImplementation.java
https://github.com/solop-develop/adempiere-grpc-server/assets/20288327/f4e8bd35-bdc3-425f-bbbe-3ef5998d198c
fixes https://github.com/solop-develop/frontend-core/issues/1238
=> feat: Add upload attachment as `Image` field.

src/main/java/org/spin/grpc/service/SecurityServiceImplementation.java, src/main/proto/security.proto
Add file name to get:
- Client logo.
- Client report logo.
- Client web logo.
=> feat: Add client logo.

src/main/java/org/spin/grpc/service/FileManagementServiceImplementation.java
When an image/archive is created, it automatically creates the child attachment reference, however deleting the attachment reference does not remove the parent or linked image/archive.
fixes https://github.com/solop-develop/frontend-core/issues/1248
=> fix: Delete image/archive linked to attachment reference.

src/main/java/org/spin/grpc/service/FileManagementServiceImplementation.java
Early validation of the attachment reference, due to the fact that the file was previously uploaded and was using resources by unnecessarily uploading the file without the resource reference existing or having a file handler configured.
fixes https://github.com/solop-develop/frontend-core/issues/1238
=> fix: Validate Attachment Reference before upload file.

src/main/java/org/spin/grpc/service/FileManagementServiceImplementation.java, src/main/proto/file_management.proto
Get resource reference (attachment reference) by:
- `ID` of Attachment Reference.
- `UUID` of Attachment Reference.
- Resource Name of Attachment Reference (`UUID` + `FileName`).
- `ID` of Image.
- `UUID` of Image.
- `ID` of Archive.
- `UUID` of Archive.
fixes https://github.com/solop-develop/frontend-core/issues/1251
=> feat: Get Resource Reference by Identifier/Archive/Image.

src/main/java/org/spin/grpc/service/LogsServiceImplementation.java, src/main/java/org/spin/log/LogsConvertUtil.java, src/main/java/org/spin/log/LogsServiceLogic.java, src/main/proto/base_data_type.proto, src/main/proto/logs.proto
```bash
curl --location 'http://localhost:8085/api/adempiere/user/log/user-activities' \
--header 'Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiIxMDAxMTc0IiwiQURfQ2xpZW50X0lEIjoxMSwiQURfT3JnX0lEIjo1MDAwNiwiQURfUm9sZV9JRCI6MTAyLCJBRF9Vc2VyX0lEIjoxMDEsIk1fV2FyZWhvdXNlX0lEIjo1MDAwNiwiQURfTGFuZ3VhZ2UiOiJlbl9VUyIsImlhdCI6MTY5MDg0OTM2MiwiZXhwIjoxNjkwOTM1NzYyfQ.uJTwHE9FVfvqBrmB5ccahbA7jPbAbYLn1sUfjmBsgeQ'
```
```json
{
"code": 200,
"result": {
"record_count": 6,
"records": [
{
"user_activity_type": 0,
"user_activity_type_name": "ENTITY_LOG",
"entity_log": {
"log_id": 1005706,
"id": 1000019,
"uuid": "",
"record_id": 1000019,
"record_uuid": "",
"table_name": "C_BPartner",
"session_uuid": "93960c40-4d7f-45aa-82a1-2b5c5746cbc5",
"user_uuid": …
```
=> feat: User Activity.

src/main/java/org/spin/form/import_file_loader/ImportFileLoaderServiceLogic.java, src/main/proto/import_file_loader.proto
```bash
curl --location 'http://localhost:8085/api/adempiere/form/addons/import-file-loader/list-file-preview?import_format_id=102&resource_id=1000197&charset=UTF-8' \
--header 'Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiIxMDAxMTc3IiwiQURfQ2xpZW50X0lEIjoxMSwiQURfT3JnX0lEIjo1MDAwNiwiQURfUm9sZV9JRCI6MTAyLCJBRF9Vc2VyX0lEIjoxMDEsIk1fV2FyZWhvdXNlX0lEIjo1MDAwNiwiQURfTGFuZ3VhZ2UiOiJlc19NWCIsImlhdCI6MTY5MDkwMTQ2NywiZXhwIjoxNjkwOTg3ODY3fQ.qO6YZOvLQpWjvIIjlM8vI5gpKrZku6VScHiu6ryBaSA'
```
```json
{
"code": 200,
"result": {
"records": [
{
"id": 0,
"uuid": "",
"table_name": "I_ElementValue",
{
"key": "AccountSign",
"value": null
},
{
"key": "AccountType",
"value": null
},
{
"key": "ChargeName",
"value": null
},
{
"key": …
```
=> feat: `Import File Loader` File Preview.

src/main/java/org/spin/base/util/DictionaryUtil.java
https://github.com/solop-develop/adempiere-grpc-server/assets/20288327/a427b403-9033-41a3-a11f-c71532e8bee4
https://github.com/solop-develop/adempiere-grpc-server/assets/20288327/bd6e2639-f95c-4e88-93d6-256fb5422803
related changes https://github.com/adempiere/adempiere/pull/4124
=> feat: ReadOnly Logic on ClientInfo.

src/main/java/org/spin/grpc/service/PointOfSalesServiceImplementation.java
```
org.postgresql.util.PSQLException: ERROR: syntax error at end of input
Position: 388, SQL=SELECT AD_User_ID FROM AD_User WHERE ((EXISTS( SELECT
1 FROM C_POSSellerAllocation AS seller WHERE seller.C_POS_ID = ? AND
seller.SalesRep_ID = AD_User.AD_User_ID AND seller.IsActive = 'Y' AND
seller.IsAllowsPOSManager = 'Y' AND seller.IsAllowsModifyDiscount= 'Y'
AND (seller.MaximumLineDiscountAllowed >= ? OR
seller.MaximumLineDiscountAllowed = 0)) AND UserPIN = ? ) AND IsActive=?
```
=> Fixed error with SQL Error for User PIN:

src/main/java/org/spin/form/import_file_loader/ImportFileLoaderServiceLogic.java
When Import Format Row exists constants values, the values to send client is bad format.
fixes https://github.com/solop-develop/frontend-core/issues/1223
=> fix: Preview file with contant import format row.

src/main/java/org/spin/log/LogsConvertUtil.java, src/main/proto/base_data_type.proto, src/main/proto/logs.proto
- Add window translated name or translated name of table to records logs.
- Add parameter translated name to process parameter log.
fixes https://github.com/solop-develop/frontend-core/issues/1262
=> feat: `User Activity` logs with displayed name.

src/main/java/org/spin/grpc/service/LogsServiceImplementation.java
Just resolve a minor problem with workflow logs, the correct order will be by updated desc
=> Fixed error with sorting for workflow logs

src/main/java/org/spin/grpc/service/PointOfSalesServiceImplementation.java, src/main/java/org/spin/pos/service/cash/CashManagement.java, src/main/java/org/spin/pos/service/cash/CashUtil.java, src/main/java/org/spin/pos/service/order/OrderManagement.java, src/main/java/org/spin/pos/service/order/OrderUtil.java, src/main/java/org/spin/pos/service/order/ReverseSalesTransaction.java
=> Add changes for Point of sales based on last supported version of 3.9.3

src/main/java/org/spin/grpc/service/PointOfSalesServiceImplementation.java
This pull request allows use a customer bank account based on combination of:
- Customer ID
- Bank
- Account No
- Social Security Number
=> Add support to finding Customer Bank account

src/main/java/org/spin/base/db/WhereClauseUtil.java
https://github.com/solop-develop/adempiere-grpc-server/assets/20288327/dd3ee160-4d92-4e48-92c1-cc540ccd886f
```json
{
"code": 500,
"result": ""
}
```
https://github.com/solop-develop/adempiere-grpc-server/assets/20288327/be2128d8-ad7b-494e-902c-d4f5b8c08fdd
```log
===========> UserInterfaceServiceImplementation.listBrowserItems: null [2655]
at org.spin.base.db.WhereClauseUtil.lambda$getBrowserWhereClauseFromCriteria$8(WhereClauseUtil.java:790)
at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
at …
```
=> fix: Smart Browser Query Criteria with range fields.

src/main/java/org/spin/form/bank_statement_match/BankStatementMatchConvertUtil.java, src/main/java/org/spin/form/bank_statement_match/BankStatementMatchServiceLogic.java, src/main/java/org/spin/form/bank_statement_match/BankStatementMatchUtil.java, src/main/java/org/spin/grpc/service/BankStatementMatchServiceImplementation.java, src/main/proto/bank_statement_match.proto
```bash
curl 'http://0.0.0.0:8085/api/adempiere/form/addons/bank-statement-match/matching-movements?match_mode=0&bank_account_id=100&business_partner_id=&ts=1691462574151' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/116.0' -H 'Accept: application/json, text/plain, */*' -H 'Accept-Language: es-MX,es;q=0.8,en-US;q=0.5,en;q=0.3' -H 'Accept-Encoding: gzip, deflate' -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiIxMDAxODg1IiwiQURfQ2xpZW50X0lEIjoxMSwiQURfT3JnX0lEIjoxMDAwMDA0LCJBRF9Sb2xlX0lEIjoxMDIsIkFEX1VzZXJfSUQiOjEwMSwiTV9XYXJlaG91c2VfSUQiOjAsIkFEX0xhbmd1YWdlIjoiZXNfTVgiLCJpYXQiOjE2OTE0MjQxMTMsImV4cCI6MTY5MTUxMDUxM30.8Z94lqQrWOW6ZQTWZpYxSPGwHhCtfbazzm_KAV69SJk' -H 'Origin: http://0.0.0.0:9527' -H 'Connection: keep-alive' -H 'Referer: …
```
=> feat: `Bank Statement Match` form, matched paymends. 

src/main/java/org/spin/grpc/service/BusinessDataServiceImplementation.java
https://github.com/solop-develop/frontend-core/assets/20288327/299bf2c0-a181-434e-883e-f633b1270056
https://github.com/solop-develop/frontend-core/assets/20288327/a29993d4-9124-4ec4-9ccd-a7c2d0d5a87b
Add any other context about the problem here.
=> fix: Run Process/Report with hidden parameters.

src/main/java/org/spin/pos/service/order/OrderManagement.java
This pull request allows validate payment processor before online process for payments
=> Validate payment processor before process payment

src/main/java/org/spin/grpc/service/PointOfSalesServiceImplementation.java
Just a minor change that allows remove throw exception and change it for warning
=> Remove throw exception for print tickets

src/main/java/org/spin/form/bank_statement_match/BankStatementMatchConvertUtil.java, src/main/java/org/spin/form/bank_statement_match/BankStatementMatchServiceLogic.java, src/main/java/org/spin/form/bank_statement_match/BankStatementMatchUtil.java, src/main/java/org/spin/grpc/service/BankStatementMatchServiceImplementation.java
```bash
curl 'http://0.0.0.0:8085/api/adempiere/form/addons/bank-statement-match/payments?bank_account_id=100&business_partner_id=&ts=1691544448315' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/116.0' -H 'Accept: application/json, text/plain, */*' -H 'Accept-Language: es-MX,es;q=0.8,en-US;q=0.5,en;q=0.3' -H 'Accept-Encoding: gzip, deflate' -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiIxMDAxODkwIiwiQURfQ2xpZW50X0lEIjoxMSwiQURfT3JnX0lEIjowLCJBRF9Sb2xlX0lEIjoxMDIsIkFEX1VzZXJfSUQiOjEwMSwiTV9XYXJlaG91c2VfSUQiOjAsIkFEX0xhbmd1YWdlIjoiZXNfTVgiLCJpYXQiOjE2OTE1MzA5NzAsImV4cCI6MTY5MTYxNzM3MH0.5U94cII5WtzibokirAoTEoV1xrLYAqHL2sDqOfiVlxg' -H 'Origin: http://0.0.0.0:9527' -H 'Connection: keep-alive' -H 'Referer: http://0.0.0.0:9527/' -H 'Pragma: no-cache' …
```
=> feat: `Bank Statement Match` list payments.

src/main/java/org/spin/form/issue_management/IssueManagementConvertUtil.java, src/main/java/org/spin/grpc/service/IssueManagementServiceImplementation.java, src/main/proto/issue_management.proto
- Change sales representative to user definition.
- Add avatar on user definition.
- Improve Query with list id.
=> feat: Add `Issue` (Request) form user/sales representative avatar.

src/main/java/org/spin/grpc/service/PointOfSalesServiceImplementation.java
The problem is that when the price is changed, the proce entered is recalculated instead of price actual
=> Fixed error with price for sales order

src/main/java/org/spin/form/bank_statement_match/BankStatementMatchConvertUtil.java, src/main/java/org/spin/form/bank_statement_match/BankStatementMatchServiceLogic.java, src/main/java/org/spin/form/bank_statement_match/BankStatementMatchUtil.java, src/main/java/org/spin/grpc/service/BankStatementMatchServiceImplementation.java, src/main/proto/bank_statement_match.proto
- Match selection.
- Unmatch selection.
- List Result Movements.
- Process Data.
=> feat: `Bank Statement Match` form, process.

src/main/java/org/spin/form/bank_statement_match/BankStatementMatchConvertUtil.java, src/main/java/org/spin/form/bank_statement_match/BankStatementMatchServiceLogic.java
Set correct automatic match flag.
fixes https://github.com/solop-develop/frontend-core/issues/1296
=> fix: Set automatic match.

src/main/java/org/spin/grpc/service/PointOfSalesServiceImplementation.java
This pull request apply for discount of product with different uom in order line
=> Fixed error with discount for distint UOM

src/main/java/org/spin/form/bank_statement_match/BankStatementMatchConvertUtil.java, src/main/proto/bank_statement_match.proto
https://github.com/solop-develop/adempiere-grpc-server/assets/20288327/332f3e3a-c191-48c5-9a78-f4d6eddc3c18
fixes https://github.com/solop-develop/frontend-core/issues/1320
=> feat: `Bank Statenent Match` form, accounting and balance info.

src/main/java/org/spin/grpc/service/PointOfSalesServiceImplementation.java, src/main/java/org/spin/pos/service/order/ReverseSalesTransaction.java
- Payment as Zero for add collect to order
- Reverse transaction for a sales order as draft
- Reverse transaction for RMA
=> Some validations

src/main/java/org/spin/grpc/service/DictionaryServiceImplementation.java
Minor chage for validate NPE loading window
=> Fixed error with NPE Loading windows

src/main/java/org/spin/base/util/DocumentUtil.java, src/main/java/org/spin/grpc/service/PointOfSalesServiceImplementation.java, src/main/java/org/spin/pos/service/order/OrderManagement.java, src/main/java/org/spin/pos/service/order/ReverseSalesTransaction.java
- Avoid reverse RMA
- Avoid reverse drafted orders
- Discount calculation for distints unit of measures
=> Add validation for point of sales

src/main/java/org/spin/grpc/service/PointOfSalesServiceImplementation.java
List orders waiting for pay, only `Completed` document status.
=> fix: List Orders waiting for pay only completed.

src/main/java/org/spin/grpc/service/PointOfSalesServiceImplementation.java
Add proposal restriction, and invoice open to list orders.
=> fix: POS List orders wihtout proposal, and invoice open.

src/main/java/org/spin/form/issue_management/IssueManagementConvertUtil.java, src/main/java/org/spin/grpc/service/IssueManagementServiceImplementation.java, src/main/proto/issue_management.proto
Add default status on request type.
fixes https://github.com/solop-develop/frontend-core/issues/1353
=> fix: Issues form with other clients.

src/main/java/org/spin/base/dictionary/WindowUtil.java, src/main/java/org/spin/grpc/logic/GeneralLedgerServiceLogic.java, src/main/java/org/spin/grpc/service/CoreFunctionalityImplementation.java, src/main/java/org/spin/grpc/service/ExpressMovementServiceImplementation.java, src/main/java/org/spin/grpc/service/ExpressReceiptServiceImplementation.java, src/main/java/org/spin/grpc/service/ExpressShipmentServiceImplementation.java, src/main/java/org/spin/grpc/service/FileManagementServiceImplementation.java, src/main/java/org/spin/grpc/service/GeneralLedgerServiceImplementation.java, src/main/java/org/spin/grpc/service/IssueManagementServiceImplementation.java, src/main/java/org/spin/grpc/service/MatchPOReceiptInvoiceServiceImplementation.java, src/main/java/org/spin/grpc/service/MaterialManagementServiceImplementation.java, src/main/java/org/spin/grpc/service/PaymentPrintExportServiceImplementation.java, src/main/java/org/spin/grpc/service/TimeControlServiceImplementation.java, src/main/java/org/spin/grpc/service/TimeRecordServiceImplementation.java, src/main/java/org/spin/grpc/service/UserCustomizationImplementation.java, src/main/java/org/spin/grpc/service/UserInterfaceServiceImplementation.java, src/main/java/org/spin/grpc/service/WorkflowServiceImplementation.java, src/main/java/org/spin/log/LogsServiceLogic.java
- Filter active records.
- Filter role/client access records.
=> fix: Filter access records, and active records.

src/main/java/org/spin/grpc/service/PointOfSalesServiceImplementation.java, src/main/proto/point_of_sales.proto
Add list orders:
- Binding Offer.
- Closed.
- Voided.
fixes https://github.com/solop-develop/frontend-core/issues/657
fixes https://github.com/solop-develop/frontend-core/issues/1362
=> feat: POS List sales orders, closed, voided, is binding offer.

src/main/java/org/spin/grpc/service/PointOfSalesServiceImplementation.java, src/main/java/org/spin/pos/service/POSServiceLogic.java, src/main/java/org/spin/pos/util/POSConvertUtil.java, src/main/proto/point_of_sales.proto
```bash
curl --location 'http://localhost:8085/api/adempiere/form/addons/point-of-sales/banks?pos_uuid=1201f142-b4b6-4156-b8c3-dcf15e41d39d&price_list_uuid=54745978-ce79-11e9-aa53-0242ac110002&page_size=15&ts=1692655539328' \
--header 'Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiIxMDAxOTYxIiwiQURfQ2xpZW50X0lEIjoxMSwiQURfT3JnX0lEIjowLCJBRF9Sb2xlX0lEIjoxMDIsIkFEX1VzZXJfSUQiOjEwMSwiTV9XYXJlaG91c2VfSUQiOjAsIkFEX0xhbmd1YWdlIjoiZXNfTVgiLCJpYXQiOjE2OTI2NTYwMjcsImV4cCI6MTY5Mjc0MjQyN30.kWyEsQ2BIsgVbX4ZnEAkDMq3dVUS7cCT1LPMlJKdzXc'
```
```json
{
"code": 200,
"result": {
"records": [
{
"id": 100,
"uuid": "1a13cb9f-0456-4fd3-ac14-d90d257b4f9c",
"name": "MoneyBank",
"routing_no": "123456789",
"swift_code": "12345"
},
{
"id": 50000, …
```
=> feat: POS List Banks.

src/main/java/org/spin/base/util/ConvertUtil.java, src/main/java/org/spin/grpc/service/PointOfSalesServiceImplementation.java, src/main/java/org/spin/pos/service/POSServiceLogic.java, src/main/java/org/spin/pos/util/POSConvertUtil.java, src/main/proto/point_of_sales.proto
```bash
curl --location 'http://localhost:8085/api/adempiere/form/addons/point-of-sales/campaigns?pos_uuid=1201f142-b4b6-4156-b8c3-dcf15e41d39d&search_value=mail&page_size=15&ts=1692655539328' \
--header 'Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiIxMDAxOTYxIiwiQURfQ2xpZW50X0lEIjoxMSwiQURfT3JnX0lEIjowLCJBRF9Sb2xlX0lEIjoxMDIsIkFEX1VzZXJfSUQiOjEwMSwiTV9XYXJlaG91c2VfSUQiOjAsIkFEX0xhbmd1YWdlIjoiZXNfTVgiLCJpYXQiOjE2OTI2NTYwMjcsImV4cCI6MTY5Mjc0MjQyN30.kWyEsQ2BIsgVbX4ZnEAkDMq3dVUS7cCT1LPMlJKdzXc'
```
```json
{
"code": 200,
"result": {
"records": [
{
"id": 102,
"uuid": "f51b6906-dc87-44bb-bde8-8eb379f2e01d",
"name": "Spring Mailer",
"description": "Brochure Mailing for Spring",
"start_date": 1606881600000,
"end_date": 1611547200000
}
]
}
}
``` …
=> feat: POS List active `Campaigns`.

src/main/java/org/spin/base/util/ConvertUtil.java, src/main/java/org/spin/grpc/service/PointOfSalesServiceImplementation.java, src/main/java/org/spin/pos/util/POSConvertUtil.java, src/main/proto/point_of_sales.proto
On shipment line add:
- Movement quantity.
- UOM convertion.
- Product UOM convertion.
fixes https://github.com/solop-develop/frontend-core/issues/1364
=> feat: POS Shipment Line add movement quantity and uom conversion.

src/main/java/org/spin/form/bank_statement_match/BankStatementMatchServiceLogic.java
fixes https://github.com/solop-develop/frontend-core/issues/1298
=> fix: `Bank Statement Match` form list only not `Processed`.

src/main/java/org/spin/authentication/AuthorizationServerInterceptor.java, src/main/java/org/spin/base/util/ServiceContextProvider.java, src/main/java/org/spin/base/util/SessionManager.java, src/main/java/org/spin/grpc/service/SecurityServiceImplementation.java, src/main/java/org/spin/grpc/service/UpdateImplementation.java, src/main/java/org/spin/pos/service/order/OrderManagement.java, src/main/java/org/spin/server/AllInOneServices.java
- Open two sessions: Use a single tab (tab 1) and other as incognito (tab 2):
- Tab 1:
- Login with User 1
- Open POS
- Make a Order
- Add Payments
- Tab 2:
- Login with User 2
- Open POS
- Make a Order
- Add Payments
- After add payments press the pay button in two tabs fast
- Open the two generated documents and see that changes was crossover between both orders
=> Fixed error with merge session from two or more users

src/main/java/org/spin/form/bank_statement_match/BankStatementMatchConvertUtil.java, src/main/java/org/spin/form/bank_statement_match/BankStatementMatchServiceLogic.java, src/main/java/org/spin/form/bank_statement_match/BankStatementMatchUtil.java, src/main/proto/bank_statement_match.proto
Filter Imported Bank Movements by bank statement id.
fixes https://github.com/solop-develop/frontend-core/issues/1323
=> feat: `Bank Statement Match` filter by bank statement id.

src/main/java/org/spin/authentication/AuthorizationServerInterceptor.java, src/main/java/org/spin/grpc/service/SecurityServiceImplementation.java
When the user is logout, the session shoul be removed
=> Revoke session when is logout

src/main/java/org/spin/base/util/ConvertUtil.java, src/main/java/org/spin/grpc/service/PointOfSalesServiceImplementation.java, src/main/java/org/spin/pos/service/POSServiceLogic.java, src/main/java/org/spin/pos/service/bank/BankManagement.java, src/main/proto/point_of_sales.proto
```bash
curl --location 'http://localhost:8085/api/adempiere/form/addons/point-of-sales/banks?bank_id=100&search_value=&page_size=15&ts=1692655539328' \
--header 'Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiIxMDAyMDAxIiwiQURfQ2xpZW50X0lEIjoxMSwiQURfT3JnX0lEIjoxMDAwMDA0LCJBRF9Sb2xlX0lEIjoxMDIsIkFEX1VzZXJfSUQiOjEwMSwiTV9XYXJlaG91c2VfSUQiOjAsIkFEX0xhbmd1YWdlIjoiZW5fVVMiLCJpYXQiOjE2OTI5OTI5MjIsImV4cCI6MTY5MzA3OTMyMn0.Zv0DL4TXT6p4AEyFKjKbHgeE6m02uaRvz1uzoTy0N8M'
```
```json
{
"code": 200,
"result": {
"records": [
{
"id": 50000,
"uuid": "63835e4e-87fa-4217-964b-976caec4b947",
"name": "POS Transfer Control Bank",
"routing_no": "1234567",
"swift_code": ""
},
{
"id": 100,
"uuid": "1a13cb9f-0456-4fd3-ac14-d90d257b4f9c",
"name": …
```
=> feat: POS List `Bank Accounts`.

src/main/java/org/spin/grpc/service/PointOfSalesServiceImplementation.java
a service for list cash movements
=> Add service for cash movements

src/main/java/org/spin/grpc/service/PointOfSalesServiceImplementation.java, src/main/java/org/spin/pos/service/order/OrderManagement.java
- On Credit Order
- Binding Orders
=> Fixed error with options:

src/main/java/org/spin/pos/service/POSServiceLogic.java
```bash
curl --location 'http://localhost:8085/api/adempiere/form/addons/point-of-sales/bank-accounts?bank_id=100&search_value=&page_size=15&ts=1692655539328' \
--header 'Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiIxMDAyMDAxIiwiQURfQ2xpZW50X0lEIjoxMSwiQURfT3JnX0lEIjoxMDAwMDA0LCJBRF9Sb2xlX0lEIjoxMDIsIkFEX1VzZXJfSUQiOjEwMSwiTV9XYXJlaG91c2VfSUQiOjAsIkFEX0xhbmd1YWdlIjoiZW5fVVMiLCJpYXQiOjE2OTI5OTI5MjIsImV4cCI6MTY5MzA3OTMyMn0.Zv0DL4TXT6p4AEyFKjKbHgeE6m02uaRvz1uzoTy0N8M'
```
```json
{
"code": 200,
"result": {
"records": [
{
"uuid": "9a5bbbb8-9b69-4c13-be86-0a1a370200e2",
"id": 0,
"name": "MoneyBank 5678",
"account_no": "5678",
"description": "With Optimal Payments",
"currency": {
"id": 100,
"uuid": "a5671df0-fb40-11e8-a479-7a0060f0aa01", …
```
=> fix: List bank accounts.

src/main/java/org/spin/grpc/service/PointOfSalesServiceImplementation.java, src/main/proto/point_of_sales.proto
Add `id` and `uuid` on `ListCashMovementsResponse` proto message.
=> feat: POS Add id and uuid on `ListCashMovementsResponse`.

src/main/java/org/spin/base/dictionary/DictionaryUtil.java, src/main/java/org/spin/base/dictionary/custom/BrowseFieldCustomUtil.java, src/main/java/org/spin/base/dictionary/custom/FieldCustomUtil.java, src/main/java/org/spin/base/dictionary/custom/ProcessParaCustomUtil.java, src/main/java/org/spin/grpc/service/DictionaryServiceImplementation.java, src/main/java/org/spin/grpc/service/UserCustomizationImplementation.java, src/main/proto/dictionary.proto, src/main/proto/user_customization.proto
https://github.com/solop-develop/adempiere-grpc-server/assets/20288327/fa93870d-63b7-4465-aef8-a0bda0584abe
fixes https://github.com/solop-develop/frontend-core/issues/1129
fixes https://github.com/solop-develop/frontend-core/issues/1348
=> feat: Persistent front show/hidden fields.

build.gradle, src/main/java/org/spin/base/util/FileUtil.java, src/main/java/org/spin/grpc/service/BusinessDataServiceImplementation.java, src/main/java/org/spin/grpc/service/PointOfSalesServiceImplementation.java, src/main/proto/point_of_sales.proto
Add support to print ticket based on new definition of `adempiere-pos-improvements` project
=> Add new definition for Print Ticket

src/main/proto/point_of_sales.proto
Some changes for references and add RMA and RMALine entity
=> Just add return order support

src/main/java/org/spin/grpc/service/PointOfSalesServiceImplementation.java
Business Partner Name + Account No + Routing No
=> feat: Add routing no on customer bank account.

src/main/java/org/spin/authentication/AuthorizationServerInterceptor.java, src/main/java/org/spin/base/util/SessionManager.java, src/main/java/org/spin/grpc/service/SecurityServiceImplementation.java, src/main/proto/security.proto
This change allows add authentication using Open ID Service
=> Add support to authentication with Open ID

src/main/java/org/spin/base/util/ConvertUtil.java, src/main/java/org/spin/grpc/service/PointOfSalesServiceImplementation.java, src/main/java/org/spin/pos/service/cash/CollectingManagement.java, src/main/java/org/spin/pos/service/order/OrderManagement.java, src/main/java/org/spin/pos/service/order/OrderUtil.java, src/main/java/org/spin/pos/service/order/ReturnSalesOrder.java
A implementation for Create RMA Service
=> Just add createRMA implementation

src/main/java/org/spin/pos/service/order/ReverseSalesTransaction.java
After reverse sales transaction the IsInvoiced flag is not setted in RMA
=> Fixed error with reverse sales transaction

src/main/java/org/spin/base/util/ConvertUtil.java, src/main/java/org/spin/grpc/service/PointOfSalesServiceImplementation.java, src/main/java/org/spin/pos/service/order/OrderUtil.java, src/main/java/org/spin/pos/service/order/RMAUtil.java, src/main/java/org/spin/pos/service/order/ReturnSalesOrder.java, src/main/java/org/spin/pos/service/order/ReverseSalesTransaction.java
- Create RMA
- Create RMA Line
- Update RMA Line
- Delete RMA Line
=> Add RMA services

src/main/java/org/spin/base/util/ValueUtil.java
fixes https://github.com/solop-develop/frontend-core/issues/1393
=> fix: Cast `Long` as `Integer` and `BigDecimal` with column sql.

src/main/java/org/spin/pos/service/order/OrderManagement.java, src/main/java/org/spin/pos/service/order/RMAUtil.java, src/main/java/org/spin/pos/service/order/ReturnSalesOrder.java
Add return order quantity validation
=> Add return order quantity validation

src/main/java/org/spin/pos/service/order/OrderManagement.java
Just add current user for copied Sales Order
=> Just add current user for copied Sales Order

src/main/java/org/spin/grpc/service/DictionaryServiceImplementation.java
https://github.com/solop-develop/adempiere-grpc-server/assets/20288327/53364101-36be-480b-adad-ff391cdc0cc5
fixes https://github.com/solop-develop/frontend-core/issues/1129
=> fix: Load fields with is displayed table customization.

src/main/java/org/spin/base/util/ConvertUtil.java, src/main/java/org/spin/grpc/service/PointOfSalesServiceImplementation.java, src/main/java/org/spin/pos/service/order/OrderUtil.java, src/main/proto/point_of_sales.proto
- is_rma
- is_binding_offer
- is_order
=> Just add flags for determine a order type:

src/main/java/org/spin/base/util/ConvertUtil.java, src/main/java/org/spin/grpc/service/PointOfSalesServiceImplementation.java, src/main/java/org/spin/pos/service/order/OrderUtil.java, src/main/java/org/spin/pos/service/order/RMAUtil.java, src/main/java/org/spin/pos/service/order/ReturnSalesOrder.java, src/main/java/org/spin/pos/util/ColumnsAdded.java
This process allows collect a invoice with a credit Memo
=> Allows collect with credit memo

build.gradle
https://github.com/solop-develop/adempiere-grpc-server/pull/496/checks
=> fix: Build project with ADempiere-JWT-Token.

src/main/java/org/spin/grpc/service/CoreFunctionalityImplementation.java, src/main/java/org/spin/grpc/service/SecurityServiceImplementation.java, src/main/proto/security.proto
- Change `UUID` to `ID` on security requests.
=> feat: Change `uuid` to `id` security requests.

src/main/java/org/spin/grpc/service/CoreFunctionalityImplementation.java
When role is `System` (AD_Role_ID=0), no list of organizations.
=> fix: Load organizations by role=0.

.github/workflows/publish.yml, .gitignore, build.gradle, docker/alpine.Dockerfile, docker/focal.Dockerfile, src/main/java/org/spin/authentication/AuthorizationServerInterceptor.java, src/main/java/org/spin/base/Version.java, src/main/java/org/spin/grpc/service/CoreFunctionalityImplementation.java, src/main/proto/core_functionality.proto
```bash
curl --location 'http://localhost:8085/api/adempiere/core/system-info'
```
```json
{
"code": 200,
"result": {
"name": "",
"release_no": "3.9.4",
"version": "2023-01-24",
"last_build_info": "ADempiere Foundation Release 3.9.4 20230117-1854",
"logo_url": "",
"backend_date_version": "2023-09-14",
"backend_main_version": "1.0.0-dev",
"backend_implementation_version": "1.0.0-dev",
"proxy_version": "1.0.0-rc.3"
}
}
```
=> feat: Add `SystemInfo` service.

resources/envoy.yaml, src/main/proto/business.proto, src/main/proto/core_functionality.proto, src/main/proto/dashboarding.proto, src/main/proto/dictionary.proto, src/main/proto/enrollment.proto, src/main/proto/express_movement.proto, src/main/proto/express_receipt.proto, src/main/proto/security.proto
Transcoding.
- Business Data.
- User Interface.
- Core Functionality.
- Dashboarding.
- Dictionary.
- Enrollment.
- Express Movement.
- Express Receipt.
=> feat: Transcoding data.proto (`BusinessData` and `UserInterface` services).

src/main/java/org/spin/grpc/service/SecurityServiceImplementation.java
https://github.com/solop-develop/adempiere-grpc-server/assets/20288327/44dc463b-0217-4ed0-aef4-23ed88776b56
https://github.com/solop-develop/adempiere-grpc-server/assets/20288327/097990e0-db86-4bb8-bad9-f6d309dac9fa
fixes https://github.com/solop-develop/frontend-core/issues/1466
=> fix: Organization context different of session.

src/main/java/org/spin/base/db/FromUtil.java, src/main/java/org/spin/base/db/QueryUtil.java, src/main/java/org/spin/base/util/ReferenceInfo.java
```log
Error getting browser search: org.postgresql.util.PSQLException: ERROR: column so.c_projectcategory_id does not exist
```
fixes https://github.com/solop-develop/adempiere-grpc-server/issues/514
=> fix: SB View Column with sub query as lookup reference.

src/main/java/org/spin/pos/service/order/OrderUtil.java, src/main/java/org/spin/pos/service/order/RMAUtil.java
=> Fixed error with return order when a source order is not delivered or

src/main/java/org/spin/base/util/ConvertUtil.java, src/main/java/org/spin/base/util/LookupUtil.java, src/main/java/org/spin/base/util/RecordUtil.java, src/main/java/org/spin/base/util/ValueUtil.java, src/main/java/org/spin/grpc/service/BusinessData.java, src/main/java/org/spin/grpc/service/BusinessPartner.java, src/main/java/org/spin/grpc/service/LogsInfo.java, src/main/java/org/spin/grpc/service/UserInterface.java, src/main/java/org/spin/log/LogsConvertUtil.java, src/main/proto/business.proto, src/main/proto/business_partner.proto, src/main/proto/logs.proto
https://documenter.getpostman.com/view/3549586/2s9YJaXj1m#6a24a2a3-580e-4d0b-8b64-4834f90b610a
=> feat: Add transcoding `BusinessPartner` and `UserInterface`.

src/main/java/org/spin/base/util/ConvertUtil.java, src/main/java/org/spin/form/bank_statement_match/BankStatementMatchServiceLogic.java, src/main/java/org/spin/form/import_file_loader/ImportFileLoaderServiceLogic.java, src/main/java/org/spin/grpc/service/BusinessData.java, src/main/java/org/spin/grpc/service/PaymentPrintExport.java, src/main/java/org/spin/grpc/service/PayrollActionNotice.java, src/main/java/org/spin/grpc/service/Security.java, src/main/java/org/spin/grpc/service/UserInterface.java
Struct values only get with last put value.
=> fix: Struct values.

src/main/java/org/spin/base/db/OperatorUtil.java, src/main/java/org/spin/base/db/WhereClauseUtil.java, src/main/java/org/spin/base/query/Filter.java
=> fix: Smart Browser with filters.

README.es.md, README.md, src/main/java/org/spin/grpc/service/SecurityServiceImplementation.java
when the `MTreeNode` has a value in `Parent_ID` that does not exist in the `AD_Menu` table it generates a `Null Pointer Exception` when trying to instantiate the parent menu node.
https://github.com/solop-develop/adempiere-grpc-server/assets/20288327/a52bdb5b-4060-42fd-99a6-d3cccaa58cd9
```log
===========> MTree.loadNodes: Nodes w/o parent - adding to root - [Catálogo de Productos, Catálogo de Productos desde Orden de Venta (Menú)] [36]
```
=> fix: Null Pointer Exception when tree parent id, without menu.

src/main/java/org/spin/grpc/service/BusinessDataServiceImplementation.java, src/main/proto/business.proto
```bash
curl 'http://localhost:8085/api/adempiere/common/api/process?ts=1696529957028' \
-X POST \
-H 'Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiIxMDAyMTg4IiwiQURfQ2xpZW50X0lEIjoxMSwiQURfT3JnX0lEIjoxMDAwMDA0LCJBRF9Sb2xlX0lEIjoxMDIsIkFEX1VzZXJfSUQiOjEwMCwiTV9XYXJlaG91c2VfSUQiOi0xLCJBRF9MYW5ndWFnZSI6ImVzX01YIiwiaWF0IjoxNjk2NTI5ODYzLCJleHAiOjE2OTY2MTYyNjN9.rPXliEN79CbQaWxW4Eh-JzJ7DpyxNMOaVgSNyph4Ooo' \
--data-raw '{"uuid":"a42d0c38-fb40-11e8-a479-7a0060f0aa01","parameters":[{"key":"DocAction","value":"CO"}],"browser_id":50075,"selections":[{"selectionId":1000001,"selectionValues":[{"columnName":"O_C_Order_ID","valueType":"INTEGER","value":1000001},{"columnName":"O_DateOrdered","valueType":"DATE", …
```
=> feat: Run process with `Smart Browser ID`.

src/main/java/org/spin/grpc/service/LogsInfo.java, src/main/proto/logs.proto
=> feat: (Transcoding) Process logs or `Process Activity`.

src/main/java/org/spin/grpc/service/Dictionary.java, src/main/proto/dictionary.proto
Remove unused `GetValidationRule` service, this is deprecated.
Add process/report definition `is_have_parameres` to validate request definition on processes associated.
=> feat: (Transcoding) Remove validation rule.

src/main/java/org/spin/base/workflow/WorkflowUtil.java, src/main/proto/business.proto, src/main/proto/workflow.proto
https://github.com/solop-develop/frontend-core/assets/20288327/1e10e21f-a38a-49d3-9212-543856c99f39
=> feat: (Transcoding) Run Business Process

src/main/java/org/spin/grpc/service/UserInterface.java, src/main/proto/business.proto
https://github.com/solop-develop/frontend-core/assets/20288327/20e94fe6-2b3e-439f-9f43-91c0e755f87c
=> fix: (Transcoding) Report Views.

src/main/java/org/spin/grpc/service/Dashboarding.java, src/main/java/org/spin/grpc/service/UserInterface.java
Add record count on list services.
=> fix: (Transcoding) Record count on services.

src/main/java/org/spin/grpc/service/Dictionary.java, src/main/proto/dictionary.proto
- Add `key columns` on Tab by Table.
- Add `field key` on Smart Browse.
=> feat: (Transcoding) Tab and Smart Browse with keys definition.

src/main/java/org/spin/base/util/ConvertUtil.java, src/main/java/org/spin/grpc/service/CoreFunctionality.java, src/main/java/org/spin/grpc/service/PointOfSalesForm.java, src/main/java/org/spin/pos/service/POSLogic.java, src/main/java/org/spin/pos/util/POSConvertUtil.java, src/main/proto/point_of_sales.proto
The point of sale form on the client side used the list business partner service, defined in `CoreFunctionality`, however there must be a specific one for the point of sale, since additional parameters are added.
In addition the `CoreFunctionality` list is corrected, when setting the phone number, it could generate a sql error when duplicating the `AND`.
=> feat: (Transcoding) POS List Customers.

build.gradle, src/main/java/org/spin/grpc/service/PointOfSalesForm.java, src/main/java/org/spin/pos/util/POSConvertUtil.java
- Update `adempiere-grpc-tools` to 1.0.8.
- Change deprecated method `getBigDecimalFromDecimal` to `getBigDecimalFromValue`.
- Fix list orders.
- fix Update order.
=> feat: (Transcoding) POS Changes.

src/main/java/org/spin/base/util/ConvertUtil.java, src/main/java/org/spin/grpc/service/PointOfSalesForm.java, src/main/java/org/spin/pos/service/POSLogic.java, src/main/java/org/spin/pos/service/order/OrderUtil.java, src/main/proto/point_of_sales.proto
- Order grand total converted.
- Order Line total amt converted.
- Order line total amt with tax converted.
=> feat: (Transcoding) POS add amt converted.

.github/workflows/publish.yml, docker/envoy_template.yaml, docker/grpc_proxy.Dockerfile, docker/start_proxy.sh
Add docker image to envoy proxy.
=> feat: (Transcoding) Envoy docker image.

src/main/proto/workflow.proto
Change http path to:
- Get Document Actions.
- Get Document Statuses.
=> fix: (Transcoding) Http API Document Actions/Statuses.

src/main/java/org/spin/base/util/ContextManager.java, src/main/java/org/spin/grpc/service/CoreFunctionality.java, src/main/java/org/spin/grpc/service/Security.java, src/main/java/org/spin/server/AllInOneServices.java, src/main/proto/core_functionality.proto, src/main/proto/security.proto
Reundant services and definitions from `CoreFunctionality` to `Security`.
=> feat: (Transcoding) Add list `Languages`, `Organizations`, `Warehouses` to security service.

README.es.md, README.md, docker-compose/.env, docker/alpine.Dockerfile, docker/focal.Dockerfile, docker/grpc_proxy.Dockerfile, resources/standalone.yaml, src/main/java/org/spin/base/util/Services.java, src/main/java/org/spin/grpc/service/field/location_address/LocationAddress.java, src/main/java/org/spin/grpc/service/field/location_address/LocationAddressConvertUtil.java, src/main/java/org/spin/grpc/service/field/location_address/LocationAddressLogic.java, src/main/java/org/spin/server/AllInOneServices.java, src/main/proto/location_address.proto
Add services
- ListCountries
- GetCountry
- ListRegions
- ListCities
- GetAddress
- CreateAddress
- UpdateAddress
=> feat: `Location Address` field services.

src/main/java/org/spin/grpc/service/field/location_address/LocationAddressConvertUtil.java, src/main/proto/location_address.proto
=> add `Display Value` on Location Address.

.github/workflows/publish.yml, .vscode/settings.json, docker/start.sh, docker/start_grpc_proxy.sh, resources/envoy.yaml
Add delivery to envoy proxy image
=> feat: Generate envoy proxy image.

src/main/java/org/spin/grpc/service/form/ExpressMovement.java
=> fix: `Express Movement` form list warehouses.

src/main/java/org/spin/grpc/service/Dashboarding.java, src/main/proto/dashboarding.proto
Add table name on `Pending Document` definition to icons:
=> feat: Add table name on `Pending Document`.

src/main/java/org/spin/grpc/service/PointOfSalesForm.java, src/main/java/org/spin/pos/util/POSConvertUtil.java, src/main/proto/point_of_sales.proto
- Create Customer.
- Update Customer.
- Create Customer Location.
- Update Customer Location.
fixes https://github.com/solop-develop/frontend-core/issues/1612
=> fix: POS Create/Update customer location.

src/main/java/org/spin/base/util/PreferenceUtil.java, src/main/java/org/spin/grpc/service/Security.java
https://github.com/solop-develop/adempiere-grpc-server/assets/20288327/8970966f-ea7d-4fc1-998f-9d66ab891860
fixes https://github.com/solop-develop/frontend-core/issues/1613
=> feat: Load last session preferences on login.

src/main/java/org/spin/grpc/service/LogsInfo.java
fixes https://github.com/solop-develop/frontend-core/issues/1389
=> feat: `Created By`/`Updated By` on change logs.

src/main/java/org/spin/grpc/service/UserInterface.java, src/main/java/org/spin/grpc/service/dictionary/BrowseConverUtil.java, src/main/java/org/spin/grpc/service/dictionary/DictionaryConvertUtil.java, src/main/java/org/spin/grpc/service/dictionary/ProcessConvertUtil.java, src/main/java/org/spin/grpc/service/dictionary/WindowConvertUtil.java, src/main/proto/dictionary.proto
https://github.com/solop-develop/adempiere-grpc-server/assets/20288327/2e763d0e-43af-4200-baa8-6e918be4792a
fixes https://github.com/solop-develop/frontend-core/issues/1593
=> fix: Logics on Field/Parameters/Browse Field.

src/main/java/org/spin/grpc/service/IssueManagement.java
Error with pagination and record access.
=> fix: Issues with pagination and record access.

src/main/java/org/spin/grpc/service/form/bank_statement_match/BankStatementMatch.java, src/main/java/org/spin/grpc/service/form/bank_statement_match/BankStatementMatchConvertUtil.java, src/main/java/org/spin/grpc/service/form/bank_statement_match/BankStatementMatchServiceLogic.java, src/main/java/org/spin/grpc/service/form/bank_statement_match/BankStatementMatchUtil.java, src/main/java/org/spin/server/AllInOneServices.java
fixes https://github.com/solop-develop/frontend-core/issues/1296
=> fix: Automatic match on `Bank Statement Match` form.

src/main/java/org/spin/base/util/ConvertUtil.java, src/main/java/org/spin/base/util/convert/ConvertCommon.java, src/main/java/org/spin/form/issue_management/IssueManagementConvertUtil.java, src/main/java/org/spin/grpc/service/BusinessData.java, src/main/java/org/spin/grpc/service/CoreFunctionality.java, src/main/java/org/spin/grpc/service/PointOfSalesForm.java, src/main/java/org/spin/grpc/service/ReportManagement.java, src/main/java/org/spin/log/LogsConvertUtil.java
When set `google.protobuf.Timestamp` and date value on data base is null generate:
```log
===========> IssueManagement.listIssues: null [20]
at org.spin.form.issue_management.IssueManagementConvertUtil.convertRequest(IssueManagementConvertUtil.java:278)
at org.spin.form.issue_management.IssueManagementConvertUtil.convertRequest(IssueManagementConvertUtil.java:257)
at org.spin.grpc.service.IssueManagement.lambda$4(IssueManagement.java:545)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.spin.grpc.service.IssueManagement.listIssues(IssueManagement.java:544)
at org.spin.grpc.service.IssueManagement.listIssues(IssueManagement.java:451)
at org.spin.backend.grpc.issue_management.IssueManagementGrpc$MethodHandlers.invoke(IssueManagementGrpc.java …
```
=> fix: `Null Pointer Exception` when date is null.

docker/grpc_proxy.Dockerfile
```log
grpc.proxy             | sh: 0: Can't open start.sh
grpc.proxy exited with code 127
```
=> fix: Start grpc proxy.

src/main/java/org/spin/base/util/RecordUtil.java, src/main/java/org/spin/form/issue_management/IssueManagementConvertUtil.java, src/main/java/org/spin/grpc/logic/RecordManagementServiceLogic.java, src/main/java/org/spin/grpc/service/BusinessData.java, src/main/java/org/spin/grpc/service/RecordManagement.java, src/main/java/org/spin/grpc/service/UserInterface.java, src/main/proto/base_data_type.proto, src/main/proto/business.proto, src/main/proto/record_management.proto, src/main/proto/user_interface.proto
https://github.com/solop-develop/adempiere-grpc-server/assets/20288327/2ca53735-c748-4eb9-aae3-21bd11602742
fixes https://github.com/solop-develop/frontend-core/issues/1606
=> fix: Record References on window.

docker-compose/.env, docker-compose/docker-compose.yml, docker/grpc_proxy.Dockerfile, docker/start_grpc_proxy.sh
=> feat: Start gRPC-Envoy-Proxy.

src/main/java/org/spin/grpc/service/FileManagement.java, src/main/java/org/spin/server/AllInOneServices.java, src/main/proto/file_management.proto
```bash
curl --location --request GET 'http://192.168.5.101:8080/api/file-management/resources/image/6a1734cd-b8b5-42d2-9015-35bb54c74b18-54648828.png' \
--header 'Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiIxMDAyMDAzIiwiQURfQ2xpZW50X0lEIjoxMSwiQURfT3JnX0lEIjo1MDAwMSwiQURfUm9sZV9JRCI6MTAyLCJBRF9Vc2VyX0lEIjoxMDEsIk1fV2FyZWhvdXNlX0lEIjo1MDAwMiwiQURfTGFuZ3VhZ2UiOiJlc19NWCIsImlhdCI6MTcwMDE1MTEzNSwiZXhwIjoxNzAwMjM3NTM1fQ.92zTp2LschWEVt-4GAIruwal1WbHW0_o1bYHGMX-7lc'
```
fixes https://github.com/solop-develop/frontend-core/issues/1631
=> feat: Load resource by file name.

src/main/java/org/spin/base/db/WhereClauseUtil.java
fixes https://github.com/solop-develop/frontend-core/issues/1629
=> fix: Windows search records with Advanced Query.

src/main/java/org/spin/grpc/service/Workflow.java
If document status `Void`, `Closed` or `Reversed`, must not allow to execute document action to change document status. So in addition to returning the empty list, it does not have to return document action by default.
```bash
curl --location --request GET 'http://0.0.0.0:8080/api/workflow/actions/C_Order/1000105?page_size=15' \
--header 'Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiIyMDE0OTk1IiwiQURfQ2xpZW50X0lEIjoxMDAwMDAxLCJBRF9PcmdfSUQiOjEwMDAwMDEsIkFEX1JvbGVfSUQiOjEwMDAwMDIsIkFEX1VzZXJfSUQiOjEwMDEyMTIsIk1fV2FyZWhvdXNlX0lEIjoxMDAwMDc1LCJBRF9MYW5ndWFnZSI6ImVzX01YIiwiaWF0IjoxNzAwNDg5OTU3LCJleHAiOjE3MDA1NzYzNTd9.LJldFSLZuZMobuB8zNwrbrnmk4PAFJwtoS6D6R6NCPI'
```
```json
{
"record_count": "0",
"document_actions": [],
"default_document_action": {
"value": "CL",
"name": "Cerrar", …
```
=> fix: Workflow list document actions with `Void`/`Closed`/`Reversed` document status.

src/main/java/org/spin/base/db/ParameterUtil.java, src/main/java/org/spin/base/db/WhereClauseUtil.java, src/main/java/org/spin/base/query/Filter.java, src/main/java/org/spin/base/query/FilterManager.java, src/main/java/org/spin/base/util/ContextManager.java
https://github.com/solop-develop/adempiere-grpc-server/assets/20288327/e123313d-2c71-408a-8871-4d7c5d8a8705
fixes https://github.com/solop-develop/frontend-core/issues/1603
=> fix: Smart Browse with filter date values.

src/main/java/org/spin/grpc/service/PaymentPrintExport.java, src/main/proto/payment_print_export.proto
Change end points with mandatory field on path.
related issue https://github.com/solop-develop/frontend-core/issues/1653
=> fix: `Payment Print/Export` form.

src/main/java/org/spin/grpc/service/form/payroll_action_notice/PayrollActionNotice.java, src/main/java/org/spin/grpc/service/form/payroll_action_notice/PayrollActionNoticeUtil.java, src/main/java/org/spin/server/AllInOneServices.java, src/main/proto/payroll_action_notice.proto
=> feat: `Action Payroll Notice` form

src/main/java/org/spin/grpc/service/UserCustomization.java, src/main/java/org/spin/grpc/service/UserInterface.java, src/main/proto/user_customization.proto
=> fix: User Customization end points.

src/main/java/org/spin/grpc/service/FileManagement.java
fixes https://github.com/solop-develop/frontend-core/issues/1666
=> fix: Delete attachment resource with `Resource Name`.

src/main/java/org/spin/base/util/ConvertUtil.java, src/main/java/org/spin/base/util/RecordUtil.java, src/main/java/org/spin/grpc/service/GeneralLedger.java, src/main/java/org/spin/grpc/service/UserInterface.java, src/main/proto/general_ledger.proto
```bash
curl --location --request GET 'http://127.0.0.1:8080/api/general-ledger/accounts/schemas/101/elements' \
--header 'Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiIxMDAyMjE4IiwiQURfQ2xpZW50X0lEIjoxMSwiQURfT3JnX0lEIjo1MDAwMSwiQURfUm9sZV9JRCI6MTAyLCJBRF9Vc2VyX0lEIjoxMDEsIk1fV2FyZWhvdXNlX0lEIjo1MDAwMiwiQURfTGFuZ3VhZ2UiOiJlc19NWCIsImlhdCI6MTcwMDg2MDU4OSwiZXhwIjoxNzAwOTQ2OTg5fQ.y1f1tU0NUGpUhxgVeR4JralnqLv5tZ6HH7YZKA8c8xI'
```
```json
{
"record_count": "8",
"accouting_elements": [
{
"element_type": "",
"column_name": "Combination",
"name": "Combinación",
"is_mandatory": false,
"is_balanced": false,
"sequece": 0,
"context_column_names": [],
"display_type": 14,
"field_id": 1437
},
{
"element_type": "OO",
"column_name": "AD_Org_ID",
"name": "Organización",
"is_mandatory": true, …
```
=> feat: Accouting elements by accouting schema.

build.gradle, src/main/java/org/spin/base/util/RecordUtil.java, src/main/java/org/spin/grpc/service/BusinessData.java, src/main/java/org/spin/grpc/service/UserInterface.java
```json
{
"id": 50001,
"table_name": "M_Product",
"values": {
"M_Product_ID": 50001,
"AD_Client_ID": 11,
"AD_Org_ID": 0,
"IsActive": true,
"Created": {
"type": "date",
"value": "2008-09-22 01:51:17"
},
"CreatedBy": 100,
"Updated": {
"type": "date",
"value": "2019-05-03 10:40:01"
},
"UpdatedBy": 0,
"Value": "PFrontLeg",
"Name": "Assembly Front Leg",
"C_UOM_ID": 100,
"IsSummary": false,
"IsStocked": false,
"IsPurchased": false,
"IsSold": false,
"IsBOM": true,
"IsInvoicePrintDetails": false,
"IsPickListPrintDetails": false,
"IsVerified": true,
"M_Product_Category_ID": 50000,
"Volume": {
"type": "decimal",
"value": "0.00"
},
"Weight": {
"type": "decimal",
"value": "0.00"
},
"ShelfWidth": 0,
"ShelfHeight": {
"type": "decimal",
"value": "0.00"
},
"ShelfDepth": 0,
"UnitsPerPallet": {
"type": …
```
=> fix: Entity with null values.

src/main/java/org/spin/form/issue_management/IssueManagementConvertUtil.java, src/main/java/org/spin/grpc/service/IssueManagement.java, src/main/proto/issue_management.proto
- List Status Categories.
- List Categories.
- List Groups.
- List Business Partners.
- List Projects.
=> feat: Issues as task management.

src/main/java/org/spin/grpc/service/IssueManagement.java
fixes https://github.com/solop-develop/frontend-core/issues/1696
=> fix: List Issues Priorities.

build.gradle, src/main/java/org/spin/base/util/RecordUtil.java, src/main/java/org/spin/grpc/service/BusinessData.java, src/main/java/org/spin/grpc/service/UserInterface.java
```json
{
"id": 50001,
"table_name": "M_Product",
"values": {
"M_Product_ID": 50001,
"AD_Client_ID": 11,
"AD_Org_ID": 0,
"IsActive": true,
"UpdatedBy": 0,
"Value": "PFrontLeg",
"Name": "Assembly Front Leg",
"C_UOM_ID": 100,
"Processing": "N",
"ProductType": "I",
"UUID": "9be3a0a6-6368-11e9-b849-00ff97344bad",
"DisplayColumn_AD_Client_ID": "GardenWorld",
"DisplayColumn_AD_Org_ID": "*"
}
}
```
```json
{
"id": 50001,
"table_name": "M_Product",
"values": {
"M_Product_ID": 50001,
"AD_Client_ID": 11,
"AD_Org_ID": 0,
"IsActive": true,
"UpdatedBy": 0,
"Value": "PFrontLeg",
"Name": "Assembly Front Leg",
"C_UOM_ID": 100,
"Processing": "N",
"ProductType": "I",
"UUID": "9be3a0a6-6368-11e9-b849-00ff97344bad",
"DisplayColumn_M_Product_Category_ID": "Assembly", …
```
=> fix: Display value as null.

src/main/java/org/spin/base/util/ReferenceUtil.java, src/main/java/org/spin/form/issue_management/IssueManagementConvertUtil.java, src/main/java/org/spin/grpc/service/IssueManagement.java, src/main/proto/issue_management.proto
related issue https://github.com/solop-develop/frontend-core/issues/1681
=> feat: Issue form add task status.

src/main/java/org/spin/grpc/service/NoticeManagement.java, src/main/proto/notice_management.proto
fixes https://github.com/solop-develop/frontend-core/issues/1683
=> feat: Delete notices.

src/main/java/org/spin/grpc/service/Dashboarding.java, src/main/proto/dashboarding.proto
fixes https://github.com/solop-develop/frontend-core/issues/1670
=> fix: Window chart and window metrics.

src/main/java/org/spin/grpc/service/Dashboarding.java, src/main/java/org/spin/grpc/service/LogsInfo.java, src/main/java/org/spin/log/LogsServiceLogic.java, src/main/java/org/spin/server/AllInOneServices.java, src/main/proto/logs.proto
```bash
curl 'http://0.0.0.0:8080/api/logs/user-activities?date=2023-06-05T04:00:00.000Z' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:120.0) Gecko/20100101 Firefox/120.0' -H 'Accept: application/json, text/plain, */*' -H 'Accept-Language: es-MX,es;q=0.8,en-US;q=0.5,en;q=0.3' -H 'Accept-Encoding: gzip, deflate' -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiIxMDAyMjQ5IiwiQURfQ2xpZW50X0lEIjoxMSwiQURfT3JnX0lEIjo1MDAwMSwiQURfUm9sZV9JRCI6MTAyLCJBRF9Vc2VyX0lEIjoxMDEsIk1fV2FyZWhvdXNlX0lEIjo1MDAwMiwiQURfTGFuZ3VhZ2UiOiJlc19NWCIsImlhdCI6MTcwMTc0NTY3MiwiZXhwIjoxNzAxODMyMDcyfQ.lNIVTZQJRoynNU3fPHDzTRGqpD2zvdYbK8YbrBDTGZY' -H 'Origin: http://0.0.0.0:9527' -H 'Connection: keep-alive' -H 'Referer: http://0.0.0.0:9527/' -H 'Pragma: no-cache' -H 'Cache-Control: no-cache'
```
```json
{ …
```
=> feat: User Activities with notice.

src/main/java/org/spin/grpc/service/IssueManagement.java, src/main/proto/issue_management.proto
fixes https://github.com/solop-develop/frontend-core/issues/1681
=> feat: Issues and My Issues form (as Request and Request All).

src/main/java/org/spin/base/db/WhereClauseUtil.java
https://github.com/solop-develop/adempiere-grpc-server/assets/20288327/f02ddea0-7338-4c7b-828e-5b38679f2172
```log
===========> UserInterface.listTabEntities: org.postgresql.util.PSQLException: ERROR: function upper(timestamp without time zone) does not exist
Hint: No function matches the given name and argument types. You might need to add explicit type casts.
Position: 6242, SQL=SELECT COUNT(*)  FROM C_Order AS C_Order LEFT JOIN C_DocType AS C_DocTypeTarget_ID_C_DocType ON(C_DocTypeTarget_ID_C_DocType.C_DocType_ID = C_Order.C_DocTypeTarget_ID) LEFT JOIN C_DocType_Trl AS C_DocTypeTarget_ID_C_DocType_Trl ON(C_DocTypeTarget_ID_C_DocType_Trl.C_DocType_ID = C_DocTypeTarget_ID_C_DocType.C_DocType_ID AND C_DocTypeTarget_ID_C_DocType_Trl.AD_Language = 'es_MX') LEFT JOIN C_BPartner AS …
```
=> fix: Advanced query with date.

src/main/java/org/spin/form/issue_management/IssueManagementConvertUtil.java, src/main/proto/issue_management.proto
fixes https://github.com/solop-develop/frontend-core/issues/1492
fixes https://github.com/solop-develop/frontend-core/issues/1681
=> fix: Issue with is default flag on Request Type.

src/main/java/org/spin/base/util/ConvertUtil.java, src/main/java/org/spin/form/issue_management/IssueManagementConvertUtil.java, src/main/java/org/spin/grpc/service/Security.java
fixes https://github.com/solop-develop/frontend-core/issues/1712
=> fix: Context to user logo.

src/main/java/org/spin/grpc/service/FileManagement.java, src/main/proto/file_management.proto
fixes https://github.com/solop-develop/frontend-core/issues/1726
=> fix: Get Attachment Reference info.

src/main/java/org/spin/form/issue_management/IssueManagementConvertUtil.java, src/main/java/org/spin/grpc/service/IssueManagement.java
```json
{
"record_count": "9",
"records": [
{
"id": 1000008,
"value": "",
"name": "Cierre Final",
"sequence": 80,
"is_default": false
},
{
"id": 1000000,
"value": "",
"name": "Solicitada",
"sequence": 1,
"is_default": false
},
{
"id": 1000001,
"value": "",
"name": "En Curso",
"sequence": 2,
"is_default": false
},
{
"id": 1000002,
"value": "",
"name": "Completo",
"sequence": 30,
"is_default": false
},
{
"id": 1000003,
"value": "",
"name": "Aprobación Interna",
"sequence": 3,
"is_default": false
},
{
"id": 1000004,
"value": "",
"name": "En Cliente",
"sequence": 4,
"is_default": false
},
{
"id": 1000005,
"value": "",
"name": "Cambios Agencia",
"sequence": 5, …
```
=> fix: Issues Statuses, order by `IsDefault` and `SeqNo`.

src/main/java/org/spin/grpc/service/IssueManagement.java
fixes https://github.com/solop-develop/frontend-core/issues/1492
=> fix: Update issue with empty values.

src/main/java/org/spin/base/db/WhereClauseUtil.java, src/main/java/org/spin/base/util/RecordUtil.java, src/main/java/org/spin/base/workflow/WorkflowUtil.java, src/main/java/org/spin/form/import_file_loader/ImportFileLoaderServiceLogic.java, src/main/java/org/spin/grpc/service/BusinessData.java, src/main/java/org/spin/grpc/service/Dashboarding.java, src/main/java/org/spin/grpc/service/FileManagement.java, src/main/java/org/spin/grpc/service/GeneralLedger.java, src/main/java/org/spin/grpc/service/IssueManagement.java, src/main/java/org/spin/grpc/service/LogsInfo.java, src/main/java/org/spin/grpc/service/UserInterface.java, src/main/java/org/spin/grpc/service/Workflow.java, src/main/java/org/spin/grpc/service/dictionary/DictionaryServiceLogic.java
Reduce logic on a method to validate and get table by table name.
=> feat: Reduce duplicated logic on validate table.

src/main/java/org/spin/grpc/service/PointOfSalesForm.java, src/main/proto/point_of_sales.proto
https://github.com/solop-develop/adempiere-grpc-server/assets/20288327/5ebaa9cd-9239-4831-9f52-99396ddabb02
https://github.com/solop-develop/adempiere-grpc-server/assets/20288327/4e23d7a3-1433-4094-bf1f-a46511913388
fixes https://github.com/solop-develop/frontend-core/issues/1789
=> fix: POS Create order with assigned sales representative.

src/main/java/org/spin/grpc/service/GeneralLedger.java, src/main/java/org/spin/grpc/service/Security.java, src/main/proto/security.proto
fixes https://github.com/solop-develop/frontend-core/issues/1790
=> fix: Accouting elements without role access.

build.gradle
This dependencies are used on `adempiere-grpc-utils`.
=> feat: Remove unused JWT dependencies.

src/main/java/org/spin/grpc/service/Security.java, src/main/proto/notice_management.proto, src/main/proto/report_management.proto, src/main/proto/security.proto
```json
[
{
"id": 487,
"uuid": "8e525846-fb40-11e8-a479-7a0060f0aa01",
"parent_id": 367,
"sequence": "00005",
"name": "Reinicia Contraseña",
"description": "Reinicia contraseñas para el usuario",
"is_active": true,
"is_summary": false,
"is_sales_transaction": false,
"is_read_only": false,
"action": "P",
"process": {
"id": 288,
"uuid": "a42b14e6-fb40-11e8-a479-7a0060f0aa01",
"name": "Reinicia Contraseña",
"description": "Reinicia contraseñas para el usuario",
"help": "Puede cambiar la contraseña del usuario y la configuración del correo electrónico. No necesita conocer la contraseña o introducirla si es Administrador."
},
"children": []
},
{
"id": 150,
"uuid": "8e5191f4-fb40-11e8-a479-7a0060f0aa01",
"parent_id": 367,
"sequence": "00006",
"name": "Rol",
"description": "Mantener …
```
=> feat: Change menu structure.

src/main/java/org/spin/grpc/service/form/trial_balance_drillable/TrialBalanceDrillable.java, src/main/java/org/spin/grpc/service/form/trial_balance_drillable/TrialBalanceDrillableServiceLogic.java, src/main/proto/trial_balance_drillable.proto
- List Organizations
- List Budgets
- List User 1
- List Periods
- List Accouting Keys
- List Report Cubes
=> feat: `Trial Balance` form query services

src/main/java/org/spin/grpc/service/UserInterface.java, src/main/java/org/spin/grpc/service/form/trial_balance_drillable/TrialBalanceDrillableServiceLogic.java
https://github.com/solop-develop/frontend-core/assets/20288327/ace49887-1b74-48d7-8211-cc44b673127a
https://github.com/solop-develop/frontend-core/assets/20288327/9e90ac62-21d8-452d-a3a8-4c7043f7f219
fixes https://github.com/solop-develop/frontend-core/issues/1817
=> fix: Smart Browse default vale with sales representative.

src/main/java/org/spin/grpc/service/dictionary/BrowseConverUtil.java, src/main/java/org/spin/grpc/service/dictionary/Dictionary.java, src/main/java/org/spin/grpc/service/dictionary/DictionaryConvertUtil.java, src/main/java/org/spin/grpc/service/dictionary/ProcessConvertUtil.java, src/main/java/org/spin/grpc/service/dictionary/WindowConvertUtil.java
fixes https://github.com/solop-develop/frontend-core/issues/1751
=> fix: Translated dictionary entities.

src/main/java/org/spin/base/db/WhereClauseUtil.java
https://github.com/solop-develop/frontend-core/assets/20288327/61fb70c3-cefe-43e2-94bf-9486abbebc06
fixes https://github.com/solop-develop/frontend-core/issues/1823
=> fix: Advanced query with multiple values list.

src/main/java/org/spin/base/util/RecordUtil.java, src/main/java/org/spin/grpc/service/BusinessData.java
Improve validation to delele record with zero (0) id value.
=> feat: Improve delete record.

src/main/java/org/spin/grpc/service/Dashboarding.java, src/main/proto/dashboarding.proto
fixes https://github.com/solop-develop/frontend-core/issues/976
=> feat: Portlet measures on metrics.

src/main/java/org/spin/log/LogsConvertUtil.java
fixes https://github.com/solop-develop/frontend-core/issues/1752
fixes https://github.com/solop-develop/frontend-core/issues/1753
=> fix: Log same time and different events.

src/main/java/org/spin/grpc/service/UserInterface.java
https://github.com/solop-develop/adempiere-grpc-server/assets/20288327/cb902105-7597-41c3-882c-dd008397fabf
https://github.com/solop-develop/adempiere-grpc-server/assets/20288327/ffad86f9-321f-4da0-b5f0-a039c108b1e1
fixes https://github.com/solop-develop/frontend-core/issues/1842
=> fix: Default value with `EntityType` column name and `Table` display type.

src/main/java/org/spin/grpc/service/LogsInfo.java, src/main/java/org/spin/log/LogsConvertUtil.java, src/main/java/org/spin/log/LogsServiceLogic.java
fixes https://github.com/solop-develop/frontend-core/issues/1752
fixes https://github.com/solop-develop/frontend-core/issues/1753
=> fix: Record log group on delete event type.

.project, build.gradle
Install dependencies from maven local.
=> feat: Install local dependencies.

src/main/java/org/spin/grpc/service/UserInterface.java, src/main/java/org/spin/grpc/service/ui/UserInterfaceConvertUtil.java, src/main/java/org/spin/grpc/service/ui/UserInterfaceLogic.java
https://github.com/solop-develop/adempiere-grpc-server/assets/20288327/a77b5d7e-1a0c-4e01-8688-6def24d2e0b7
fixes https://github.com/solop-develop/frontend-core/issues/686
=> fix: List records tree tab.

src/main/java/org/spin/base/query/Filter.java, src/main/java/org/spin/base/query/FilterManager.java, src/main/java/org/spin/base/query/Order.java, src/main/java/org/spin/base/query/SortingManager.java, src/main/java/org/spin/dashboarding/DashboardingConvertUtil.java, src/main/java/org/spin/grpc/service/Dashboarding.java
https://github.com/solop-develop/frontend-core/assets/45974454/49db3608-f1c3-446e-b4b6-13372a9fcd27
fixes https://github.com/solop-develop/frontend-core/issues/959
=> fix: Filters on window dashboards.

src/main/java/org/spin/base/db/QueryUtil.java, src/main/java/org/spin/grpc/service/UserInterface.java, src/main/java/org/spin/grpc/service/dictionary/WindowConvertUtil.java
fixes https://github.com/solop-develop/frontend-core/issues/1853
=> fix: Load `Button` as `List` or `Table` default value.

build.gradle, src/main/java/org/spin/grpc/service/Dashboarding.java
```bash
curl --location --request GET 'http://0.0.0.0:8080/api/dashboard/dashboards/1000033/metrics' \
--header 'Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiIyMDE3NDQxIiwiQURfQ2xpZW50X0lEIjoxMDAwMDAxLCJBRF9PcmdfSUQiOjEwMDAwMDQsIkFEX1JvbGVfSUQiOjEwMDAwMjMsIkFEX1VzZXJfSUQiOjEwMDEzOTgsIk1fV2FyZWhvdXNlX0lEIjoxMDAwMDcxLCJBRF9MYW5ndWFnZSI6ImVzX01YIiwiaWF0IjoxNzA1NjgwNDA1LCJleHAiOjE3MDU3NjY4MDV9.VoVDIUQEkfBUzodykZHVsWUF4Qgqf41q7fxnu3xTbaY'
```
```json
{
"id": 0,
"name": "",
"x_axis_label": "",
"y_axis_label": "",
"measure_target": "100000",
"measure_actual": "308173816.76",
"performance_goal": "3081.738168",
"color_schemas": [
{
"name": "",
"color": "#00FF00",
"percent": "50"
},
{
"name": "",
"color": "#FFFF00",
"percent": "100"
},
{
"name": "",
"color": "#FF0000", …
```
=> fix: Chart overwrite data series.

build.gradle
The values on columns Col_X always null, the value is a `ColumnSQL`
```json
{
"id": 1000023,
"table_name": "UY_InvoiceImport",
"values": {
"AD_Client_ID": 1000001,
"AD_Org_ID": 1000005,
"Col_10": null,
"Col_11": null,
"Created": {
"type": "date",
"value": "2023-09-01 06:00:05"
},
"CreatedBy": 1001211,
"Description": null,
"DocumentNo": "1000007",
"IsActive": true,
"Name": "Enero 2023",
"Updated": {
"type": "date",
"value": "2023-09-01 06:00:05"
},
"UpdatedBy": 1001211,
"UUID": "af53f5f7-304f-4e7c-9e84-b72c410bf659",
"UY_InvoiceImport_ID": 1000023,
"Col_12": null,
"DisplayColumn_AD_Org_ID": "Colegio",
"Col_1": null,
"Col_2": null,
"Col_3": null,
"Col_4": null,
"Col_5": null,
"Col_6": null
}
}
```
```json
{
"id": 1000023,
"table_name": "UY_InvoiceImport",
"values": {
"AD_Client_ID": …
```
=> fix: Value `Long`, `Float`, `Double` to `Integer`.

src/main/java/org/spin/base/util/WorkflowUtil.java, src/main/proto/workflow.proto
fixes https://github.com/solop-develop/frontend-core/issues/1800
=> feat: Workflow Ativities zoom to `IsSOTrx` window.

build.gradle, src/main/java/org/spin/grpc/service/UserInterface.java
https://github.com/solop-develop/frontend-core/assets/20288327/0e07e511-9b2b-4dc8-bfb2-ba0c63f227d9
fixes https://github.com/solop-develop/frontend-core/issues/1869
=> fix: Smart Browse search with range query criteria.

src/main/java/org/spin/grpc/service/form/issue_management/IssueManagementConvertUtil.java
fixes https://github.com/solop-develop/frontend-core/issues/1856
=> fix Issue comments feed log type.

src/main/java/org/spin/grpc/service/Security.java
fixes https://github.com/solop-develop/frontend-core/issues/1879
=> fix: Login with path values.

src/main/java/org/spin/grpc/service/FileManagement.java, src/main/proto/file_management.proto
- Add confirm attachment referenece with file size.
- Add flag to delete external file related to attachment referenece.
related issue https://github.com/solop-develop/frontend-core/issues/1238
=> feat: Confirm resource reference

src/main/java/org/spin/grpc/service/Dashboarding.java, src/main/proto/dashboarding.proto
fixes https://github.com/solop-develop/frontend-core/issues/977
=> fix: Dashboard peformance goal values.

build.gradle, src/main/java/org/spin/grpc/service/BusinessData.java, src/main/java/org/spin/grpc/service/ReportManagement.java
When send string date on parameter set null on process info as it expects a timestamp.
fixes https://github.com/solop-develop/adempiere-grpc-server/issues/683
=> fix: Cast correct parameter value by display type.

src/main/java/org/spin/grpc/service/UserInterface.java, src/main/proto/user_interface.proto
https://github.com/solop-develop/frontend-core/assets/20288327/80087afd-30f0-40f6-8f2d-9f9b273e9ad9
fixes https://github.com/solop-develop/frontend-core/issues/1685
=> fix: Lookups list inactive records.

src/main/java/org/spin/grpc/service/Security.java
```bash
curl 'http://0.0.0.0/api/security/organizations?role_id=1000017&page_size=100' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:122.0) Gecko/20100101 Firefox/122.0' -H 'Accept: application/json, text/plain, */*' -H 'Accept-Language: es-MX,es;q=0.8,en-US;q=0.5,en;q=0.3' -H 'Accept-Encoding: gzip, deflate' -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiIyMDE3ODUyIiwiQURfQ2xpZW50X0lEIjoxMDAwMDAxLCJBRF9PcmdfSUQiOjAsIkFEX1JvbGVfSUQiOjEwMDAwMTcsIkFEX1VzZXJfSUQiOjEwMDEyMTIsIk1fV2FyZWhvdXNlX0lEIjowLCJBRF9MYW5ndWFnZSI6ImVzX01YIiwiaWF0IjoxNzA4NDQ0ODYyLCJleHAiOjE3MDg1MzEyNjJ9.fVP-tjc6qgS54OQyUt8J5Ej92Fr4RVtLr54_2xGvVgk' -H 'Origin: http://0.0.0.0:9527' -H 'Connection: keep-alive' -H 'Referer: http://0.0.0.0:9527/' -H 'Pragma: no-cache' -H 'Cache-Control: no-cache'
```
Before this …
=> fix: No instance of the organization in asterisk.

src/main/java/org/spin/base/db/QueryUtil.java, src/main/java/org/spin/base/util/ReferenceInfo.java, src/main/java/org/spin/base/util/ReferenceUtil.java, src/main/java/org/spin/grpc/service/UserInterface.java
=> feat: Entity `DisplayColumn` on `ID` display type.

src/main/java/org/spin/grpc/service/field/business_partner/BusinessPartnerConvert.java, src/main/java/org/spin/grpc/service/field/business_partner/BusinessPartnerLogic.java, src/main/proto/business_partner.proto
fixes https://github.com/solop-develop/frontend-core/issues/1828
=> feat: Business Partner field `DisplayValue`.

resources/envoy.yaml, src/main/java/org/spin/grpc/service/field/business_partner/BusinessPartnerLogic.java
https://github.com/solop-develop/adempiere-grpc-server/assets/20288327/407b8170-10e0-4828-89ec-07fe55f535c5
fixes https://github.com/solop-develop/frontend-core/issues/1121
fixes https://github.com/solop-develop/frontend-core/issues/1828
fixes https://github.com/solop-develop/frontend-core/issues/1837
=> fix: `Search Value` on business partner field.

src/main/java/org/spin/grpc/service/Security.java, src/main/proto/security.proto
And add `uuid` values.
```bash
curl 'http://0.0.0.0/api/security/warehouses?organization_id=0&page_size=100' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:123.0) Gecko/20100101 Firefox/123.0' -H 'Accept: application/json, text/plain, */*' -H 'Accept-Language: es-MX,es;q=0.8,en-US;q=0.5,en;q=0.3' -H 'Accept-Encoding: gzip, deflate' -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiIyMDE3MjY0IiwiQURfQ2xpZW50X0lEIjoxMDAwMDAxLCJBRF9PcmdfSUQiOjAsIkFEX1JvbGVfSUQiOjEwMDAwMzIsIkFEX1VzZXJfSUQiOjEwMDEyMTIsIk1fV2FyZWhvdXNlX0lEIjowLCJBRF9MYW5ndWFnZSI6ImVzX01YIiwiaWF0IjoxNzA5MjE3OTQ5LCJleHAiOjE3MDkzMDQzNDl9.1Sx_MyiooQXyMmAj6AKWmQlI_SJEztn4mIXqRvVjmFI' -H 'Origin: http://0.0.0.0:9527' -H 'Connection: keep-alive' -H 'Referer: http://0.0.0.0:9527/' -H 'Pragma: no-cache' -H 'Cache-Control: …
```
=> fix: No instance of the `warehouse` in asterisk.

build.gradle, src/main/java/org/spin/base/util/ReferenceInfo.java, src/main/java/org/spin/grpc/service/field/product/ProductInfoConvert.java, src/main/java/org/spin/grpc/service/field/product/ProductInfoLogic.java, src/main/proto/product.proto
https://github.com/solop-develop/adempiere-grpc-server/assets/20288327/482a7dce-1f08-42b0-b660-1a82d1700fbc
fixes https://github.com/solop-develop/frontend-core/issues/1034
fixes https://github.com/solop-develop/frontend-core/issues/1587
=> feat: Field `Product` Search.

src/main/java/org/spin/base/db/QueryUtil.java, src/main/java/org/spin/base/util/ReferenceUtil.java
fixes https://github.com/solop-develop/frontend-core/issues/1987
=> fix: Smart Browse display column table records.

src/main/java/org/spin/dictionary/util/WindowUtil.java, src/main/java/org/spin/grpc/service/ReportManagement.java
fixes https://github.com/solop-develop/frontend-core/issues/1999
TODO: Add filter by ASP Level.
=> fix: Displayed process with ASP field displayed associated.

src/main/java/org/spin/grpc/service/UserInterface.java
https://github.com/solop-develop/adempiere-grpc-server/assets/20288327/2092ed04-6e8c-4e10-8ac4-1bd6517626d0
fixes https://github.com/solop-develop/frontend-core/issues/1122
=> fix: Payment callout `IsSOtrx`.

src/main/java/org/spin/base/util/AccessUtil.java, src/main/java/org/spin/dictionary/util/WindowUtil.java, src/main/java/org/spin/grpc/service/BusinessData.java, src/main/java/org/spin/grpc/service/ReportManagement.java, src/main/java/org/spin/grpc/service/UserCustomization.java, src/main/java/org/spin/grpc/service/dictionary/ProcessConvertUtil.java, src/main/java/org/spin/grpc/service/dictionary/WindowConvertUtil.java, src/main/proto/dictionary.proto
Add process on tab structure.
related issue https://github.com/solop-develop/frontend-core/issues/689
=> feat: Add process associated on tab.

src/main/java/org/spin/grpc/service/field/product/ProductInfo.java, src/main/java/org/spin/grpc/service/field/product/ProductInfoLogic.java, src/main/proto/product.proto
https://github.com/solop-develop/adempiere-grpc-server/assets/20288327/0a69de5e-3b30-4f7c-8e14-ec47051d12ec
fixes https://github.com/solop-develop/frontend-core/issues/1586
fixes https://github.com/solop-develop/frontend-core/issues/1034
=> feat: Get last price list version into `Product` search field.

src/main/java/org/spin/grpc/service/UserInterface.java
https://github.com/solop-develop/adempiere-grpc-server/assets/20288327/27c3e9ae-c28c-42a9-8413-16bba6f551db
fixes https://github.com/solop-develop/frontend-core/issues/2023
=> fix: List document types with `IsActive` flag.

build.gradle, src/main/java/org/spin/grpc/service/dictionary/BrowseConverUtil.java, src/main/java/org/spin/grpc/service/dictionary/DictionaryConvertUtil.java, src/main/java/org/spin/grpc/service/dictionary/ProcessConvertUtil.java, src/main/java/org/spin/grpc/service/dictionary/WindowConvertUtil.java, src/main/proto/dictionary.proto
- remove view_id
- change value to code.
- change window structure to `DictionaryEntity`.
- change process structure to `DictionaryEntity`.
- remove element_id.
- remove column_id.
- remove context_info.
- remove context_info.
- add window_id.
- remove element_id.
- remove column_id.
- inactive field_definition.
- change value to code.
- add form_id.
- add browse_id.
- add workflow_id.
- remove access_level
=> feat: MS Cache reduce unused properties.

build.gradle, docker/grpc_proxy.Dockerfile
- Update kafka-connector to 1.1.4.
- Update pos-improvements to 1.0.2.
- Update protobuf-java to 3.25.3.
- Update netty-handler to 4.1.107.
- Update com.google.protobuf plugin to 0.9.4.
- Update envoy proxy to 1.29.2.
=> feat: Update kafka connector to 1.1.4.

src/main/java/org/spin/base/db/QueryUtil.java, src/main/java/org/spin/base/util/ReferenceUtil.java
The subquery is multiple alias.
```sql
SELECT TO_CHAR(DateInvoiced, 'YYYY-MM-DD') 
FROM C_Invoice AS C_Invoice_C_Invoice_ID inv 
WHERE inv.C_Invoice_ID=C_Invoice.C_Invoice_ID
```
@no-autoclose
fixes https://github.com/solop-develop/frontend-core/issues/2013
=> fix: Query with subquery and table alias.

src/main/java/org/spin/dictionary/util/WindowUtil.java, src/main/java/org/spin/grpc/service/dictionary/BrowseConverUtil.java, src/main/java/org/spin/grpc/service/dictionary/DictionaryConvertUtil.java, src/main/java/org/spin/grpc/service/dictionary/ProcessConvertUtil.java, src/main/java/org/spin/grpc/service/dictionary/WindowConvertUtil.java, src/main/proto/dictionary.proto
related issue https://github.com/solop-develop/frontend-core/issues/1958
related issue https://github.com/solop-develop/frontend-core/issues/1965
related issue https://github.com/solop-develop/frontend-core/issues/2025
related issue https://github.com/solop-develop/frontend-core/issues/1996
related issue https://github.com/solop-develop/frontend-core/issues/2026
related issue https://github.com/solop-develop/frontend-core/issues/1995
related issue https://github.com/solop-develop/frontend-core/issues/1994
=> feat: Improve properties with optional flag.

src/main/java/org/spin/grpc/service/Security.java, src/main/proto/security.proto
related issue https://github.com/solop-develop/frontend-core/issues/1965
related issue https://github.com/solop-develop/frontend-core/issues/1994
=> feat: `Menu` as `OpenSearch` response.

src/main/java/org/spin/grpc/service/field/product/ProductInfoLogic.java
https://github.com/solop-develop/frontend-core/assets/20288327/9d500f4a-c5ff-4638-a887-5be0a638f09d
fixes https://github.com/solop-develop/frontend-core/issues/2021
=> fix: `Product` search some fixes.

build.gradle
Fix identifier on Browse.
related issue https://github.com/solop-develop/frontend-core/issues/2026
=> fix: Browser identifier.

build.gradle, src/main/java/org/spin/grpc/service/Security.java, src/main/proto/security.proto
change menu end-point to `security/menus`.
fixes https://github.com/solop-develop/frontend-core/issues/1994
=> feat: Change menu endpoint.

src/main/java/org/spin/form/import_file_loader/ImportFileLoaderServiceLogic.java, src/main/java/org/spin/grpc/service/GeneralLedger.java, src/main/java/org/spin/grpc/service/UserInterface.java, src/main/java/org/spin/grpc/service/form/PaymentAllocation.java, src/main/java/org/spin/grpc/service/form/bank_statement_match/BankStatementMatchServiceLogic.java, src/main/java/org/spin/grpc/service/form/match_po_receipt_invoice/MatchPOReceiptInvoice.java, src/main/java/org/spin/grpc/service/form/trial_balance_drillable/TrialBalanceDrillableServiceLogic.java, src/main/proto/bank_statement_match.proto, src/main/proto/base_data_type.proto, src/main/proto/general_ledger.proto, src/main/proto/import_file_loader.proto, src/main/proto/match_po_receipt_invoice.proto, src/main/proto/payment_allocation.proto, src/main/proto/payment_print_export.proto, src/main/proto/payroll_action_notice.proto, src/main/proto/product.proto, src/main/proto/trial_balance_drillable.proto
https://github.com/solop-develop/adempiere-grpc-server/assets/20288327/a9a3ba56-336a-496e-ac56-d6ce3b66cae8
fixes https://github.com/solop-develop/frontend-core/issues/2036
=> feat: Add flag to filter only active records.

src/main/java/org/spin/grpc/service/dictionary/WindowConvertUtil.java, src/main/proto/dictionary.proto
=> fix: Add table name on tab structure.

src/main/java/org/spin/grpc/service/Security.java
fixes https://github.com/solop-develop/frontend-core/issues/1994
=> fix: Menus without root element.

docker/envoy_template.yaml, resources/envoy.yaml
When timeout the response is:
```
upstream tiemeout
```
Or
```
stream tiemout
```
=> feat: Set envoy proxy tiemout.

src/main/java/org/spin/grpc/service/Security.java, src/main/java/org/spin/grpc/service/core_functionality/CoreFunctionalityConvert.java, src/main/java/org/spin/grpc/service/form/issue_management/IssueManagementConvertUtil.java
fixes https://github.com/solop-develop/frontend-core/issues/2022
=> fix: Change `ValidFileName` to `FileName`.

src/main/java/org/spin/grpc/service/Dashboarding.java
fixes https://github.com/solop-develop/frontend-core/issues/2096
=> fix: Dashboard content translation.

build.gradle
- feat: Add table_name on tab structure. by @EdwinBetanc0urt in https://github.com/adempiere/adempiere-kafka-connector/pull/9
- feat: Improve peformance migration. by @EdwinBetanc0urt in https://github.com/adempiere/adempiere-kafka-connector/pull/10
- feat: Update github actions. by @EdwinBetanc0urt in https://github.com/adempiere/adempiere-kafka-connector/pull/11
- feat: Add action_id and action_uuid on Menu structure. by @EdwinBetanc0urt in https://github.com/adempiere/adempiere-kafka-connector/pull/14
- feat: Reference ContextColumns on field. by @EdwinBetanc0urt in https://github.com/adempiere/adempiere-kafka-connector/pull/12
- fix: Resource leak consumer is never colsed. by @EdwinBetanc0urt in https://github.com/adempiere/adempiere-kafka-connector/pull/13
Full Changelog: …
=> feat: Update `adempiere-kafka-connector` to 1.1.6 version.

src/main/java/org/spin/grpc/service/form/issue_management/IssueManagement.java
https://github.com/solop-develop/adempiere-grpc-server/assets/20288327/458ead8d-3a41-40a8-8606-a1403163078f
fixes https://github.com/solop-develop/frontend-core/issues/2008
=> fix: Issue feed sorted by date.

src/main/java/org/spin/base/db/WhereClauseUtil.java, src/main/java/org/spin/grpc/logic/RecordManagementServiceLogic.java, src/main/java/org/spin/grpc/service/Dashboarding.java, src/main/java/org/spin/grpc/service/UserInterface.java, src/main/proto/dashboarding.proto
https://github.com/solop-develop/frontend-core/assets/45974454/a7c0f193-63ba-4bff-be06-a8c0ceb1aadd
fixes https://github.com/solop-develop/frontend-core/issues/1946
=> fix: Filter pending documents.

src/main/java/org/spin/base/util/ConvertUtil.java, src/main/java/org/spin/dictionary/util/WindowUtil.java, src/main/java/org/spin/grpc/service/PointOfSalesForm.java, src/main/java/org/spin/grpc/service/UserCustomization.java, src/main/java/org/spin/grpc/service/UserInterface.java, src/main/java/org/spin/grpc/service/Workflow.java, src/main/java/org/spin/pos/service/order/OrderManagement.java, src/main/java/org/spin/pos/service/order/ReturnSalesOrder.java, src/main/java/org/spin/pos/util/POSConvertUtil.java
```log
===========> UserInterface.updateBrowserEntity: java.util.NoSuchElementException: No Value Present  [244]
```
```json
{
"code": 13,
"message": "No value present",
"details": []
}
```
fixes https://github.com/solop-develop/frontend-core/issues/2126
=> fix: `java.util.NoSuchElementException: No value present`.

src/main/java/org/spin/base/util/RecordUtil.java, src/main/java/org/spin/grpc/service/UserInterface.java
```log
===========> UserInterface.getTabEntity: ERROR: column ad_clientinfo.ad_clientinfo_id does not exist
Position: 4907 [100]
org.postgresql.util.PSQLException: ERROR: column ad_clientinfo.ad_clientinfo_id does not exist
Position: 4907
at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2675)
at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2365)
at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:355)
at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:490)
at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:408)
at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:166)
at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedState …
```
=> fix: Edit record without own key column`AD_ClientInfo=AD_Client_ID`.

src/main/java/org/spin/grpc/service/UserInterface.java
with the parallelStream does not have the correct scope of the PO_Info, so in some threads it does not get it correctly and cannot obtain the index of the field. It is corrected by instantiating the column and evaluating if it is correctly, otherwise it does not exist in the table to be modified.
fixes https://github.com/solop-develop/frontend-core/issues/1294
fixes https://github.com/solop-develop/frontend-core/issues/2126
=> fix: Update entity with `parallelStream`.

src/main/java/org/spin/grpc/service/GeneralLedger.java, src/main/proto/general_ledger.proto
fixes https://github.com/solop-develop/frontend-core/issues/893
=> fix: Accouting combination field.

src/main/java/org/spin/grpc/service/dictionary/BrowseConverUtil.java, src/main/java/org/spin/grpc/service/dictionary/DictionaryConvertUtil.java, src/main/java/org/spin/grpc/service/dictionary/ProcessConvertUtil.java, src/main/java/org/spin/grpc/service/dictionary/WindowConvertUtil.java, src/main/proto/dictionary.proto
Change `container_id` to `parent_id`, `container_uuid` to `parent_uuid`, change `container_name` to `parent_name`.
As `OpenSearch Gateway RS`.
=> feat: Change container to parent on dependent field.

src/main/java/org/spin/grpc/service/UserInterface.java
Fix edit record on `Browse Field` with `IsReadOnly=true` or `IsActive=false`, the parent `Column` with `IsVirtualColumn=true` or `IsKey=true` or `IsUpdateable=false`.
=> fix: Edit browse entity on field read only.

build.gradle, src/main/java/org/spin/log/LogsConvertUtil.java
- adempiere-kafka-connector from 1.1.6 to 1.1.9 
- adempiere-grpc-utils from 1.3.6 to 1.3.7
=> feat: Update `adempiere-kafka-connector` and `adempiere-grpc-utils` libraries

build.gradle
- Add support to forms.
- Add export specific dictionary entity.
- Add export current dicionary entity.
fixes https://github.com/solop-develop/frontend-core/issues/2200
fixes https://github.com/solop-develop/frontend-core/issues/2204
fixes https://github.com/solop-develop/frontend-core/issues/2205
=> feat: Update `adempiere-kafka-connector` to `1.2.1`.

build.gradle
Add `IsParent` column into `context_columns` list.
fixes https://github.com/solop-develop/frontend-core/issues/2206
=> feat: Update `kafka-connector` to `1.2.2`.

src/main/java/org/spin/base/query/Filter.java
fixes https://github.com/solop-develop/frontend-core/issues/2211
=> fix: Key `Name` on filters.

src/main/java/org/spin/grpc/service/field/location_address/LocationAddressConvertUtil.java, src/main/java/org/spin/grpc/service/field/location_address/LocationAddressLogic.java
Add return coordinates values.
fixes https://github.com/solop-develop/frontend-core/issues/2169
fixes https://github.com/solop-develop/frontend-core/issues/838
=> fix: `Location` field return coordinantes.

build.gradle
- fix: IsParent column as Context Columns. by @EdwinBetanc0urt in https://github.com/adempiere/adempiere-kafka-connector/pull/26
- feat: Update org.apache.kafka:kafka_2.13 to 2.8.2. by @EdwinBetanc0urt in https://github.com/adempiere/adempiere-kafka-connector/pull/27
- fix: Export form associated. by @EdwinBetanc0urt in https://github.com/adempiere/adempiere-kafka-connector/pull/28
- feat: Add support to is_displayed_as_panel and is_displayed_as_table. by @EdwinBetanc0urt in https://github.com/adempiere/adempiere-kafka-connector/pull/29
- feat: Add IsParent flag on field. by @EdwinBetanc0urt in https://github.com/adempiere/adempiere-kafka-connector/pull/30
Full Changelog: https://github.com/adempiere/adempiere-kafka-connector/compare/1.2.1...1.2.4
=> feat: Update `kafka-connector` to `1.2.4`.

src/main/java/org/spin/grpc/service/form/ExpressMovement.java, src/main/java/org/spin/grpc/service/form/ExpressReceipt.java, src/main/java/org/spin/grpc/service/form/ExpressShipment.java
=> fix: Express forms revert parallel strem with context.

src/main/java/org/spin/grpc/service/field/invoice/InvoiceInfoConvert.java, src/main/proto/invoice.proto
=> feat: Add `Display Value` on invoice field.

build.gradle, docker/grpc_proxy.Dockerfile
fixes https://github.com/solop-develop/frontend-core/issues/2241
=> fix: Window `Browser` associated as button or process.

src/main/java/org/spin/base/db/WhereClauseUtil.java, src/main/java/org/spin/grpc/service/field/invoice/InvoiceInfoLogic.java
https://github.com/solop-develop/adempiere-grpc-server/assets/45974454/38b3d428-40b6-4121-a2eb-99504e6cdc77
=> Fix List Invoices Info Query

src/main/proto/invoice.proto
Add end-points to:
- table: `/field/invoices/table/{table_name}/{column_name}`.
- column: `/field/invoices/column/{column_id}`.
- field: `/field/invoices/field/{field_id}`.
- parameter `/field/invoices/parameter/{process_parameter_id}`.
- query criteria `/field/invoices/query-criteria/{browse_field_id}`.
=> fix: `Invoice Field` end-points.

src/main/java/org/spin/base/interim/ContextTemporaryWorkaround.java, src/main/java/org/spin/base/util/ConvertUtil.java, src/main/java/org/spin/base/util/RecordUtil.java, src/main/java/org/spin/grpc/service/UserInterface.java
* `C_Payment`
* `C_Order`.
* `C_OrderLine`
fixes https://github.com/solop-develop/frontend-core/issues/2217
fixes https://github.com/solop-develop/frontend-core/issues/2156
=> fix: Add context (emulating callouts) as unknow columns.

src/main/java/org/spin/server/AllInOneServices.java, src/main/java/org/spin/server/ServerReportProvider.java
When generated a report with jasper generated `Null Pointer Exception`.
https://github.com/adempiere/adempiere/blob/develop/JasperReports/src/org/compiere/jr/report/ReportStarter.java#L670
=> fix: Report provider to jasper.

src/main/java/org/spin/grpc/service/field/invoice/InvoiceInfoConvert.java
=> Fix: Get Document Status Name (`DocStatus`)

src/main/java/org/spin/grpc/service/GeneralLedger.java
fixes https://github.com/solop-develop/frontend-core/issues/2164
=> fix: Accouting info validate record id and table.

build.gradle
fixes https://github.com/solop-develop/frontend-core/issues/2274
=> fix: Index name with all values.

src/main/java/org/spin/grpc/service/UserInterface.java
`ERROR: insert or update on table "ad_user" violates foreign key constraint "cgreeting_aduser" Detail: Key (c_greeting_id)=(0) is not present in table "c_greeting".
`
fixes https://github.com/solop-develop/frontend-core/issues/2126
=> Fix: Validate values in Null

src/main/java/org/spin/grpc/service/dictionary/BrowseConverUtil.java, src/main/java/org/spin/grpc/service/dictionary/DictionaryConvertUtil.java, src/main/java/org/spin/grpc/service/dictionary/ProcessConvertUtil.java, src/main/java/org/spin/grpc/service/dictionary/WindowConvertUtil.java
When each list and a element is null generated `Null Pointer Exception`.
=> fix: NPE when object is null.

build.gradle
```json
{
"context_column_names": [
"C_PaySelection_ID"
]
}
```
```json
{
"context_column_names": [
"PayDate",
"INV_IsSOTrx",
"C_Currency_ID",
"C_PaySelection_ID",
"PS_C_Currency_ID"
]
}
```
fixes https://github.com/solop-develop/frontend-core/issues/2294
=> fix: Context columns on `Smart Browse`.

src/main/java/org/spin/grpc/service/UserInterface.java
https://github.com/solop-develop/adempiere-grpc-server/assets/20288327/84055f5d-02a6-4ffc-a20d-8321731b6284
fixes https://github.com/solop-develop/frontend-core/issues/2324
=> fix: Callout on tab line.

build.gradle
- Change on menu.
- Change on process.
=> fix: Change `Browse` to `Browser`.

build.gradle
feat: Add filter record ColumnName to Sort Tab. by @EdwinBetanc0urt in https://github.com/adempiere/adempiere-kafka-connector/pull/36
Add support to ID as uuid
=> feat: Update kafka connector to 1.3.1.

src/main/java/org/spin/grpc/service/UserInterface.java
https://github.com/solop-develop/adempiere-grpc-server/assets/20288327/e054cbc5-b50e-491c-8182-8ef7d6ae6e2e
https://github.com/solop-develop/adempiere-grpc-server/assets/20288327/29b64776-1175-486c-8884-547c11bfaa4c
fixes https://github.com/solop-develop/frontend-core/issues/2397
=> fix: Default value with spaces.

build.gradle, src/main/java/org/spin/dictionary/util/BrowserUtil.java, src/main/java/org/spin/grpc/service/BusinessData.java
https://github.com/solop-develop/frontend-core/assets/20288327/69a33dbb-db22-4144-80d3-14ca05f34571
```bash
curl 'http://spdev01.solopapp.com:24610/api/business-data/process/2000189/smart-browse/2000038' \
-X POST \
-H 'Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiIyMDIwNzI1IiwiQURfQ2xpZW50X0lEIjoxMDAwMDAxLCJBRF9PcmdfSUQiOjEwMDAwMDIsIkFEX1JvbGVfSUQiOjEwMDAwMDIsIkFEX1VzZXJfSUQiOjEwMDEyMTIsIk1fV2FyZWhvdXNlX0lEIjoxMDAwMDA0LCJBRF9MYW5ndWFnZSI6ImVzX01YIiwiaWF0IjoxNzE5NTE4ODE5LCJleHAiOjE3MTk2MDUyMTl9.qRF54QqKTARdpWiMeHOCtJpQrEADBFkWX6XX480roVY' \
--data-raw '{"record_id":1007787,"parameters":{"C_ProjectPhase_ID":1014318},"selections":[{"selectionId":1004825,"values":{"P_M_Product_ID":1004825,"P_QtyEnte …
```
=> fix: Smart Browse process selection with decimal values.

src/main/java/org/spin/grpc/service/UserInterface.java
https://github.com/solop-develop/frontend-core/assets/20288327/33449061-c1cc-4477-a70a-b6ba2f659d74
fixes https://github.com/solop-develop/frontend-core/issues/1074
=> fix: Window save sort tab.

src/main/java/org/spin/grpc/service/UserInterface.java
https://github.com/user-attachments/assets/e34877b1-9dbb-4a7c-86d2-d27ef60fd914
fixes https://github.com/solop-develop/frontend-core/issues/2419
=> fix: Save new with zero value.

src/main/java/org/spin/dictionary/util/WindowUtil.java, src/main/java/org/spin/grpc/service/UserInterface.java
https://github.com/user-attachments/assets/b2c388b1-e79a-46be-9f99-84987092857f
https://github.com/user-attachments/assets/05078fe7-e5bf-48ca-b674-58e6886b47ab
fixes https://github.com/solop-develop/frontend-core/issues/2438
=> fix: Callout cast string to date.

src/main/java/org/compiere/model/POAdapter.java, src/main/java/org/spin/grpc/service/UserInterface.java, src/main/java/org/spin/grpc/service/dictionary/BrowseConverUtil.java
https://github.com/user-attachments/assets/fa3f9c99-3a11-4a97-859e-8c09653d8844
fixes https://github.com/solop-develop/frontend-core/issues/2419
=> fix: Edit zero value on record.

src/main/java/org/spin/grpc/service/form/PaymentAllocation.java
https://github.com/user-attachments/assets/bbdd2677-e090-467e-afef-e1a4dda7defd
fixes https://github.com/solop-develop/frontend-core/issues/2433
=> fix: Payment Allocation form, with 0 organizaiton.

src/main/java/org/spin/grpc/service/field/invoice/InvoiceInfoLogic.java, src/main/java/org/spin/grpc/service/field/invoice/InvoiceInfoService.java, src/main/java/org/spin/grpc/service/field/order/OrderInfoLogic.java, src/main/java/org/spin/grpc/service/field/payment/PaymentInfoLogic.java
https://github.com/user-attachments/assets/f66cce3c-0189-4dcf-b407-9a8224995340
https://github.com/user-attachments/assets/f1b1246b-b95d-4b35-88cd-224c912928c8
fixes https://github.com/solop-develop/adempiere-grpc-server/pull/812
=> SQL Error in Order Field (Payment)

src/main/java/org/spin/base/db/WhereClauseUtil.java, src/main/java/org/spin/grpc/service/field/product/ProductInfoLogic.java
https://github.com/user-attachments/assets/d6b3b1d4-078f-44b1-87eb-cba0e12b832a
fixes https://github.com/solop-develop/frontend-core/issues/2259
=> fix: `Product` info field with role, org, and record access.

src/main/java/org/spin/base/db/WhereClauseUtil.java, src/main/java/org/spin/dictionary/util/ReportUtil.java, src/main/java/org/spin/grpc/service/ReportManagement.java
https://github.com/user-attachments/assets/be4463a8-67aa-416e-9b6b-e5bc711c9766
fixes https://github.com/solop-develop/frontend-core/issues/2380
=> fix: Change report output.

src/main/java/org/spin/grpc/service/InOutInfo.java, src/main/java/org/spin/grpc/service/field/business_partner/BusinessPartnerLogic.java, src/main/java/org/spin/grpc/service/field/invoice/InvoiceInfoLogic.java, src/main/java/org/spin/grpc/service/field/order/OrderInfoLogic.java, src/main/java/org/spin/grpc/service/field/payment/PaymentInfoLogic.java, src/main/java/org/spin/grpc/service/field/product/ProductInfoLogic.java, src/main/java/org/spin/grpc/service/ui/UserInterfaceLogic.java
https://github.com/user-attachments/assets/49367045-8c02-4751-9c85-fbc6a182a297
https://github.com/user-attachments/assets/99523446-5bf9-4c91-8f48-cc2060b05253
fixes https://github.com/solop-develop/frontend-core/issues/2470
=> fix: List `IsActive` records on search field.

build.gradle
Add AWS S3 ADempiere Connector.
=> feat: Add `S3 Connector` 1.0.2 version.

src/main/java/org/spin/base/util/RecordUtil.java, src/main/java/org/spin/grpc/service/UserInterface.java
fixes https://github.com/solop-develop/frontend-core/issues/2561
=> feat: Add client uuid on record as `AD_Client_ID_UUID`.

src/main/java/org/spin/base/db/OrderByUtil.java, src/main/java/org/spin/base/db/QueryUtil.java, src/main/java/org/spin/base/db/WhereClauseUtil.java, src/main/java/org/spin/base/util/ReferenceInfo.java, src/main/java/org/spin/base/util/WorkflowUtil.java, src/main/java/org/spin/dictionary/util/ReportUtil.java, src/main/java/org/spin/dictionary/util/WindowUtil.java, src/main/java/org/spin/form/import_file_loader/ImportFileLoaderServiceLogic.java, src/main/java/org/spin/grpc/service/ReportManagement.java, src/main/java/org/spin/grpc/service/UserInterface.java, src/main/java/org/spin/grpc/service/dictionary/BrowseConverUtil.java, src/main/java/org/spin/grpc/service/dictionary/Dictionary.java, src/main/java/org/spin/grpc/service/dictionary/ProcessConvertUtil.java, src/main/java/org/spin/grpc/service/dictionary/WindowConvertUtil.java, src/main/java/org/spin/grpc/service/field/field_management/FieldManagementConvert.java, src/main/java/org/spin/grpc/service/field/field_management/FieldManagementLogic.java, src/main/java/org/spin/grpc/service/ui/BrowserLogic.java
ASP handling is eliminated, since the dictionary is currently handled in OpenSearch and is not being exported, generating unexpected behavior in the handling, visualization and filtering of records.
fixes https://github.com/solop-develop/frontend-core/issues/2565
=> fix: Remove ASP manage.

src/main/java/org/spin/grpc/service/GeneralLedger.java
Before
https://github.com/user-attachments/assets/d37c8ce4-5bd8-4ccd-bd1f-a3aaa4b31808
After 
https://github.com/user-attachments/assets/1b447e6f-6a8c-4c50-8e8b-24d8a4d873aa
fixed: https://github.com/solop-develop/frontend-core/issues/2429
=> Fix: Validate Organization ID

src/main/java/org/spin/grpc/service/form/match_po_receipt_invoice/MatchPOReceiptInvoice.java, src/main/java/org/spin/grpc/service/form/payroll_action_notice/PayrollActionNotice.java
Implement get display column lookup key.
=> feat: Implement lookup display column key method.

src/main/java/org/spin/base/db/WhereClauseUtil.java, src/main/java/org/spin/dictionary/util/WindowUtil.java
=> fix: Load child records.

src/main/java/org/spin/grpc/service/UserInterface.java
```bash
curl 'http://20.12.0.164/api/user-interface/run-callout/450/M_Product_ID/@script:beanshell:fill_SerNoFromProduct' \
-X POST \
-H 'Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiIxMDAxMDQzIiwiQURfQ2xpZW50X0lEIjoxMSwiQURfT3JnX0lEIjo1MDAwNiwiQURfUm9sZV9JRCI6MTAwMDAwMSwiQURfVXNlcl9JRCI6MTAwMDAwNywiTV9XYXJlaG91c2VfSUQiOjUwMDA2LCJBRF9MYW5ndWFnZSI6ImVzX01YIiwiaWF0IjoxNzI0MzU4MTI4LCJleHAiOjE3MjQ0NDQ1Mjh9.9jUSfnaNLppRr4kYhsO1BIn9p7n4u6Lvrl1MRstLu3I' \
--data-raw '{"tab_id":450,"context_attributes":{"A_Asset_Action":"MD","Processed":false,"A_AssetType":"MFX","Processing":false,"AD_Client_ID":11,"AD_Org_ID":50006,"IsActive":true,"M_Product_ID":1000001,"A_Asset_Group_ID":50006,"IsInPosession":false,"M_ …
```
=> fix: Callout with `@script` as MRule.

build.gradle, gradle.properties
=>  feat: Increase default JVM Arguments on gradle.

src/main/java/org/spin/grpc/service/dictionary/WindowConvertUtil.java
=> fix: Tab and Field translation.

src/main/java/org/spin/base/db/QueryUtil.java, src/main/java/org/spin/grpc/service/UserInterface.java, src/main/java/org/spin/grpc/service/dictionary/BrowseConverUtil.java, src/main/java/org/spin/grpc/service/dictionary/DictionaryConvertUtil.java, src/main/java/org/spin/grpc/service/dictionary/ProcessConvertUtil.java, src/main/java/org/spin/grpc/service/dictionary/WindowConvertUtil.java
https://github.com/user-attachments/assets/afac9618-9a24-4912-9a4b-e7a2294e1d0c
https://github.com/user-attachments/assets/4b96ebad-c0d6-497f-8f6f-f3efda908d13
fixes https://github.com/solop-develop/frontend-core/issues/2593
=> fix: Translate list values on records.

docker/envoy_template.yaml, resources/envoy.yaml, src/main/java/org/spin/grpc/service/PreferenceManagement.java, src/main/java/org/spin/server/AllInOneServices.java
```bash
curl --location 'http://20.12.0.164/api/preference-management/preference/WINDOW/C_Order' \
--header 'Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiIyMDIyNDg1IiwiQURfQ2xpZW50X0lEIjoxMDAwMDAxLCJBRF9PcmdfSUQiOjEwMDAwMDEsIkFEX1JvbGVfSUQiOjEwMDAwMDIsIkFEX1VzZXJfSUQiOjEwMDEyMTIsIk1fV2FyZWhvdXNlX0lEIjoxMDAwMDI4LCJBRF9MYW5ndWFnZSI6ImVzX01YIiwiaWF0IjoxNzI0OTM4NzEzLCJleHAiOjE3MjUwMjUxMTN9.6-jOwCzWeguCHAQzitbmNAzFcIQ97IiBi5iSjwG3BKw'
```
```json
{
"client_id": 0,
"organization_id": 0,
"user_id": 0,
"container_id": 0,
"column_name": "",
"value": "",
"type": "CUSTOM"
}
```
https://github.com/solop-develop/frontend-core/issues/2426
=> feat: Add get Preference.

src/main/java/org/spin/grpc/service/Dashboarding.java
fixes https://github.com/solop-develop/frontend-core/issues/2601
=> Error number of records in the Document Pending

build.gradle
fixes https://github.com/solop-develop/frontend-core/issues/2604
=> Bugfix/role access with string UUID

build.gradle
```bash
curl --location --request GET 'http://192.168.3.53/api/user-interface/entities/186?record_reference_uuid=&search_value=&context_attributes=%7B%7D&page_token=1&page_size=15&sort_by=DocumentNo%20ASC' \
--header 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:129.0) Gecko/20100101 Firefox/129.0' \
--header 'Accept: application/json, text/plain, */*' \
--header 'Accept-Language: es-ES,es;q=0.8,en-US;q=0.5,en;q=0.3' \
--header 'Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiIyMDIyNTEzIiwiQURfQ2xpZW50X0lEIjoxMDAwMDAxLCJBRF9PcmdfSUQiOjEwMDAwMDMsIkFEX1JvbGVfSUQiOjEwMDAwMDIsIkFEX1VzZXJfSUQiOjEwMDEyMTIsIk1fV2FyZWhvdXNlX0lEIjoxMDAwMDQ1LCJBRF9MYW5ndWFnZSI6ImVuX1VTIiwiaWF0IjoxNzI2MjM2MjU5LCJleHAiOjE3MjYzMjI2NTl9.-Ed81ejkt6bxZPA-cQhJ081ovsUyiUgbzyi2ebhqPUU' \
--header 'Connection: …
```
=> feat: Add support to sort column on window.

src/main/java/org/spin/grpc/service/BusinessData.java
1. [xxx]
2. [xxx]
3. [xxxx]
https://github.com/user-attachments/assets/394071cc-5d36-4bdc-9151-4e1a0f74dcef
A clear and concise description of what you expected to happen.
- Your OS:
- Web Browser:
- Node.js version:
- Yarn version:
- adempiere-vue version: 
fixes https://github.com/solop-develop/frontend-core/issues/2597
=> fix: SB process all records on server.

src/main/java/org/spin/base/util/ReferenceInfo.java
related issue https://github.com/solop-develop/frontend-core/issues/2622
=> fix: `Payment Rule` field with Button as List display type.

src/main/java/org/spin/grpc/service/dictionary/ProcessConvertUtil.java
ref https://github.com/solop-develop/frontend-core/issues/2435
=> fix: Correct `Is Jasper Report` with backend.

src/main/java/org/spin/grpc/service/form/issue_management/IssueManagementServiceLogic.java
ref https://github.com/solop-develop/frontend-core/issues/2436
=> fix: Remove parallel stream on issues form.

src/main/java/org/spin/grpc/service/form/issue_management/IssueManagementServiceLogic.java
https://github.com/user-attachments/assets/39ee635c-f0b6-42be-bb48-5602e203968f
=> Support to Filter Issues All

src/main/java/org/spin/grpc/service/form/issue_management/IssueManagementServiceLogic.java
ref https://github.com/solop-develop/frontend-core/issues/2436
=> Change Where Clause to List Issues All

build.gradle, src/main/java/org/spin/base/db/WhereClauseUtil.java, src/main/java/org/spin/grpc/service/UserInterface.java
https://github.com/user-attachments/assets/59de2634-0fd7-468a-b074-a1127b811747
https://github.com/user-attachments/assets/9ef4bb20-5023-4424-bb83-6d7f07019a16
fixes https://github.com/solop-develop/frontend-core/issues/2884
=> fix: DB Parameter with display type.

src/main/java/org/spin/base/db/QueryUtil.java
ref https://github.com/solop-develop/frontend-core/issues/2937
=> fix: Display Column on virtual column sql.

src/main/java/org/spin/grpc/service/UserInterface.java
https://github.com/user-attachments/assets/f8ce409d-1430-45c7-be0c-85cd95a0806f
ref https://github.com/solop-develop/frontend-core/issues/2927
=> fix: Record Count with search value.

src/main/java/org/spin/base/util/ConvertUtil.java, src/main/java/org/spin/base/util/RecordUtil.java, src/main/java/org/spin/grpc/service/UserInterface.java
=> feat: Add `DisplayColumn` value on `Record_ID` column.

src/main/java/org/spin/base/db/WhereClauseUtil.java
ref https://github.com/solop-develop/frontend-core/issues/2921
=> fix: Load records on `CFE` tab.

src/main/java/org/spin/base/workflow/WorkflowUtil.java, src/main/java/org/spin/grpc/logic/RecordManagementServiceLogic.java, src/main/java/org/spin/grpc/service/BusinessData.java, src/main/java/org/spin/grpc/service/NoticeManagement.java, src/main/java/org/spin/grpc/service/PointOfSalesForm.java, src/main/java/org/spin/grpc/service/ReportManagement.java, src/main/java/org/spin/grpc/service/Security.java, src/main/java/org/spin/grpc/service/UserInterface.java, src/main/java/org/spin/grpc/service/dictionary/DictionaryConvertUtil.java, src/main/java/org/spin/grpc/service/form/PaymentAllocation.java, src/main/java/org/spin/grpc/service/form/bank_statement_match/BankStatementMatchServiceLogic.java, src/main/java/org/spin/grpc/service/form/import_file_loader/ImportFileLoaderServiceLogic.java, src/main/java/org/spin/grpc/service/form/match_po_receipt_invoice/MatchPOReceiptInvoice.java, src/main/java/org/spin/log/LogsConvertUtil.java
https://github.com/user-attachments/assets/0509bc7d-553c-4f11-b1f2-bb31cba7297e
https://github.com/user-attachments/assets/74226ab1-3e5e-4c26-8e3d-d97750be4c81
=> fix: Translated process message.

build.gradle, gradle.properties
https://github.com/user-attachments/assets/7bb8f6fe-babb-4e49-9bb0-cee8fd395044
ref https://github.com/solop-develop/frontend-core/issues/189
=> fix: The time is saved with afternoon time but always returns morning time

src/main/java/org/spin/grpc/service/UserInterface.java, src/main/java/org/spin/grpc/service/ui/CalloutLogic.java
https://github.com/user-attachments/assets/6dc821e3-6238-43fa-ad8f-e224eafa3372
ref https://github.com/solop-develop/frontend-core/issues/214
=> fix: Set callout on hidden fields.

src/main/java/org/spin/grpc/service/GeneralLedger.java
ref https://github.com/solop-develop/frontend-core/pull/230
=> fix: RePost message error.

src/main/java/org/spin/grpc/service/UserInterface.java
https://github.com/user-attachments/assets/d533fffa-766d-47e1-a357-91ba504d6927
ref https://github.com/solop-develop/frontend-core/issues/184
ref https://github.com/solop-develop/frontend-core/issues/207
ref
=> fix: Set callout.

gradle.properties
- Update `adempiere-kafka-connector` to 1.4.8.
- Update `adempiere-grpc-utils` to 1.5.6.
- Redmine `#22530`.
- Add `WPP` and `CGM` projects.
ref https://github.com/solop-develop/frontend-core/issues/236
=> feat: Update `adempiere-solop` libs to `3.9.4.001-spuy-0.0.1-rc-12` version.

gradle.properties
ref https://github.com/solop-develop/frontend-core/issues/249
=> fix: Menu Tree with parent id `NULL` as `Zero`.

src/main/java/org/spin/grpc/logic/GeneralLedgerServiceLogic.java, src/main/java/org/spin/grpc/service/GeneralLedger.java
ref https://github.com/solop-develop/frontend-core/issues/229
=> fix: Re-Post accouting document error message.

src/main/java/org/spin/grpc/service/dictionary/WindowConvertUtil.java
See
https://github.com/adempiere/adempiere/blob/develop/base/src/org/adempiere/apps/toolbar/AProcessActionModel.java#L237
ref https://github.com/solop-develop/frontend-core/issues/2
=> feat: Tab processes list order by name.

src/main/java/org/spin/grpc/service/field/business_partner/BusinessPartnerLogic.java
```
Position: 198, SQL=SELECT COUNT(*) FROM C_BPartner WHERE ( 1=1 AND IsActive = ?  AND C_BPartner_ID IN (SELECT C_BPartner_ID FROM C_BPartner_Location bpl, C_Location AS l WHERE l.C_Location_ID = bpl.C_Location_ID AND UPPER(Postal) '%' || UPPER(?) || '%') ) AND AD_Client_ID=?
```
=> fix: Postal code filter sql on bp field.

src/main/java/org/spin/grpc/service/form/PaymentAllocation.java
ref https://github.com/solop-develop/frontend-core/issues/128
=> fix: SQL Payment allocation.

src/main/java/org/spin/grpc/service/form/import_file_loader/ImportFileLoaderServiceLogic.java
References: https://github.com/solop-develop/frontend-core/issues/67
=> Fixed error with parse data

src/main/java/org/spin/grpc/service/PointOfSalesForm.java, src/main/java/org/spin/pos/util/OrderConverUtil.java, src/main/java/org/spin/pos/util/POSConvertUtil.java
ref https://github.com/solop-develop/frontend-core/issues/289
=> feat: Add `Invoice No` on POS order.

src/main/java/org/spin/grpc/service/MaterialManagement.java
ref https://github.com/solop-develop/frontend-core/issues/282
=> feat: Load warehouse asterisc `All` on locators field.

src/main/java/org/spin/grpc/service/PointOfSalesForm.java
```bash
curl --location --request POST 'http://0.0.0.0/api/point-of-sales/customers' \
--header 'Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiIzMDA3MjEyIiwiQURfQ2xpZW50X0lEIjoxMDAwMDAxLCJBRF9PcmdfSUQiOjEwMDAwMTAsIkFEX1JvbGVfSUQiOjEwMDAwMjIsIkFEX1VzZXJfSUQiOjEwMDEyMTIsIk1fV2FyZWhvdXNlX0lEIjoxMDAwMDgwLCJBRF9MYW5ndWFnZSI6ImVzX01YIiwiaWF0IjoxNzM2MjY1NDQzLCJleHAiOjE3MzYzNTE4NDN9.fdQaDvHj4i45oA65KarSrEbD_DfyadqATI7qcINMLi0' \
--data '{
"name": "Edmundo González 4",
"value": "",
"addresses": [
{
"posalCodeAdditional": "",
"locationName": "",
"postalCode": "",
"countries": {},
"cityLabel": "",
"longitude": "",
"address1": "",
"address2": "",
"address3": "",
"address4": "",
"latitude": "",
"altitude": "",
"reference": "",
"phone": "",
"email": …
```
=> fix: Create POS Customer template.

src/main/java/org/spin/grpc/service/display_definition/DisplayDefinition.java, src/main/java/org/spin/grpc/service/display_definition/DisplayDefinitionConvertUtil.java, src/main/java/org/spin/grpc/service/display_definition/DisplayDefinitionServiceLogic.java
ref https://github.com/solop-develop/adempiere-solop/issues/81
=> feat: Display Type resources.

src/main/java/org/spin/pos/service/POSLogic.java
ref https://github.com/solop-develop/frontend-core/issues/287
=> fix: POS `Business Partner Template` order by `SeqNo`.

src/main/java/org/spin/grpc/service/display_definition/DisplayDefinitionConvertUtil.java
=> fix: Display Type definitions columns.

.github/workflows/publish.yml
Referente a https://github.com/solop-develop/adempiere-solop/issues/98
Documentación https://stackoverflowteams.com/c/solop/questions/83/84#84
Imagen en Registry registry.digitalocean.com/spuy/adempiere-grpc-server:adempiere-solop-98-docker-image.0.0.1
=> Set new Docker Repo Registry

src/main/java/org/spin/base/util/ReferenceUtil.java, src/main/java/org/spin/grpc/service/ui/BrowserLogic.java
https://github.com/user-attachments/assets/c738b222-a199-4fa9-acda-53a915581db9
ref https://github.com/solop-develop/frontend-core/issues/258
=> fix: Smart Browse with field as `Table Direct` and `Reference Key`.

src/main/java/org/spin/base/util/ReferenceUtil.java
ref https://github.com/solop-develop/frontend-core/issues/385
ref https://github.com/solop-develop/frontend-core/issues/258
=> fix: Display Value without reference value.

gradle.properties
```json
{
"default_context": {
"$C_Currency_ID": 142,
"#GL_Category_ID": 1000015,
"#C_TaxCategory_ID": 1000000,
"$Element_OO": true,
"#AD_PrintColor_ID": 100,
"#ShowAcct": true,
"$Element_X2": true,
"#AD_Client_ID": 1000001,
"#SalesRep_ID": 1000065,
"#M_Locator_ID": 1000063,
"#AD_PrintPaper_ID": 100,
"#AD_User_Name": "ebetancourt",
"$Element_PR": true,
"#M_PriceList_ID": 1000001,
"$C_AcctSchema_ID": 1000001,
"$Element_U4": true,
"#AD_User_ID": 1000065,
"$Element_U1": true,
"#C_ConversionType_ID": 114,
"#M_Product_Category_ID": 1000000,
"$HasAlias": true,
"$Element_PJ": true,
"#AD_User_Description": "Edwin Betancourt",
"$Element_MC": true,
"#Session_UUID": "c31dd744-2ad8-41e6-b8ae-3c29223ffbc7",
"#AD_Org_ID": 1000002,
"#AD_Client_Name": "Dentsu Uruguay",
"#C_PaymentTerm_ID": 1000000, …
```
=> fix: Default values by session context.

src/main/java/org/spin/base/db/WhereClauseUtil.java
ref https://github.com/solop-develop/frontend-core/issues/157
=> fix: Where with `DISTINCT` clause.

src/main/java/org/spin/base/util/ReferenceInfo.java
```bash
curl --location --request GET 'http://0.0.0.0/api/dictionary/search/parameter/57194' \
--header 'Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiIzMDEwMzM4IiwiQURfQ2xpZW50X0lEIjoxMDAwMDAxLCJBRF9PcmdfSUQiOjAsIkFEX1JvbGVfSUQiOjEwMDAwMDIsIkFEX1VzZXJfSUQiOjEwMDEyMTIsIk1fV2FyZWhvdXNlX0lEIjowLCJBRF9MYW5ndWFnZSI6ImVzX01YIiwiaWF0IjoxNzM4MDgwMjQ0LCJleHAiOjE3MzgxNjY2NDR9.kzapmliqMNx3Qa6XgCYPS4Mg_HNwdNCs-qrvRMPl9sM' \
--header 'Connection: keep-alive'
```
```json
{
"code": 2,
"message": "Application error processing RPC",
"details": []
}
```
=> fix: Infinity loop on reference method.

gradle.properties
https://github.com/user-attachments/assets/64604202-5fa6-47e5-8351-287c7d135fa1
=> fix: Display Value on `List` reference.

src/main/java/org/spin/grpc/service/display_definition/DisplayDefinitionConvertUtil.java
```bash
curl --location --request POST 'http://0.0.0.0/api/display-definition/1000042/entries/resources' \
--header 'accept: application/json, text/plain, */*' \
--header 'accept-language: en-US,en;q=0.9,es;q=0.8' \
--header 'authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiIzMDEzNzU0IiwiQURfQ2xpZW50X0lEIjoxMDAwMDAxLCJBRF9PcmdfSUQiOjEwMDAwMTAsIkFEX1JvbGVfSUQiOjEwMDAwMDIsIkFEX1VzZXJfSUQiOjEwMDEyMTIsIk1fV2FyZWhvdXNlX0lEIjoxMDAwMDgwLCJBRF9MYW5ndWFnZSI6ImVzX01YIiwiaWF0IjoxNzM4ODU4MTAyLCJleHAiOjE3Mzg5NDQ1MDJ9.dqoB1gP3Qgfv_-fZLDJIx3X1KqO6k2TpbAgTi7U2GYM' \
--header 'content-type: application/json' \
--header 'cookie: ajs_anonymous_id=%229c08db1f-48b4-474a-8993-b73697013ed2%22; language=es; sidebarStatus=0' \
--header 'origin: https://patches.dev.solopcloud.com' \
--header 'priority: u=1, i' …
```
=> fix: Get Display Definition entry with null values.

src/main/java/org/spin/grpc/service/display_definition/DisplayDefinitionServiceLogic.java
```json
{
"code": 13,
"message": "Cannot invoke \"com.google.protobuf.Value.getStringValue()\" because \"value\" is null",
"details": []
}
```
```json
{
"code": 13,
"message": "Cannot invoke \"java.lang.Integer.intValue()\" because the return value of \"org.spin.service.grpc.util.value.NumberManager.getIntegerFromObject(Object)\" is null",
"details": []
}
```
=> fix: NPE with Value is null.

src/main/java/org/spin/grpc/service/display_definition/DisplayDefinitionServiceLogic.java
=> fix: Set resource assignment value on record display definition.

src/main/java/org/spin/grpc/service/dictionary/DictionaryServiceLogic.java
```bash
curl --location --request GET 'http://0.0.0.0/api/dictionary/processes/table/R_Request' \
--header 'Accept: application/json, text/plain, */*' \
--header 'Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiIzMDEzODc1IiwiQURfQ2xpZW50X0lEIjoxMDAwMDAxLCJBRF9PcmdfSUQiOjEwMDAwMDEsIkFEX1JvbGVfSUQiOjEwMDAwMDIsIkFEX1VzZXJfSUQiOjEwMDEyMTIsIk1fV2FyZWhvdXNlX0lEIjoxMDAwMDI4LCJBRF9MYW5ndWFnZSI6ImVzX01YIiwiaWF0IjoxNzM4ODgxNzcwLCJleHAiOjE3Mzg5NjgxNzB9.QYl3iJraz4i752V0NtYHOS3BNvraVLwUr1y8jpgpGTc' \
--header 'Connection: keep-alive' \
--header 'TE: trailers'
```
```json
{
"record_count": "2",
"processes": [
{
"id": "a42b1388-fb40-11e8-a479-7a0060f0aa01",
"uuid": "a42b1388-fb40-11e8-a479-7a0060f0aa01",
"internal_id": 324,
"code": "R_RequestInvoice",
"name": "Facturar Solicitudes",
"description": …
```
=> fix: List processes by table name.

src/main/java/org/spin/grpc/service/Dashboarding.java, src/main/java/org/spin/grpc/service/form/issue_management/IssueManagementServiceLogic.java
ref https://github.com/solop-develop/frontend-core/issues/593
=> fix: Issues count with notification.

src/main/java/org/spin/grpc/service/GeneralLedger.java
ref https://github.com/solop-develop/adempiere-solop/issues/266
=> fix: MatchInv and MatchPO posted tables.

src/main/java/org/spin/base/db/WhereClauseUtil.java, src/main/java/org/spin/grpc/service/dictionary/WindowConvertUtil.java
```sql
(EXISTS(SELECT 1 FROM C_ProjectLine ppl INNER JOIN M_Product_PO po ON(po.C_BPartner_ID = ppl.Vendor_ID AND po.M_Product_ID = M_Product.M_Product_ID) WHERE ppl.C_ProjectLine_ID = @Parent_ID@))
```
```sql
(EXISTS(SELECT 1 FROM C_ProjectLine AS p.ppl INNER JOIN M_Product_PO AS po ON(po.C_BPartner_ID = ppl.Vendor_ID AND po.M_Product_ID = M_Product.M_Product_ID) WHERE ppl.C_ProjectLine_ID = @Parent_ID@))
```
```sql
(EXISTS(SELECT 1 FROM C_ProjectLine ppl INNER JOIN M_Product_PO po ON(po.C_BPartner_ID = ppl.Vendor_ID AND po.M_Product_ID = p.M_Product_ID) WHERE ppl.C_ProjectLine_ID = @Parent_ID@))
```
=> fix: Dynamic validation with subquery.

.gitignore, build.gradle
Add `.env` file evaluation to get gradle credentials
=> feat: Add `.env` file to get gradle credentials.

src/main/java/org/spin/grpc/service/form/out_bound_order/OutBoundOrderLogic.java
ref https://github.com/solop-develop/frontend-core/issues/720
=> fix: Generate `Order Freight` from `Out Bound Order` form.

src/main/java/org/spin/grpc/service/PointOfSalesForm.java, src/main/java/org/spin/pos/util/OrderConverUtil.java
https://github.com/user-attachments/assets/2f5e3984-a2d5-41b0-8194-dc34d6415b61
ref https://github.com/solop-develop/adempiere-solop/issues/493
=> fix: Discount amount/percent to all document.

src/main/java/org/spin/base/util/ReferenceInfo.java
=> fix: Dynamic Validation on window not working.

src/main/java/org/spin/grpc/service/PointOfSalesForm.java
ref https://github.com/solop-develop/adempiere-solop/issues/553
=> fix: POS Product Price list with zero price and is sold.

gradle.properties
Add support for Barcodes and QR codes in Jasperreport
=> Update Backend version

src/main/java/org/spin/grpc/service/form/out_bound_order/OutBoundOrderLogic.java
=> fix: Out Bound Order form only active list.

src/main/java/org/spin/grpc/service/form/out_bound_order/OutBoundOrderLogic.java
When adding the Weight and Volume if they where null it throws an error, validate that they where Zero if null
Freight order line requires M_Freight_ID, finds it by Shipper only first active Freight
Ref: https://github.com/solop-develop/frontend-core/issues/675
Ref: https://github.com/solop-develop/frontend-core/issues/720
There are still problems when proccessing the created orders
=> Validates that weight, volume and M_Freight_ID are not null

src/main/java/org/spin/pos/service/POSLogic.java
Purchase Orders should be completed or closed to create a Gift Card
Ref: https://github.com/solop-develop/adempiere-solop/issues/603
=> fixes document status validation for create gift card request

src/main/java/org/spin/pos/service/POSLogic.java
Create Gift card should always create a new gift card and not search for existing one
Ref: https://github.com/solop-develop/adempiere-solop/issues/603
=> GiftCard only create new and set amount

src/main/java/org/spin/pos/util/POSConvertUtil.java
ref https://github.com/solop-develop/adempiere-solop/issues/675
=> fix: POS Payment Method Allocation discount.

src/main/java/org/spin/pos/service/cash/CollectingManagement.java, src/main/java/org/spin/pos/service/order/OrderManagement.java, src/main/java/org/spin/pos/util/PaymentConvertUtil.java
ref https://github.com/solop-develop/adempiere-solop/issues/690
=> fix: Online Payment verification.

src/main/java/org/spin/pos/service/POSLogic.java
Revert transaction services is not really implemented
Ref: https://github.com/solop-develop/adempiere-solop/issues/690
=> Implements the services for ProcessOnline and InfoOnline

src/main/java/org/spin/grpc/service/PointOfSalesForm.java
https://www.loom.com/share/99c6895b75124f39a4fd3b1dca3ead41?sid=755e90c3-4c9c-432d-83ec-5d1ac24f14f7
Ref: https://github.com/solop-develop/adempiere-solop/issues/850
=> Filter available Sellers by SearchValue

src/main/java/org/spin/base/util/ReferenceUtil.java
https://github.com/user-attachments/assets/657bb6b0-fc92-4ad6-95a1-c6afdb7a3a44
ref https://github.com/solop-develop/adempiere-solop/issues/859
=> Fix: Warehouse Location ID display column

src/main/java/org/spin/grpc/service/BusinessData.java
ref https://github.com/solop-develop/adempiere-solop/issues/840
=> fix: Set selections if not empty.

src/main/java/org/spin/base/db/QueryUtil.java, src/main/java/org/spin/base/util/ReferenceInfo.java, src/main/java/org/spin/base/util/ReferenceUtil.java
https://github.com/user-attachments/assets/5378bb22-791e-43d6-95c5-03f44f074fc4
ref https://github.com/solop-develop/adempiere-solop/issues/912
=> fix: Smart Browse with same System Element and column alias.

src/main/java/org/spin/grpc/logic/GeneralLedgerServiceLogic.java, src/main/java/org/spin/grpc/service/GeneralLedger.java
ref https://github.com/solop-develop/adempiere-solop/issues/909
=> fix: Accounting Voew by record on table not is document.

src/main/java/org/spin/grpc/service/ReportManagement.java
ref https://github.com/solop-develop/adempiere-solop/issues/648
=> fix: Load report views only active.

src/main/java/org/spin/pos/service/POSLogic.java
Because is not implemented yet
Ref: https://github.com/solop-develop/adempiere-solop/issues/30#issuecomment-2902524972
=> Cancel Online Transaction Return Error By Default

gradle.properties, src/main/java/org/spin/grpc/service/form/PaymentAllocation.java
ref https://github.com/solop-develop/adempiere-solop/issues/973
=> fix: Accouting on `Payment Allocation` form.

src/main/java/org/spin/grpc/service/form/bank_statement_match/BankStatementMatchConvertUtil.java, src/main/java/org/spin/grpc/service/form/bank_statement_match/BankStatementMatchServiceLogic.java
ref https://github.com/solop-develop/adempiere-solop/issues/1044
=> feat: Add `IsMatched` column to bank statement import.

src/main/java/org/spin/grpc/service/PointOfSalesForm.java
https://github.com/user-attachments/assets/b4eae6d0-6391-4613-8ae0-251ce731262d
ref https://github.com/solop-develop/adempiere-solop/issues/672
=> feat: POS search EAN into Product Purchase.

src/main/java/org/spin/pos/service/POSLogic.java
ref: https://github.com/solop-develop/adempiere-solop/issues/1119
=> feat: Implements Cancel Online Payment

gradle.properties
ref https://github.com/solop-develop/adempiere-base/issues/195
=> feat: Create automatic `Gift Card` after complete sales order.

gradle.properties, src/main/java/org/spin/grpc/service/BusinessData.java
ref https://github.com/solop-develop/adempiere-solop/issues/1118
=> fix: Upload resource form parameter field.

src/main/java/org/spin/grpc/service/PointOfSalesForm.java, src/main/java/org/spin/pos/service/POSLogic.java, src/main/java/org/spin/pos/util/POSConvertUtil.java
```bash
===========> PointOfSalesForm.listCustomerCredits: org.postgresql.util.PSQLException: ERROR: column i.isprocessed does not exist
Hint: Perhaps you meant to reference the column "i.processed".
Position: 156 [792]
org.adempiere.exceptions.AdempiereException: org.postgresql.util.PSQLException: ERROR: column i.isprocessed does not exist
Hint: Perhaps you meant to reference the column "i.processed".
Position: 156
at org.spin.grpc.service.PointOfSalesForm.listCustomerCredits(PointOfSalesForm.java:2085)
at org.spin.grpc.service.PointOfSalesForm.listCustomerCredits(PointOfSalesForm.java:1949)
at org.spin.backend.grpc.pos.StoreGrpc$MethodHandlers.invoke(StoreGrpc.java:7194)
at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:182)
at …
```
=> fix: POS List Customer Credits unknow column.

src/main/java/org/spin/pos/service/cash/CollectingManagement.java, src/main/java/org/spin/pos/service/order/OrderManagement.java, src/main/java/org/spin/pos/util/ColumnsAdded.java
=> feat: Create `Gift Card` refund after process payment.

src/main/java/org/spin/grpc/service/PointOfSalesForm.java, src/main/java/org/spin/pos/service/order/OrderManagement.java
ref https://github.com/solop-develop/adempiere-solop/issues/1144
=> fix: POS Create/Update sales order validate Cash Closing/Opening.

src/main/java/org/spin/grpc/service/PointOfSalesForm.java, src/main/java/org/spin/pos/service/cash/CashManagement.java, src/main/java/org/spin/pos/service/cash/CollectingManagement.java
When multiple cash coling get the first open.
###
ref https://github.com/solop-develop/adempiere-solop/issues/1140
=> fix: Cash Closing.

src/main/java/org/spin/pos/service/order/RMAUtil.java
- Cleans other online transaction info for the reverse payment
- Fixes reverse payment IsReceipt
Ref: https://github.com/solop-develop/adempiere-solop/issues/1119
=> Add original ticket to reverse payment when is online transaction

src/main/java/org/spin/base/util/ConvertUtil.java, src/main/java/org/spin/grpc/service/PointOfSalesForm.java
When create a Payment Reference this save with `PayDate` on NULL value.
=> fix: `Payment Reference` without `Pay Date`.

src/main/java/org/spin/pos/service/POSLogic.java, src/main/java/org/spin/pos/service/order/OrderManagement.java
=> fix: Refund `Gift Card` from payment reference.

gradle.properties
Update `electronic-invoicing` to `base-0.7.16-0.0.4`.
=> feat: Update `solop-libs` to `2.1.14`.

src/main/java/org/spin/pos/service/cash/CollectingManagement.java, src/main/java/org/spin/pos/service/order/OrderManagement.java, src/main/java/org/spin/pos/service/payment/GiftCardManagement.java
=> fix: Gift Card mark as process.

src/main/java/org/spin/pos/service/order/OrderManagement.java, src/main/java/org/spin/pos/service/order/RMAUtil.java, src/main/java/org/spin/pos/service/order/ReturnSalesOrder.java, src/main/java/org/spin/pos/service/payment/GiftCardManagement.java
ref https://github.com/solop-develop/adempiere-solop/issues/1242
=> feat: RMA Gift Card.

src/main/java/org/spin/grpc/service/form/trial_balance_drillable/TrialBalanceDrillable.java, src/main/java/org/spin/grpc/service/form/trial_balance_drillable/TrialBalanceDrillableServiceLogic.java
=> fix: `Trial Balance Drillable` form list only active records.

src/main/java/org/spin/grpc/service/form/trial_balance_drillable/TrialBalanceDrillableServiceLogic.java
=> fix: `Trial Balance Drillable` form list `User_1`.

src/main/java/org/compiere/model/MOrder.java
Se agrega clase MOrder y se corrige sql por error de sintaxis
=> MOrder - Error en sql

src/main/java/org/compiere/model/MInvoiceLine.java
When setting OrderLine to a InvoiceLine set the C_ProjectLine_ID from the OrderLine
Added MInvoiceLine Class, it shloud be removed when the Base repository is updated and created the Release
=> Set C_ProjectLine_ID in InvoiceLine from OrderLine

src/main/java/org/spin/grpc/service/form/payment_allocation/PaymentAllocationLogic.java, src/main/proto/general_ledger.proto
ref https://github.com/solop-develop/adempiere-solop/issues/965
=>  fix: Conversion rate with date on `Payment Allocation`.

src/main/java/com/solop/sp013/core/model/validator/ElectronicInvoicing.java
ref: https://github.com/solop-develop/adempiere-solop/issues/1019
=> Calculate the Electronic Invoicing Summary Lines Before Prepare

build.gradle
Fixes sending Electronic Delivery Note
Ref: https://github.com/solop-develop/adempiere-solop/issues/1093
=> Update Electronic Invoicing to core-1.2.4-1.0.4

src/patches/org/spin/util/CashManagementUtil.java
Ref: https://github.com/solop-develop/adempiere-solop/issues/1377
=> Do not copy C_POS_ID in withdrawal from cash closing

src/patches/com/solop/sp015/transact/processor/TransActCard.java
Ref: https://github.com/solop-develop/adempiere-solop/issues/1377
=> Do not split Online Closing Voucher

src/main/java/org/spin/pos/util/OrderConverUtil.java
=> fix: Total tax amt.

src/main/java/org/spin/grpc/service/PointOfSalesForm.java, src/main/java/org/spin/pos/service/cash/CollectingManagement.java
fixes https://github.com/solop-develop/adempiere-solop/issues/1468
=> fix: Payment with other currency rounding amount.

.idea/adempiere-grpc-server.iml, .idea/codeStyles/codeStyleConfig.xml, .idea/gradle.xml, .idea/misc.xml, .idea/modules.xml, .idea/vcs.xml
=> feat: Launch with `IntelliJ IDEA`.

src/main/java/org/spin/grpc/service/form/bank_statement_match/BankStatementMatchLogic.java, src/main/java/org/spin/grpc/service/form/bank_statement_match/BankStatementMatchService.java, src/main/java/org/spin/grpc/service/form/import_file_loader/ImportFileLoaderLogic.java, src/main/java/org/spin/grpc/service/form/import_file_loader/ImportFileLoaderService.java, src/main/java/org/spin/grpc/service/form/issue_management/IssueManagementLogic.java, src/main/java/org/spin/grpc/service/form/issue_management/IssueManagementService.java, src/main/java/org/spin/grpc/service/form/match_po_receipt_invoice/MatchPOReceiptInvoiceService.java, src/main/java/org/spin/grpc/service/form/out_bound_order/OutBoundOrderLogic.java, src/main/java/org/spin/grpc/service/form/payment_allocation/PaymentAllocationLogic.java, src/main/java/org/spin/grpc/service/form/payment_allocation/PaymentAllocationService.java, src/main/java/org/spin/grpc/service/form/payroll_action_notice/PayrollActionNoticeService.java, src/main/java/org/spin/grpc/service/form/task_management/TaskManagementService.java, src/main/java/org/spin/grpc/service/form/task_management/TaskManagemetLogic.java, src/main/java/org/spin/grpc/service/form/trial_balance_drillable/TrialBalanceDrillableLogic.java, src/main/java/org/spin/grpc/service/form/trial_balance_drillable/TrialBalanceDrillableService.java, src/main/java/org/spin/server/AllInOneServices.java
ref https://github.com/solop-develop/adempiere-solop/issues/780
=> feat: Add forms to recent items.

src/main/java/org/spin/base/db/WhereClauseUtil.java
ref https://github.com/solop-develop/adempiere-solop/issues/1524
=> fix: Advanced query with Date infinite loop.

src/main/java/org/spin/grpc/service/BusinessData.java, src/main/java/org/spin/grpc/service/UserInterface.java, src/main/java/org/spin/grpc/service/ui/BrowserLogic.java
ref https://github.com/solop-develop/adempiere-solop/issues/1539
=> fix: Browser process all selection without Process Instance ID.

src/patches/org/solop/sp016/process/CreateARInvoiceFromSalesDropShipment.java
Ref: https://github.com/solop-develop/adempiere-solop/issues/966
=> Fix Consignment Sales Invoice Creation

src/patches/org/compiere/model/MPaymentProcessorBatch.java
The bank account is no longer used
=> remove method that got currency from BankAccount

src/patches/com/solop/sp013/core/documents/InvoiceFiscalDocumentLine.java, src/patches/com/solop/sp013/core/model/validator/ElectronicInvoicing.java, src/patches/com/solop/sp013/core/util/ElectronicInvoicingChanges.java, src/patches/com/solop/sp013/luy/support/documents/E_InvoiceDocument.java
If is summary Lines always send a product Value to Electronic Invoicing, use product or charge value, if not summary line value if not sent default INT1 Value
Also add validation of Use Electronic Invoicing in OrgInfo, for model validator just return if the org does not use Electronic Invoicing
=> Add Electronic Invoicing Patches

src/patches/org/adempiere/core/domains/models/I_C_Project.java, src/patches/org/adempiere/core/domains/models/I_C_ProjectLine.java, src/patches/org/adempiere/core/domains/models/X_C_Project.java, src/patches/org/adempiere/core/domains/models/X_C_ProjectLine.java, src/patches/org/compiere/model/MProjectLine.java, src/patches/org/solop/project/process/GenerateSalesOrder.java
Ref: https://github.com/solop-develop/adempiere-solop/issues/1201
=> Add support for Cost Based Projects

src/patches/org/adempiere/core/domains/models/I_C_ProjectLine.java, src/patches/org/adempiere/core/domains/models/I_S_ResourceType.java, src/patches/org/adempiere/core/domains/models/X_C_ProjectLine.java, src/patches/org/adempiere/core/domains/models/X_S_ResourceType.java, src/patches/org/compiere/model/MProjectLine.java
Ref: https://github.com/solop-develop/adempiere-solop/issues/1201
=> Add Resource Type and Employee for Cost Based Project

src/patches/org/adempiere/core/domains/models/I_C_PPBatchConfiguration.java, src/patches/org/adempiere/core/domains/models/X_C_PPBatchConfiguration.java, src/patches/org/solop/process/GenerateAPInvoiceFromBatch.java, src/patches/org/solop/process/GenerateARInvoiceFromBatch.java
Also Fix Sales Invoice Charge and Currency
Ref: https://github.com/solop-develop/adempiere-solop/issues/1455
=> Fix PPBatch Withholding and Tariff document Tax Calculation

src/patches/com/solop/sp013/core/documents/InvoiceFiscalDocument.java
=> Fix Electronic Document Print Format

src/main/java/org/spin/pos/service/cash/CashServiceLogic.java, src/patches/org/adempiere/core/domains/models/I_C_POS.java, src/patches/org/adempiere/core/domains/models/X_C_POS.java
Ref: https://github.com/solop-develop/adempiere-solop/issues/1642
=> Add support for Online Cash Closing Validation

src/patches/com/solop/sp013/core/model/validator/ElectronicInvoicing.java, src/patches/com/solop/sp013/core/util/ElectronicInvoicingChanges.java, src/patches/com/solop/sp013/core/util/ElectronicInvoicingUtil.java
Ref: https://github.com/solop-develop/adempiere-solop/issues/1638
=> Add Manual Electronic Documents for Tax Group Validation

src/patches/com/solop/sp013/luy/support/documents/DocumentBuilder.java, src/patches/com/solop/sp013/luy/support/documents/ICFEDocument.java
ref: https://github.com/solop-develop/adempiere-solop/issues/1638
=> Allow to send Contingency Electronic Documents
