solop-develop/adempiere-grpc-server

tools/backend.launch

Added support for the grpc backend launcher in eclipse.
Using the default connection data from the resources/standalone.yml file.
https://user-images.githubusercontent.com/20288327/167266393-0b451fa0-5170-40b0-b54c-2607722782da.mp4

feat: Add eclipse launcher.

---

src/main/java/org/spin/grpc/service/DictionaryServiceImplementation.java

1. Login with GardenAdmin.
2. Open `Financial Report` window.
3. Open browser console and see that the query window is broken.
https://user-images.githubusercontent.com/20288327/169374418-686a4767-308b-4dd3-9711-7ae43de850d3.mp4
https://user-images.githubusercontent.com/20288327/169373096-e0741b5b-0b1d-46e6-806b-1b25a215fde2.mp4
Resonse:
```json
{
"code": 500,
"result": "Cannot read field \"TableName\" because \"info\" is null\nCannot read field \"TableName\" because \"info\" is null"
}
```

fix: Lookup reference with UserElement1_ID.

---

src/main/java/org/spin/grpc/service/UserInterfaceServiceImplementation.java

1. Login with GardenAdmin.
2. Open `Process Orders` process.
3. Fill `Document Status` query criteria.
https://user-images.githubusercontent.com/20288327/169396296-18216491-b196-4548-8d93-8836b5499ba1.mp4
In the query limit sql used an offset of 2, when it should be zero unless you explicitly send it the page number.

fix: Smart Browser empty search.

---

src/main/java/org/spin/base/util/RecordUtil.java
src/main/java/org/spin/grpc/service/UserInterfaceServiceImplementation.java

When a Smart Browser has context_attributes, the request for records generates error
```bash
curl 'http://localhost:8080/api/adempiere/user-interface/smart-browser/browser-items?token=be50159c-29c9-4968-9527-cab667fcaa55&language=en' \
-X POST \
--data-raw '{"uuid":"8aaeea60-fb40-11e8-a479-7a0060f0aa01","filters":[],"context_attributes":[{"key":"C_PaySelection_ID","value":100}]}'
```
```log
===========> UserInterfaceServiceImplementation.listBrowserItems: org.postgresql.util.PSQLException: ERROR: syntax error at or near ")"
Position: 113, SQL=SELECT COUNT(*)  FROM C_PaySelectionLine WHERE psl.C_PaySelectionLine_ID=C_PaySelectionLine.C_PaySelectionLine_ID) AS "DisplayColumn_PSL_C_PaySelectionLine_ID", (SELECT NVL(C_PaySelection.DocumentNo,'')||' - …
```

fix: Count SQL Aliases and pagination.

---

src/main/java/org/spin/base/util/DictionaryUtil.java
src/main/java/org/spin/grpc/service/DictionaryServiceImplementation.java
src/main/java/org/spin/grpc/service/UserInterfaceServiceImplementation.java
src/main/proto/business.proto

1. Expand `Open Item` menu.
2. Open `Generate Payment Selection (From Invoice)`
https://user-images.githubusercontent.com/20288327/171664982-fc60601b-e071-49bc-afac-e27ea06972d6.mp4
https://user-images.githubusercontent.com/20288327/171664987-528f88f5-7548-406a-ac84-7616ff511702.mp4
In the backend it was looking for the default value of the `Bank Account` field, but since it was not in the dictionary definition it returned empty values.
In the context of the session we have the value in the `Bank Account` field, so it should be automatically set, overwriting the possible default value in case of having it.
Also, when changing the value of this field, all the fields that are dependent on it, such as the `Currency` and `Current Balance` fields, must …

feat: Add value to overwrite default value.

---

src/main/java/org/spin/base/util/DictionaryUtil.java
src/main/java/org/spin/grpc/service/DictionaryServiceImplementation.java
src/main/java/org/spin/grpc/service/UserInterfaceServiceImplementation.java
src/main/proto/dictionary.proto

When opening a window with multiple tabs, in this case `View` and querying the data of tabs such as child tabs that do not have closing where but with link column or with parent column, it does not perform the records filter correctly.
1. Open `View` window.
2. Show grid records in `View Definition` tab.
3. Change record in `View` tab.
https://user-images.githubusercontent.com/20288327/172665121-2f08589a-53ef-4b01-97e9-0c1fe09b35d6.mp4
https://user-images.githubusercontent.com/20288327/172664675-82438fb5-d336-4305-a67e-d4a7ff23d3fc.mp4
http://localhost:8080/api/adempiere/user-interface/window/entities?window_uuid=a521b0ee-fb40-11e8-a479-7a0060f0aa01&tab_uuid=a4a2b050-fb40-11e8-a479-7a0060f0aa01&context_attributes[]={%22value%22:50043,%22key%22:%22AD_View_ID%22}&search_value=&page_size=15&t …

fix: Filter tab entities with link column.

---

src/main/java/org/spin/base/util/DictionaryUtil.java
src/main/java/org/spin/grpc/service/UserInterfaceServiceImplementation.java

When zoom windows associated on smart browser selection:
```json
{
"code": 500,
"result": "org.postgresql.util.PSQLException: ERROR: syntax error at or near \"AND\"\n  Position: 5262, SQL=SELECT COUNT(*)  FROM C_Order AS C_Order LEFT JOIN C_DocType AS C_DocTypeTarget_ID_C_DocType ON(C_DocTypeTarget_ID_C_DocType.C_DocType_ID = C_Order.C_DocTypeTarget_ID) LEFT JOIN C_DocType_Trl AS C_DocTypeTarget_ID_C_DocType_Trl ON(C_DocTypeTarget_ID_C_DocType_Trl.C_DocType_ID = C_DocTypeTarget_ID_C_DocType.C_DocType_ID AND C_DocTypeTarget_ID_C_DocType_Trl.AD_Language = 'es_MX') LEFT JOIN C_BPartner AS Bill_BPartner_ID_C_BPartner ON(Bill_BPartner_ID_C_BPartner.C_BPartner_ID = C_Order.Bill_BPartner_ID) LEFT JOIN C_BPartner_Location AS Bill_Location_ID_C_BPartner_Location …
```

fix: Zoom Window of Smart Browser selection.

---

src/main/java/org/spin/base/util/DictionaryUtil.java

1. Open `Business Partner` window and set record.
2. Change multi records in `Customer Accounting` tab.
3. See without records.
4. Select to `Location` tab and change to multi record.
3. See without records.
https://user-images.githubusercontent.com/20288327/174104804-ea8b1277-e789-42ba-895d-363833e12bcf.mp4
https://user-images.githubusercontent.com/20288327/174104824-118aa9bc-a6b1-4df9-b2ba-ae54273ee675.mp4
- Your OS: Kubuntut 20.4 x64.
- Web Browser: Mozilla Firefox 101.0.1.
- Node.js version: 14.18.0.
- Yarn version: 1.22.15.
- adempiere-vue version: 4.4.0.
Request:
```bash
curl 'http://localhost:8085/api/adempiere/user-interface/window/entities?window_uuid=a520de12-fb40-11e8-a479-7a0060f0aa01&tab_uuid=a4a06ffc-fb40-11e8-a479-7a0060f0aa01&context …
```

fix: Get entites with where clause.

---

src/main/java/org/spin/grpc/service/BusinessDataServiceImplementation.java

Add record as parameter from which process or report was executed
https://user-images.githubusercontent.com/20288327/174331971-eb4e5229-2a4c-4f0e-aa55-7245958e3316.mp4
1. Login with GardenAdmin.
2. Open `Business Partner` window.
3. Select `Customer` tab.
4. Click in `Open Items` field button.
5. See key column (Business Partner) in report.
cURL request
```shell
curl 'http://localhost:8085/api/adempiere/common/api/process?token=26bf0542-2a72-4808-8974-9d4927bf077a&language=en' \
-X POST \
--data-raw '{"process_uuid":"a42cfc20-fb40-11e8-a479-7a0060f0aa01","table_name":"C_BPartner","uuid":"c3cfeb5f-1b2f-4f4b-a16c-d9cda23f59e1","report_type":"pdf","parameters":[{"key":"DaysDue","value":-99999},{"key":"DaysDue_To","value":99999}]}'
```

feat: Run process add record as parameter.

---

src/main/java/org/spin/base/util/RecordUtil.java
src/main/java/org/spin/grpc/service/AccessServiceImplementation.java
src/main/java/org/spin/grpc/service/BusinessDataServiceImplementation.java
src/main/java/org/spin/grpc/service/CoreFunctionalityImplementation.java
src/main/java/org/spin/grpc/service/LogsServiceImplementation.java
src/main/java/org/spin/grpc/service/PointOfSalesServiceImplementation.java
src/main/java/org/spin/grpc/service/UpdateImplementation.java
src/main/java/org/spin/grpc/service/UserInterfaceServiceImplementation.java
src/main/java/org/spin/grpc/service/WebStoreServiceImplementation.java
src/main/java/org/spin/grpc/service/WorkflowServiceImplementation.java

Currently in the frontend the first page 1 is handled, however in the backend the first page is 0.
Provisionally it was solved in the frontend by subtracting -1 from the current page, but when new implementations were added, and more functionalities where the page number was involved, inconsistencies were created.
Now in both, backend and frontend, both handle as first page number 1.

fix: Set and get correct page number of records.

---

src/main/java/org/spin/base/util/ValueUtil.java

Currently the button type fields are not returning value if they have.
1. Open `Business Partner` window.
2. Select any record without employee check.
3. Run `Link Organization` process.
See button field `Link Organization` with record.
http://localhost:8085/api/adempiere/user-interface/window/entities?window_uuid=a520de12-fb40-11e8-a479-7a0060f0aa01&tab_uuid=a49fca34-fb40-11e8-a479-7a0060f0aa01&filters[]={%22value%22:117,%22column_name%22:%22C_BPartner_ID%22}&page_token=bd04e22d-7f3d-4143-8f6f-bc049b16861f-1&page_size=15&token=bd04e22d-7f3d-4143-8f6f-bc049b16861f&language=en
https://github.com/solop-develop/frontend-default-theme/pull/57
TODO: Add displayed value.

fix: Return value on field button.

---

src/main/java/org/spin/grpc/service/BusinessDataServiceImplementation.java

Smart Browser without table:
If you do not have a table configured in the smart browser and you send the request to delete it, it should throw an error on the server:
https://user-images.githubusercontent.com/20288327/179839263-31f8eb7b-172d-4f05-8070-3fea181441c1.mp4
If you do not have a table configured in the smart browser, the delete option should not be enabled:
https://user-images.githubusercontent.com/20288327/179839259-e8ab5181-f88e-427f-a23d-47c397ecce89.mp4
- Your OS: Kubuntut 20.4 x64.
- Web Browser: Mozilla Firefox 101.0.1.
- Node.js version: 14.18.0.
- Yarn version: 1.22.15.
- adempiere-vue version: 4.4.0.
fixes https://github.com/solop-develop/frontend-core/issues/128

fix: SmartBrowser delete entity without table.

---

src/main/java/org/spin/base/util/RecordUtil.java
src/main/java/org/spin/grpc/service/CoreFunctionalityImplementation.java

The number of records per page set on the client side is 15, which must match on the server side, additionally when you go to the second page you never get records because the calculation of the page number is incorrect.
https://user-images.githubusercontent.com/20288327/180312005-37b28b3c-c3b4-42b6-b06d-6a631e65e1a2.mp4

fix: Business partner pagination.

---

src/main/java/org/spin/grpc/service/BusinessDataServiceImplementation.java
src/main/java/org/spin/grpc/service/UserInterfaceServiceImplementation.java

1. Open `User` window.
2. Show `Business Partner` field.
A. Without save changes.
1. Select a record without `Business Partner`.
2. Set any `Business Partner`.
B. Without clear displayed value.
1. Select a record with `Business Partner`.
2. Click on `New`.
https://user-images.githubusercontent.com/20288327/180478646-5ec2e1ae-4ade-474e-8b01-f04c3324eb27.mp4
https://user-images.githubusercontent.com/20288327/180478650-9c22606a-db49-4c79-abb4-cc047f7a6eac.mp4
A. When fill `Business Partner` field, change value and `Save` are displayed.
B. When clic on `New` button, clear old set value.
- Your OS: Kubuntut 20.4 x64.
- Web Browser: Mozilla Firefox 101.0.1.
- Node.js version: 14.18.0.
- Yarn version: 1.22.15.
- adempiere-vue version: 4.4.0.
fixes: …

fix: Business Partner Info displayed value.

---

build.gradle
src/main/java/org/spin/grpc/service/DictionaryServiceImplementation.java

```log
Exception in thread "grpc-default-executor-4" java.lang.IncompatibleClassChangeError: Method 'io.vavr.collection.List io.vavr.collection.List.ofAll(java.lang.Iterable)' must be Methodref constant
at org.compiere.util.Login.getAuthenticatedUserId(Login.java:308)
at org.spin.grpc.service.AccessServiceImplementation.getUserId(AccessServiceImplementation.java:289)
at org.spin.grpc.service.AccessServiceImplementation.createSession(AccessServiceImplementation.java:314)
at org.spin.grpc.service.AccessServiceImplementation.runLogin(AccessServiceImplementation.java:102)
at org.spin.grpc.util.SecurityGrpc$MethodHandlers.invoke(SecurityGrpc.java:728)
at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:171)
at …
```

fix: io.vavr lib.

---

src/main/java/org/spin/base/util/ConvertUtil.java
src/main/java/org/spin/grpc/service/PointOfSalesServiceImplementation.java

- Edit quantity only no longer removes the value set in the discount line.
- Edit quantity if discounted totals the discount of the order.
- Edit price only no longer removes the value set in the discount line.
- Add line with the same product updates the order discount total if that line is already discounted.
https://user-images.githubusercontent.com/20288327/186472163-4c9328ca-cee5-4aeb-b0be-a025f606bbac.mp4

fix: POS Discount order line.

---

src/main/java/org/spin/grpc/service/PointOfSalesServiceImplementation.java

POS.AllocateSellerNotAllowed
POS.ApplyDiscountNotAllowed
POS.CashClosingNotAllowed
POS.CashOpeningNotAllowed
POS.CashWithdrawalNotAllowed
POS.CollectOrderNotAllowed
POS.ConfirmShipmentByOrderNotAllowed
POS.ConfirmShipmentNotAllowed
POS.CreateCustomerNotAllowed
POS.CreateOrderNotAllowed
POS.DiscountAmtToleranceExceeded
POS.MaximumDiscountAllowedExceeded
POS.ModifyDiscountAllowed
POS.ModifyPriceNotAllowed
POS.ModifyQuantityNotAllowed
POS.PreviewDocumentNotAllowed
POS.PrintDocumentNotAllowed
POS.RefundAmtToleranceExceeded
POS.ReturnOrderNotAllowed
POS.SalesRepAssigned
POS.WriteOffAmtToleranceExceeded

fix: POS generic message ActionNotAllowedHere.

---

src/main/java/org/spin/grpc/service/WorkflowServiceImplementation.java

http://0.0.0.0:8085/api/adempiere/workflow/document-actions?uuid=create-new&table_name=R_Request&pageToken=&pageSize=0&token=ce190db2-11b8-4bf8-baf2-45c1da98646e&language=es
```log
===========> WorkflowServiceImplementation.listDocumentActions: Cannot invoke "org.compiere.model.PO.get_ValueAsString(String)" because "entity" is null [30]
```
```log
===========> WorkflowServiceImplementation.listDocumentActions: Error:  PO * No encontrado * [37]
```

fix: WF document action entity and record key.

---

src/main/java/org/spin/base/util/ConvertUtil.java

Fix null pointer exception with convert line.
https://user-images.githubusercontent.com/20288327/188212577-5a119802-b4dc-4a26-9a95-c655615de437.mp4
The average unit record, `Each` has no value in the `Symbol` field.

fix: POS Validate null on Product Conversion and Unit of Measure.

---

src/main/java/org/spin/grpc/service/AccessServiceImplementation.java

1. Run login.
2. Get session.
http://localhost:8085/api/adempiere/user/session?token=25733eea-10e2-456c-aad1-7c52a9f5cd86&language=es
Log on backend:
```log
===========> AccessServiceImplementation.convertUserInfo: null [30]
===========> AccessServiceImplementation.convertUserInfo: null [30
```

fix: Warning null on convertUserInfo.

---

src/main/java/org/spin/grpc/service/GeneralLedgerServiceImplementation.java

Request:
http://localhost:8085/api/adempiere/general-ledger/save-accounting-combination?http://20.12.0.113:8085/api/adempiere/general-ledger/accounting-combination?id=234&token=9d8439e8-cfe5-4d61-99a3-fe5d4b1a537d&language=esattributes[]=%7B%22value%22:11,%22key%22:%22AD_Org_ID%22%7D&attributes[]=%7B%22value%22:50025,%22key%22:%22Account_ID%22%7D&attributes[]=%7B%22value%22:100,%22key%22:%22C_Project_ID%22%7D&attributes[]=%7B%22value%22:101,%22key%22:%22C_Campaign_ID%22%7D&context_attributes[]=%7B%22value%22:11,%22key%22:%22AD_Org_ID%22%7D&context_attributes[]=%7B%22value%22:50025,%22key%22:%22Account_ID%22%7D&context_attributes[]=%7B%22key%22:%22C_AcctSchema_ID%22,%22value%22:101%7D&token=9d8439e8-cfe5-4d61-99a3-fe5d4b1a537d&language=es
Response:
```json
{
"code": 500,
"result": "Cannot …
```

fix: Save accouting combination without alias.

---

src/main/java/org/spin/base/util/DictionaryUtil.java
src/main/java/org/spin/base/util/ReferenceUtil.java
src/main/java/org/spin/grpc/service/UserInterfaceServiceImplementation.java

If field Accouting Combination type has a default value will now return the expected structure instead of empty values
**Request:**
http://0.0.0.0:8085/api/adempiere/user-interface/window/default-value?field_uuid=8cebe6ca-fb40-11e8-a479-7a0060f0aa01&id=3916&value=234&token=7ce97e21-7704-4810-9260-4cf4c0a084b0&language=es
**Response:**
```json
{
"code": 200,
"result": {
"id": 234,
"uuid": "b79a94f4-6a04-4c0f-8293-8f29af5e4e29",
{
"value": "HQ-12110-_-_-_-_"
},
{
"value": 234
},
{
"key": "UUID",
"value": "b79a94f4-6a04-4c0f-8293-8f29af5e4e29"
}
]
}
}
```

fixed: Default value on accouting combination field.

---

src/main/java/org/spin/grpc/service/GeneralLedgerServiceImplementation.java

https://user-images.githubusercontent.com/20288327/191953106-012f03d8-1909-421b-b0b7-d9cabbdd297e.mp4
https://user-images.githubusercontent.com/20288327/191953093-14d4ea92-8077-4ec9-bb70-c17f6a35c656.mp4
Request:
http://0.0.0.0:8085/api/adempiere/general-ledger/accounting-combinations?context_attributes[]=%7B%22key%22:%22C_AcctSchema_ID%22,%22value%22:101%7D&context_attributes[]=%7B%22key%22:%22AD_Org_ID%22,%22value%22:11%7D&context_attributes[]=%7B%22key%22:%22Account_ID%22,%22value%22:518%7D&filters[]=%7B%22column_name%22:%22AD_Org_ID%22,%22value%22:11%7D&filters[]=%7B%22column_name%22:%22Account_ID%22,%22value%22:518%7D&filters[]=%7B%22column_name%22:%22Alias%22,%22value%22:%22hq+project+%22%7D&page_token=7ce97e21-7704-4810-9260-4cf4c0a084b0-1&pa …

fixed: Accouting Combination ignore alias filter.

---

src/main/java/org/spin/base/util/DictionaryUtil.java
src/main/java/org/spin/grpc/service/UserInterfaceServiceImplementation.java

Currently we were trying to generate the display column for fields that are not supported such as:
- Location.
- Product attributes.
- Location. 
Currently only are supported:
- Accounting combination.
- Table.
- Table direct.
- List.
http://localhost:8085/api/adempiere/business-partner/grid?process_parameter_uuid=a43d0d9a-fb40-11e8-a479-7a0060f0aa01&table_name=C_BPartner&filters[]=%7B%22column_name%22:%22IsCustomer%22,%22value%22:true%7D&page_size=15&page_token=16df16fe-5bd5-44dc-95ad-bc63ed3a7556-1&token=16df16fe-5bd5-44dc-95ad-bc63ed3a7556&language=es

fixed: Ignore unsupported Display Column lookups.

---

src/main/java/org/spin/base/util/ConvertUtil.java

When creating an order, or listing an order, and the product has quantity available with decimal points in the precision greater than 2 digits (123456.123) generates the following message:
```log
===========> PointOfSalesServiceImplementation.createOrderLine: Rounding necessary [875]
===========> PointOfSalesServiceImplementation.createOrderLine: Rounding necessary [875]
```

fix: POS rouding on available quantity.

---

src/main/java/org/spin/grpc/service/AccessServiceImplementation.java
src/main/java/org/spin/grpc/service/BusinessDataServiceImplementation.java
src/main/java/org/spin/grpc/service/BusinessPartnerServiceImplementation.java
src/main/java/org/spin/grpc/service/CoreFunctionalityImplementation.java
src/main/java/org/spin/grpc/service/DashboardingServiceImplementation.java
src/main/java/org/spin/grpc/service/DictionaryServiceImplementation.java
src/main/java/org/spin/grpc/service/InOutServiceImplementation.java
src/main/java/org/spin/grpc/service/InvoiceServiceImplementation.java
src/main/java/org/spin/grpc/service/LogsServiceImplementation.java
src/main/java/org/spin/grpc/service/OrderServiceImplementation.java
src/main/java/org/spin/grpc/service/PaymentServiceImplementation.java
src/main/java/org/spin/grpc/service/PayrollActionNoticeServiceImplementation.java
src/main/java/org/spin/grpc/service/PointOfSalesServiceImplementation.java
src/main/java/org/spin/grpc/service/ProductServiceImplementation.java
src/main/java/org/spin/grpc/service/UpdateImplementation.java
src/main/java/org/spin/grpc/service/UserInterfaceServiceImplementation.java
src/main/java/org/spin/grpc/service/WebStoreServiceImplementation.java
src/main/java/org/spin/grpc/service/WorkflowServiceImplementation.java

When an error is generated, the message returned is always duplicated, e.g:
https://user-images.githubusercontent.com/20288327/194146850-49206ce8-0d87-4a48-b58b-6ef5a555f3b9.mp4
Before changes:
```json
{
"code": 500,
"result": "ERROR: duplicate key value violates unique constraint \"c_bpartner_value\"\n  Detail: Key (ad_client_id, value)=(11, Wood, Inc) already exists.\nERROR: duplicate key value violates unique constraint \"c_bpartner_value\"\n  Detail: Key (ad_client_id, value)=(11, Wood, Inc) already exists."
}
```
After changes:
```json
{
"code": 500,
"result": "ERROR: duplicate key value violates unique constraint \"c_bpartner_value\"\n  Detail: Key (ad_client_id, value)=(11, Wood, Inc) already exists."
}
```
As seen in the augmentDescription method, exactly in line 481, to the …

fix: Duplicated error message.

---

src/main/java/org/spin/base/util/DictionaryUtil.java
src/main/java/org/spin/base/util/ReferenceUtil.java

When address is inverse on country client is error
http://0.0.0.0:8085/api/adempiere/business-partner/grid?field_uuid=8cef47c0-fb40-11e8-a479-7a0060f0aa01&table_name=C_BPartner&filters[]=%7B%22column_name%22:%22IsCustomer%22,%22value%22:true%7D&page_size=15&page_token=aef4a788-bc50-443a-beb5-e3d3dbc0dde0-1&token=aef4a788-bc50-443a-beb5-e3d3dbc0dde0&language=es
```json
{
"code": 200,
"result": {
"record_count": 6,
"records": [
{
"id": 117,
"uuid": "b7bafd8e-ae3b-4bbc-9a0d-d47fdbef390f",
"table_name": "C_BPartner"
}
]
}
}
```
https://github.com/solop-develop/frontend-core/issues/528

fix: Display column on location address inverse.

---

src/main/java/org/spin/grpc/service/AccessServiceImplementation.java

```bash
curl --location --request POST 'http://0.0.0.0:8085/api/adempiere/user/login?language=es' \
--data-raw '{
"username": "SuperUser",
"password": "System",
"role_uuid": "non-existent-role-uuid"
}'
```
```json
{
"code": 500,
"result": ""
}
```
```log
===========> AccessServiceImplementation.runLogin: null [25]
```
```json
{
"code": 200,
"result": "b1badcd7-b28d-4294-b484-27b6cc786d9b"
}
```
Previously if a login was made with a role uuid that did not exist in the database, it generated an error, now if it fails, it logs in with the default role.

fix: Login with Role UUID nonexistent.

---

src/main/java/org/spin/grpc/service/DictionaryServiceImplementation.java

When loaded window with dependencies in other tab generate NPE:
```log
DictionaryServiceImplementation.getField: Cannot invoke "java.util.List.stream()" because "fieldsList" is null [505]
```

fix: Null Pointer Exception Dependent Fields.

---

src/main/java/org/spin/grpc/service/DictionaryServiceImplementation.java

Translation tabs are not rendered on the client, so if you add fields dependent on a translation tab you will not get it on the client, so warnings will be displayed in the browser console.
https://user-images.githubusercontent.com/20288327/199052317-f44916d8-62ed-450b-8976-a763182c3023.mp4
https://user-images.githubusercontent.com/20288327/199052308-085b5c7b-0fc4-49a2-baea-2bcda71e3de2.mp4

 fix: Dependencies fields on translation tab.

---

src/main/java/org/spin/base/util/ValueUtil.java
src/main/proto/base_data_type.proto

When a search is made for a text field and the LIKE operator was not sent, it takes EQUAL as the default operator, so an exact search had to be made.
A default operator called VOID is added, which when set, searches for the default operator according to the display type, for number type fields the EQUAL, for text type fields the LIKE operator.
https://user-images.githubusercontent.com/20288327/201457227-3583d223-1404-4c01-8f82-6983d72d3658.mp4
Fixes https://github.com/solop-develop/frontend-core/issues/462

fix: Search text with like as default operator.

---

src/main/java/org/spin/grpc/service/FileManagementServiceImplementation.java
src/main/proto/file_management.proto

http://0.0.0.0:8085/api/adempiere/user-interface/component/resource/exists-attachment?table_name=C_Greeting&record_id=1000003&record_uuid=7fd879af-78db-446e-9b92-1e893f03541b&token=71ab66dc-637f-43f9-a4e1-033d1c447956&language=es
```bash
curl 'http://0.0.0.0:8085/api/adempiere/user-interface/component/resource/exists-attachment?table_name=C_Greeting&record_id=1000003&record_uuid=7fd879af-78db-446e-9b92-1e893f03541b&token=71ab66dc-637f-43f9-a4e1-033d1c447956&language=es' \
-H 'Accept: application/json, text/plain, */*'
```
```json
{
"code": 200,
"result": 3
}
```
fixes https://github.com/solop-develop/frontend-core/issues/488

feat: Exists attachment on record.

---

src/main/java/org/spin/base/util/ConvertUtil.java
src/main/java/org/spin/grpc/service/LogsServiceImplementation.java
src/main/java/org/spin/grpc/service/UserInterfaceServiceImplementation.java
src/main/proto/logs.proto

- Add user information on chat entries.
- Add new service to exists chat entries:
Request
http://localhost:8085/api/adempiere/user/log/exists-chat-entries?table_name=C_BP_Group&record_id=103&record_uuid=f1bac04e-2aa3-44a2-86c4-cf1f28415eab&token=0cfd52ab-de38-4bc4-b81f-dbdac2ddcb35&language=es
Response
```json
{
"code": 200,
"result": 4
}
```

feat: Add exists chat entries.

---

src/main/java/org/spin/grpc/service/UserInterfaceServiceImplementation.java

http://localhost:8085/api/adempiere/user-interface/window/default-value?field_uuid=8d8b5bba-fb40-11e8-a479-7a0060f0aa01&id=59390&value=%27DR%27&token=23b81174-fa45-40dc-8583-b176673f85eb&language=en&ts=1675266803201
```json
{
"code": 500,
"result": ""
}
```
```log
===========> UserInterfaceServiceImplementation.getDefaultValue: null [206]
```
https://user-images.githubusercontent.com/20288327/216104449-037e12a6-9680-45be-a9da-634a1eeaa9d1.mp4
https://user-images.githubusercontent.com/20288327/216104401-fc7422dc-5eb5-4bc3-a2c7-b6258570e9db.mp4
fixes https://github.com/solop-develop/frontend-core/issues/818

fix: Get default value with single quotes.

---

src/main/java/org/spin/grpc/service/UserInterfaceServiceImplementation.java

It is validated that the quotation mark at the beginning is equal to the quotation mark at the end, that is to say, if it starts with a single quotation mark it must end with the same, examples:
* `"DR'`: invalid
* `'DR"`: invalid
* `'DR'`: valid
* `"DR"`: valid
fixes https://github.com/solop-develop/frontend-core/issues/818

fix: Same start quotation with end quotation.

---

src/main/java/org/spin/base/setup/SetupLoader.java
src/main/java/org/spin/server/AllInOneServices.java

if the `database` attribute is not defined in the connection `.yaml` file (default is `resources/standalone.yaml`) a `Java Null Pointer Exception` is generated when trying to start the server without giving relevant information to the user that identifies why the error occurs.

fix: Validate database attribute to standalone.yaml.

---

src/main/java/org/spin/grpc/service/UserInterfaceServiceImplementation.java

```bash
curl --location --request POST 'http://localhost:8085/api/adempiere/user-interface/smart-browser/browser-items?page_token=f266454d-53cc-45a4-9b6a-557796684dff-1&page_size=15&token=f266454d-53cc-45a4-9b6a-557796684dff&language=es&ts=1676060941965' \
--data-raw '{
"uuid": "8aaeeea2-fb40-11e8-a479-7a0060f0aa01",
"filters": [
{
"column_name": "CF_CreateFromType",
"value": "O"
},
{
"column_name": "CF_IsSameWarehouse",
"value": false
},
{
"column_name": "CF_C_Order_ID",
"value": 1000007
}
],
"context_attributes": []
}'
```
```json
{
"code": 200,
"result": {
"record_count": 3,
"records": [
...
]
}
}
```
```json
{
"code": 200,
"result": { …
```

fix: Smart Browser where clause with context columns.

---

.classpath
.settings/org.eclipse.buildship.core.prefs
README.md
src/main/proto/access.proto
src/main/proto/base_data_type.proto
src/main/proto/business_partner.proto
src/main/proto/client.proto
src/main/proto/core_functionality.proto
src/main/proto/dictionary.proto
src/main/proto/enrollment.proto
src/main/proto/file_management.proto
src/main/proto/general_ledger.proto
src/main/proto/in_out.proto
src/main/proto/invoice.proto
src/main/proto/material_management.proto
src/main/proto/order.proto
src/main/proto/payment.proto
src/main/proto/payment_print_export.proto
src/main/proto/payroll_action_notice.proto
src/main/proto/point_of_sales.proto
src/main/proto/product.proto
src/main/proto/time_control.proto
src/main/proto/update_center.proto
src/main/proto/warehouse_management.proto
src/main/proto/web_store.proto

- Remove `option objc_class_prefix = "HLW";` from `.proto` files.
- Set gradle 7.2 version on eclipse IDE.
- Set jdk 11 version on eclipse IDE.
fixes https://github.com/solop-develop/backend/issues/216

fix: Eclipse IDE objec-class-prefix error.

---

src/main/java/org/spin/grpc/service/WorkflowServiceImplementation.java

http://localhost:8085/api/adempiere/workflow/document-statuses?uuid=0e824f4a-b186-48c7-b51e-5cb821e281da&table_name=M_Requisition&page_token=&page_size=0&token=e440e31d-66dd-46f6-982e-6d74a8d91b79&language=es&ts=1677780160829
```log
-----------> MRequisition.get_Value: Column not found - IsSOTrx [153]
```
http://localhost:8085/api/adempiere/workflow/document-actions?uuid=0e824f4a-b186-48c7-b51e-5cb821e281da&table_name=M_Requisition&page_token=&page_size=0&token=e440e31d-66dd-46f6-982e-6d74a8d91b79&language=es&ts=1677780160828
```
-----------> MRequisition.get_Value: Column not found - IsSOTrx [159]
```

fix: Document statuses/actions without isSOTrx column.

---

src/main/java/org/spin/authentication/BearerToken.java

Token is crop with `BEARER_TOKEN` char length.

fix: Token without bearer token.

---

src/main/java/org/spin/base/setup/SetupLoader.java
src/main/java/org/spin/server/AllInOneServices.java
tools/ADempiere Backend.launch

- Set in the eclipse launcher the default connection file (`resources/standalone.yaml`).
- Set default connection file if argument is empty on `AllInOnseServices`.
- If the connection file is established but does not exist, throw exception on `SetupLoader`.

fix: Load connection file.

---

src/main/java/org/spin/grpc/service/ExpressReceiptServiceImplementation.java
src/main/java/org/spin/grpc/service/ExpressShipmentServiceImplementation.java

```json
{
"code": 500,
"result": "org.postgresql.util.PSQLException: No value specified for parameter 2., SQL=SELECT COUNT(*) FROM C_Order WHERE (IsSOTrx='Y' AND C_BPartner_ID = ? AND DocStatus IN ('CL','CO')AND EXISTS(SELECT 1 FROM C_OrderLine ol WHERE ol.C_Order_ID = C_Order.C_Order_ID AND COALESCE(ol.QtyOrdered, 0) - COALESCE(ol.QtyDelivered, 0) > 0)) AND AD_Client_ID=?"
}
```

fix: List Orders with Business Partner.

---

src/main/java/org/spin/grpc/service/PointOfSalesServiceImplementation.java

```log
PointOfSalesServiceImplementation.createOrder: org.postgresql.util.PSQLException: ERROR: trailing junk after parameter at or near "$1A"
Position: 215, SQL=SELECT AD_Client_ID,AD_Org_ID,Created,CreatedBy,IsActive,M_PriceList_Version_ID,M_ProductPrice_ID,M_Product_ID,PriceLimit,PriceList,PriceStd,UUID,Updated,UpdatedBy FROM M_ProductPrice WHERE (M_PriceList_Version_ID=?AND EXISTS(SELECT 1 FROM C_OrderLine ol WHERE ol.C_Order_ID = 1000035 AND ol.M_Product_ID = M_ProductPrice.M_Product_ID) AND EXISTS(SELECT 1 FROM C_OrderLine ol WHERE ol.C_Order_ID = 1000035 AND ol.M_Product_ID = M_ProductPrice.M_Product_ID)) [45]
```
fixes https://github.com/solop-develop/frontend-core/issues/961
Adempiere related changes to fixes https://github.com/adempiere/adempiere/pull/4094

fix: POS Set Price List Version on Sales Order.

---

src/main/proto/express_movement.proto
src/main/proto/express_receipt.proto
src/main/proto/express_shipment.proto

```proto
import "proto/business.proto";
import "proto/core_functionality.proto";
```
on:
- Express Movement.
- Express Receipt.
- Express Shipment.

fix: Remove unused imports on express forms.

---

src/main/proto/bank_statement_match.proto

The import `core_functionality.proto` is unused on `src/main/proto/bank_statement_match.proto` file.

fix: Unused import on bank statement march proto.

---

.github/workflows/publish.yml

el paso `Publish to Maven Repository` depende del paso `Check if docker hub registry information was set on secrets` cuando de `Check if maven registry information was set on secrets`.

fix: CI with github action.

---

.github/workflows/publish.yml

Update `Publish Project` workflow, github action `docker/build-push-action` from v2 to v4, to remove warning in `Push docker alpine image to Docker Hub` step.

feat: CI/CD Update GitHub actions docker build.

---

src/main/java/org/spin/grpc/service/DashboardingServiceImplementation.java

Currently we do not have the total number of records, besides listing dasboards associated to the role that are deactivated in the table `AD_Dashboard_Access`.
http://localhost:8085/api/adempiere/dashboard/dashboards?role_id=102&role_uuid=ca49b44b-651a-4740-ab65-83da2b5dbea3&page_size=15&language=es&ts=1682022632970
```json
{
"code": 200,
"result": {
"record_count": 9,
"records": [
...
]
}
}
````
fixes https://github.com/solop-develop/frontend-core/issues/979

fix: List only active Dashboard access Role.

---

src/main/java/org/spin/base/util/SessionManager.java

When the server is restarted the first request associated with a token never gets the session, however when the same request is sent again it receives a successful response because it does get the session.
```json
{
"code": 500,
"result": "@AD_Session_ID@ @NotFound@"
}
```
fixes https://github.com/solop-develop/frontend-core/issues/928

fix: Session Not Found before restart server.

---

src/main/java/org/spin/grpc/service/PaymentAllocationServiceImplementation.java

With the ResultSet.getBoolean method always returns a null value since in the database it is stored as a string ('Y' or 'N') and this is compatible to parse data 1, 0, true, 'true', false, 'false', 'on, 'off',

fix: DB boolean values on Payment Allocation form.

---

src/main/java/org/spin/form/match_po_receipt_invoice/Util.java
src/main/java/org/spin/grpc/service/MatchPOReceiptInvoiceServiceImplementation.java

* Add id value.
* Fix order `ValueColumn`, was `0` when it should be `2`.
```json
{
"code": 200,
"result": {
"records": [
{
"id": 0,
"uuid": "",
"table_name": "",
"values": {
"DisplayColumn": "Invoice",
"ValueColumn": 0
}
},
{
"id": 1,
"uuid": "",
"table_name": "",
"values": {
"DisplayColumn": "Shipment/Receipt",
"ValueColumn": 1
}
},
{
"id": 2,
"uuid": "",
"table_name": "",
"values": {
"DisplayColumn": "Order",
"ValueColumn": 2
}
}
]
}
}
```

fix: Match PO Receipt Invoice form match type values.

---

src/main/java/org/spin/grpc/service/DashboardingServiceImplementation.java

if the window chart parameter are deactivated, it is still considered to send them as filters in the vue client.

fix: Show inactives Window Chart Parameters.

---

src/main/java/org/spin/grpc/service/BusinessDataServiceImplementation.java

When is run process associated in two or more tabs on same windows, always takes the uuid of the first tab it is associated with.
fixes https://github.com/solop-develop/frontend-core/issues/1014

fix: Run process without record id.

---

src/main/java/org/spin/grpc/service/UserInterfaceServiceImplementation.java

```bash
curl --location 'http://localhost:8085/api/adempiere/user-interface/window/default-value?field_uuid=8d8b5bba-fb40-11e8-a479-7a0060f0aa01&id=59390&value=%27DR%22&token=23b81174-fa45-40dc-8583-b176673f85eb&language=en&ts=1675265155138' \
--header 'Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiIxMDAxMjk5IiwiQURfQ2xpZW50X0lEIjoxMSwiQURfT3JnX0lEIjoxMDAwMDA1LCJBRF9Sb2xlX0lEIjoxMDIsIkFEX1VzZXJfSUQiOjEwMSwiTV9XYXJlaG91c2VfSUQiOjAsIkFEX0xhbmd1YWdlIjoiZW5fVVMiLCJpYXQiOjE2ODU2Mzc0NjIsImV4cCI6MTY4NTcyMzg2Mn0.N1phU7FvJHLeTlVHClMFXMEiX3Z1fd_OBPQ2r0xzfrc'
```
```log
===========> UserInterfaceServiceImplementation.getDefaultValue: null [338]
```
```json
{
"code": 500,
"result": ""
}
```
```json
{
"code": 200,
"result": {
"id": 0,
"uuid": …
```

fix: Default value starts with ' and ends with ".

---

src/main/java/org/spin/base/util/SessionManager.java

Add `AD_User_ID` as sales representative on context
See:
https://github.com/solop-develop/adempiere-box/blob/09b49fffb5cea7863fcc6feec125f32f9d27bee6/base/src/org/compiere/util/Login.java#L430-L431
fixes https://github.com/solop-develop/frontend-core/issues/841

fix: Sales Representative on global context.

---

src/main/java/org/spin/base/util/ContextManager.java
src/main/java/org/spin/grpc/service/UserInterfaceServiceImplementation.java

If the column that triggers the callout is `C_BPartner_ID`, whose value is 10000, but it is sent in the context attributes `C_BPartner_ID = 5000`, in the return context it will still have the value 5000 when it should be 1000.
It also does not take into account the context that is emptied, which may be necessary for fields that depend on another for their value such as `C_BPartner_Location_ID`.
fixes https://github.com/solop-develop/frontend-core/issues/636

fix: Callout context, return clear empty values.

---

.github/workflows/ci.yml
build.gradle

fix: Gradle CI with base group id.

---

src/main/java/org/spin/grpc/service/WorkflowServiceImplementation.java

- Remove duplicated method `convertWorkflow` by `org.spin.base.util.WorkflowUtil.convertWorkflowDefinition`.
- Validate id and uuid.

feat: Remove duplicated method `convertWorkflow`.

---

src/main/java/org/spin/grpc/service/DictionaryServiceImplementation.java

Although the table name is sent, it is not considered for the `MTable` instance.
http://localhost:8085/api/adempiere/dashboard/window/exists-dashboards?tab_id=347&window_id=204&ts=1686794671262
```json
{
"code": 500,
"result": "Llenar campos obligatorios:  Tabla"
}
```

fix: Fill Mandatory Table on general info fields.

---

src/main/java/org/spin/base/db/OperatorUtil.java
src/main/java/org/spin/base/db/WhereUtil.java
src/main/java/org/spin/base/util/RecordUtil.java
src/main/java/org/spin/base/util/ValueUtil.java
src/main/java/org/spin/grpc/service/BusinessDataServiceImplementation.java
src/main/java/org/spin/grpc/service/BusinessPartnerServiceImplementation.java
src/main/java/org/spin/grpc/service/CoreFunctionalityImplementation.java
src/main/java/org/spin/grpc/service/GeneralLedgerServiceImplementation.java
src/main/java/org/spin/grpc/service/InOutServiceImplementation.java
src/main/java/org/spin/grpc/service/InvoiceServiceImplementation.java
src/main/java/org/spin/grpc/service/OrderServiceImplementation.java
src/main/java/org/spin/grpc/service/PaymentServiceImplementation.java
src/main/java/org/spin/grpc/service/ProductServiceImplementation.java
src/main/java/org/spin/grpc/service/UserInterfaceServiceImplementation.java

- Move `src/main/java/org/spin/base/util/OperatorUtil.java` to `src/main/java/org/spin/base/db/OperatorUtil.java`
- Rename and move `src/main/java/org/spin/base/util/QueryUtil.java` to `src/main/java/org/spin/base/db/WhereUtil.java`
- Remove duplicated `convertOperator` method on `src/main/java/org/spin/grpc/service/UserInterfaceServiceImplementation.java` and `src/main/java/org/spin/base/util/ValueUtil.java`, by `src/main/java/org/spin/base/db/OperatorUtil.java`.
- Move `getWhereClauseFromCriteria` method from `src/main/java/org/spin/base/util/ValueUtil.java` to `src/main/java/org/spin/base/db/WhereUtil.java`.

feat: Change `getWhereClauseFromCriteria` and remove duplicated `convertOperator`.

---

src/main/java/org/spin/base/util/ConvertUtil.java
src/main/java/org/spin/base/util/FileUtil.java
src/main/java/org/spin/base/util/RecordUtil.java
src/main/java/org/spin/grpc/service/FileManagementServiceImplementation.java

Move `getResourceFromImageId` and `getResourceUuidFromImageId` methods, from `src/main/java/org/spin/base/util/RecordUtil.java` to `src/main/java/org/spin/base/util/FileUtil.java`

feat: Move `getResourceFromImageId` to `FileUtil` class.

---

src/main/java/org/spin/base/db/OrderByUtil.java
src/main/java/org/spin/base/util/DictionaryUtil.java
src/main/java/org/spin/grpc/service/BankStatementMatchServiceImplementation.java
src/main/java/org/spin/grpc/service/BusinessDataServiceImplementation.java
src/main/java/org/spin/grpc/service/DictionaryServiceImplementation.java
src/main/java/org/spin/grpc/service/MatchPOReceiptInvoiceServiceImplementation.java
src/main/java/org/spin/grpc/service/UserInterfaceServiceImplementation.java

Move `getBrowseOrderBy`, and `getBrowserFieldOrderByPosition` methods, from `src/main/java/org/spin/base/util/DictionaryUtil.java` to `src/main/java/org/spin/base/db/OrderByUtil.java`

feat: Move order by methods to `OrderByUtil`.

---

src/main/java/org/spin/base/db/QueryUtil.java
src/main/java/org/spin/base/util/DictionaryUtil.java
src/main/java/org/spin/grpc/service/BusinessPartnerServiceImplementation.java
src/main/java/org/spin/grpc/service/DictionaryServiceImplementation.java
src/main/java/org/spin/grpc/service/GeneralLedgerServiceImplementation.java
src/main/java/org/spin/grpc/service/InOutServiceImplementation.java
src/main/java/org/spin/grpc/service/InvoiceServiceImplementation.java
src/main/java/org/spin/grpc/service/MaterialManagementServiceImplementation.java
src/main/java/org/spin/grpc/service/OrderServiceImplementation.java
src/main/java/org/spin/grpc/service/PaymentServiceImplementation.java
src/main/java/org/spin/grpc/service/ProductServiceImplementation.java
src/main/java/org/spin/grpc/service/UserInterfaceServiceImplementation.java

Move the next methods:
- `getTableQueryWithReferences`.
- `getTabQueryWithReferences`.
- `getBrowserQuery`.
- `getBrowserQueryWithReferences`
From `src/main/java/org/spin/base/util/DictionaryUtil.java` to `src/main/java/org/spin/base/db/QueryUtil.java` class.

feat: Move query methods to `QueryUtil` class.

---

src/main/java/org/spin/grpc/service/DictionaryServiceImplementation.java

I was looking for the parent table sending the name of the table associated to the tab when it should be in `AD_Tab`.
```sql
SELECT UUID from C_InvoiceTax where C_InvoiceTax_ID = ? AND AD_Client_ID=? Order By C_InvoiceTax_ID
```
```log
===========> DB.getSQLValueString: select UUID from C_InvoiceTax where C_InvoiceTax_ID = ? and AD_Client_ID=? Order By C_InvoiceTax_ID [36]
328
org.postgresql.util.PSQLException: ERROR: column "c_invoicetax_id" does not exist
327
Hint: Perhaps you meant to reference the column "c_invoicetax.c_invoice_id".
326
Position: 37; State=42703; ErrorCode=0
325
at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2675)
324
at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2365)
323
at …
```

fix: Parent tab uuid generates sql exeption.

---

src/main/java/org/spin/base/util/SessionManager.java

The `#ShowAcct` attribute is required to display logic on `Posted` field to accounting features.

fix: `#ShowAcct` on session context.

---

src/main/java/org/spin/grpc/service/DictionaryServiceImplementation.java
src/main/java/org/spin/grpc/service/UserInterfaceServiceImplementation.java

```bash
curl --location --globoff 'http://localhost:8085/api/adempiere/user-interface/window/default-value?context_attributes[]=%7B%22key%22%3A%22AD_Table_ID%22%2C%22value%22%3A318%7D&field_uuid=8d56bba8-fb40-11e8-a479-7a0060f0aa01&id=3890&value=100&ts=1687806196918' \
--header 'Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiIxMDAxNDg0IiwiQURfQ2xpZW50X0lEIjoxMSwiQURfT3JnX0lEIjoxMSwiQURfUm9sZV9JRCI6MTAyLCJBRF9Vc2VyX0lEIjoxMDEsIk1fV2FyZWhvdXNlX0lEIjowLCJBRF9MYW5ndWFnZSI6ImVuX1VTIiwiaWF0IjoxNjg3Nzg5Nzk3LCJleHAiOjE2ODc4NzYxOTd9.KxLqQo_xjLezK0yyMncs80GEFUXlFUZDf11xWH5hL6U'
```
```json
{
"code": 200,
"result": {
"id": 100,
"uuid": "3880ea1a-35c7-4e62-b450-755ac24c4817",
{
"value": "2002-02-22 USD"
},
{
"value": 100
},
{
"key": …
```

feat: Add display column to `Record_ID` as button reference.

---

src/main/java/org/spin/grpc/service/SecurityServiceImplementation.java

1. Login with `GardenAdmin` role and `Spanish` language.
2. Change role to `GardenUser`.
In the client the language is maintained (Spanish), however the data that is loaded with translation from the server is in English.
When inspecting in the context of the session, in the previous session the value was `#AD_Language=es_MX` and the new value is `#AD_Language=en_US`, it should keep the value of the previous session unless explicitly requested to change the language as well.
https://github.com/solop-develop/adempiere-grpc-server/assets/20288327/36c985c5-196d-472b-80dc-562ca3e2abd6

fix: Change role change server language.

---

src/main/java/org/spin/base/db/ParameterUtil.java
src/main/java/org/spin/base/db/WhereClauseUtil.java

When is `NULL` value on list to `IN` or `NOT IN` operator, the search is empty.
With the values `CO`, `NULL`, `CL` generates sql:
```sql
o.DocStatus IN (
'CO',
NULL,
'CL'
)
```
```sql
(UPPER(o.DocumentNo) IN (
UPPER('CO'),
UPPER(''),
UPPER('CL')
)
OR UPPER(o.DocumentNo) IN (SELECT o.DocumentNo WHERE o.DocumentNo IS NULL))
```
Is add restriction:
```sql
OR `columnName` IN (SELECT `columnName` WHERE `columnName` IS NULL)
```
If column is value type string the 
```sql
UPPER(`columnName`)
UPPER(`value`)
```
is added on column name and value.

fix: Empty values with `IN` and `NOT IN` operator.

---

src/main/java/org/spin/grpc/service/WorkflowServiceImplementation.java

Temporarily inactivates the functionality of starting workflows when processing the document action, until the correct functionality is available.

fix: Inactive start workflows when processing document action.

---

src/main/java/org/spin/grpc/service/BusinessDataServiceImplementation.java
src/main/java/org/spin/grpc/service/WorkflowServiceImplementation.java

Sometimes when executing a process or a document action, and it generates an error that is not captured, it may arrive empty so the cause of the error is not identified.
If the error is handled and I return its corresponding message, it is the one that is sent to the client, otherwise it takes the error of the catch.

fix: Run Process/DocAction empty error message.

---

src/main/java/org/spin/grpc/service/WorkflowServiceImplementation.java

When listing the actions on a document that has active workflows, this will generate the error `Active Workflow for this Record exists (complete first): Status`, however to list the document actions this validation should not exist.
This validation was moved to `runDocumentAction` to avoid executing multiple workflows simultaneously on the same document.

fix: Workflow Actions list error if exists wokflow activity.

---

src/main/java/org/spin/grpc/service/FileManagementServiceImplementation.java

https://github.com/solop-develop/adempiere-grpc-server/assets/20288327/59ff60dc-00f4-4216-bf89-296a7083ea43
```log
FileManagementServiceImplementation.setResourceReference: SaveError [915]
org.adempiere.exceptions.AdempiereException: SaveError
at org.compiere.model.PO.saveEx(PO.java:2320)
at org.spin.grpc.service.FileManagementServiceImplementation.lambda$1(FileManagementServiceImplementation.java:457)
at org.compiere.util.Trx.run(Trx.java:529)
at org.compiere.util.Trx.run(Trx.java:497)
at org.spin.grpc.service.FileManagementServiceImplementation.setResourceReference(FileManagementServiceImplementation.java:454)
at org.spin.grpc.service.FileManagementServiceImplementation.setResourceReference(FileManagementServiceImplementation.java:411)
at …
```

fix: `Null Pointer Execption` when save attachment.

---

src/main/java/org/spin/grpc/service/FileManagementServiceImplementation.java

when querying for attachments in the role window with the `System` record having the id `0`, an error is generated.
```bash
curl 'https://api-develop.solopcloud.com/api/adempiere/user-interface/component/resource/exists-attachment?table_name=AD_Role&record_id=0&record_uuid=a48d2596-fb40-11e8-a479-7a0060f0aa01&ts=1689910629327' -H 'Accept: application/json, text/plain, */*'  -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiIxMDAxNzMwIiwiQURfQ2xpZW50X0lEIjoxMSwiQURfT3JnX0lEIjoxMDAwMDA0LCJBRF9Sb2xlX0lEIjoxMDIsIkFEX1VzZXJfSUQiOjEwMSwiTV9XYXJlaG91c2VfSUQiOjAsIkFEX0xhbmd1YWdlIjoiZXNfTVgiLCJpYXQiOjE2ODk4OTE0MzIsImV4cCI6MTY4OTk3NzgzMn0.FfUizGkjbZh3pbi695EGwXir0_HPxHSlgGd57Ybp62I''
```
https://github.com/solop-develop/adempiere-grpc-server/assets/20288327/792978fe-fcdf-4fa3-a2ba-655533aa5e3 …

fix: Exists attachment error with role zero.

---

src/main/java/org/spin/base/dictionary/DictionaryUtil.java
src/main/java/org/spin/grpc/service/BusinessDataServiceImplementation.java
src/main/java/org/spin/grpc/service/DictionaryServiceImplementation.java
src/main/java/org/spin/grpc/service/WorkflowServiceImplementation.java

```log
===========> Trx.commit: POSave_298520ab-b473-4efc-bd6e-bb62b6d84b75 [79]
org.postgresql.util.PSQLException: ERROR: insert or update on table "ad_recentitem" violates foreign key constraint "adwindow_adrecentitem"
Detail: Key (ad_window_id)=(50075) is not present in table "ad_window".; State=23503; ErrorCode=0
at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2675)
at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2365)
at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:355)
at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:315)
at org.postgresql.jdbc.PgConnection.executeTransactionCommand(PgConnection.java:855)
at …
```

fix: Error adding recent items when different from window.

---

src/main/java/org/spin/base/db/WhereClauseUtil.java

If the parameter is range, default operator is `BETWEEN`.
However, if it does not have a start value, the operator is `<=`, or if it does not have an end value, the operator is `>=`.

fix: Add restriction with `BETWEEN` operator and one value.

---

src/main/java/org/spin/grpc/service/UserInterfaceServiceImplementation.java

```bash
curl --location 'http://0.0.0.0:8085/api/adempiere/user-interface/window/default-value?field_uuid=8d06274c-fb40-11e8-a479-7a0060f0aa01&id=364&value=O&ts=1691109442189' \
--header 'Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiIxMDAxODY3IiwiQURfQ2xpZW50X0lEIjoxMSwiQURfT3JnX0lEIjowLCJBRF9Sb2xlX0lEIjoxMDIsIkFEX1VzZXJfSUQiOjEwMSwiTV9XYXJlaG91c2VfSUQiOjAsIkFEX0xhbmd1YWdlIjoiZXNfTVgiLCJpYXQiOjE2OTEwNzUwNTIsImV4cCI6MTY5MTE2MTQ1Mn0.3tdP8oeHvdZJJDGajzBt_NO9xYGsIeTFV9cAikA_FrA'
```
```json
{
"code": 500,
"result": ""
}
```
```json
{
"code": 200,
"result": {
"id": 0,
"uuid": "",
"attributes": []
}
}
```
```log
===========> UserInterfaceServiceImplementation.getDefaultValue: null [41]
at …
```

fix: NPE with get default value as `List` reference inexistent value.

---

src/main/java/org/spin/base/workflow/WorkflowUtil.java
src/main/java/org/spin/grpc/service/BusinessDataServiceImplementation.java
src/main/java/org/spin/grpc/service/WorkflowServiceImplementation.java

when the action of a document is executed, the workflow was not being activated.
Additionally, a bypass is added so that if `runBusinessProcess` with workflow is called, it executes the same logic of executing an action. In this way it is ensured that both services, despite being different, have the same behavior and therefore the same result.
fixes https://github.com/solop-develop/frontend-core/issues/1088

fix: Process document with workflow.

---

src/main/proto/bank_statement_match.proto

the business partner is unused to filter on import table, this is used only payment.

fix: `Bank Statement Match`, remove unused props.

---

src/main/java/org/spin/form/bank_statement_match/BankStatementMatchConvertUtil.java

Set Bank Statement name.
fixes https://github.com/solop-develop/frontend-core/issues/1297
fixes https://github.com/solop-develop/frontend-core/issues/1298

fix: `Bank Statement Match` empty name.

---

src/main/java/org/spin/form/bank_statement_match/BankStatementMatchConvertUtil.java
src/main/java/org/spin/form/bank_statement_match/BankStatementMatchServiceLogic.java
src/main/java/org/spin/form/bank_statement_match/BankStatementMatchUtil.java
src/main/proto/bank_statement_match.proto

- List Imported Payments, regardless if it is matches.
- List Payments, regardless if it is matches.
- Add `isAutomatic` matches.
- Add `PaymentAmount`.

fix: `Bank Statement Match` form, matches/unmatches records.

---

src/main/java/org/spin/pos/service/order/ReverseSalesTransaction.java

- Create a Sales Order
- Return it
The result:
- The return order is created with context organization instead of source order organization

Fixed error with organization for RMA

---

src/main/java/org/spin/pos/service/order/OrderManagement.java

When a orders don't have payments and is flagged as write off amount, the invoice is created as open amount instead of write off it

Fixed error with write-off amount for orders without payments

---

src/main/java/org/spin/base/db/WhereClauseUtil.java

Cuando hay 2 pestañas que no comparten campos en comun, zk permitia "joinearlas" mediante la clausula SQL del AD_Tab.
Ahora en VUE, a lo que tenga la clausula le agrega el ID de la ventana de nivel 0
Esto causa que se intente hacer un join con la tabla lvl1 con la superior lvl0 por su campo ID, siendo que no tienen campos en comun.
Esto causa un error SQL de campo no encontrado que hace que no se carguen registros en la pestaña

Fix not found column

---

src/main/java/org/spin/grpc/service/UserInterfaceServiceImplementation.java

when a callout is executed for example in `C Payment`, it does not have `IsSOTrx` as a field, but the callout sends it to the context and the value does not reach the client.
fixes https://github.com/solop-develop/frontend-core/issues/1122

fix: Callout wiith `isSOTrx` context.

---

src/main/java/org/spin/grpc/service/CoreFunctionalityImplementation.java

```bash
curl --location 'http://0.0.0.0:8085/api/adempiere/common/warehouses?organization_uuid=e1a4a3f6-f352-4e64-b068-a333ef6c747d&page_size=100&ts=1692903771838' \
--header 'Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiIxMTM1NDQ3IiwiQURfQ2xpZW50X0lEIjoxMDAwMDAwLCJBRF9PcmdfSUQiOjEwMDAwMjAsIkFEX1JvbGVfSUQiOjEwMDAxMTEsIkFEX1VzZXJfSUQiOjEwMDAwOTMsIk1fV2FyZWhvdXNlX0lEIjoxMDAwMDcwLCJBRF9MYW5ndWFnZSI6ImVzX1ZFIiwiaWF0IjoxNjkyOTAyODg1LCJleHAiOjE2OTI5ODkyODV9.mlAoSAJAkOf_Pl6z56ESkBdL38sw9MwS9293aceUagE'
```
```json
{
"code": 500,
"result": "org.postgresql.util.PSQLException: ERROR: column \"rownum\" does not exist\n  Position: 277, SQL=SELECT AD_Client_ID,AD_Org_ID,C_Location_ID,Created,CreatedBy,Description,IsActive,IsInTransit,M_Warehouse_ID,M_WarehouseSource_ID,Name, …
```

fix: Query warehouses with limit and access filter and records.

---

src/main/java/org/spin/base/db/WhereClauseUtil.java

Avoid warning at building
```Java
adempiere-grpc-server/src/main/java/org/spin/base/db/WhereClauseUtil.java:627:
warning: [dep-ann] deprecated item is not annotated with @Deprecated
public static String getBrowserWhereClause(MBrowse browser,
String parsedWhereClause,
^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 warning
```

Minor change for source code

---

src/main/java/org/spin/base/dictionary/custom/BrowseFieldCustomUtil.java

```log
===========> Query.first: SELECT AD_BrowseCustom_ID,AD_BrowseFieldCustom_ID,AD_Browse_Field_ID,AD_Client_ID,AD_Org_ID,AD_Reference_ID,AD_Reference_Value_ID,AD_Val_Rule_ID,Axis_Column_ID,Axis_Parent_Column_ID,Callout,Created,CreatedBy,DefaultValue,DefaultValue2,Description,DisplayLogic,Help,InfoFactoryClass,IsActive,IsDisplayed,IsDisplayedAsPanel,IsDisplayedAsTable,IsIdentifier,IsInfoOnly,IsKey,IsMandatory,IsOrderBy,IsQueryCriteria,IsRange,IsReadOnly,Name,ReadOnlyLogic,SeqNo,SeqNoGrid,SortNo,UUID,Updated,UpdatedBy,VFormat,ValueMax,ValueMin FROM AD_BrowseFieldCustom WHERE (AD_BrowseField_ID = ? AND EXISTS( SELECT 1 FROM AD_BrowseCustom AS bc WHERE bc.AD_User_ID = ? AND bc.AD_BrowseCustom_ID = AD_BrowseFieldCustom.AD_BrowseCustom_ID)) AND IsActive=? [22] …
```

fix: Smart Browse with ASP custom.

---

.github/workflows/publish.yml
build.gradle
resources/envoy.yaml
src/main/proto/security.proto

This pull request allows generate descriptor file for envoy proxy and transcoding gRPC to JSON, see:
- https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/grpc_json_transcoder_filter#route-configs-for-transcoded-requests
- https://github.com/google/protobuf-gradle-plugin/pull/30
- https://github.com/google/protobuf-gradle-plugin#generate-descriptor-set-files
- https://github.com/toefel18/transcoding-grpc-to-http-json

Add support to Envoy proxy

---

.settings/org.eclipse.buildship.core.prefs
src/main/proto/bank_statement_match.proto
src/main/proto/business_partner.proto
src/main/proto/security.proto

- Security:
- POST: `/security/login`
- POST: `/security/session-attribute`
- GET: `/security/user-info`
- GET: `/security/session-info`
- GET: `/security/roles`
- GET: `/security/menu`
- GET: `/security/services`
- POST: `/security/logout`
- Business Partner:
- `/business-partner/business-partners`
- Bank
- GET: `/bank-statement-match/bank-statements/{id}`
- GET: `/bank-statement-match/accounts`
- GET: `/bank-statement-match/business-partners`
- GET: `/bank-statement-match/search-modes`
- GET: `/bank-statement-match/imported-movements`
- GET: `/bank-statement-match/payments`
- GET: `/bank-statement-match/matching-movements`
- GET: `/bank-statement-match/movements`
- GET: `/bank-statement-match/bank-statements`
- POST: `/bank-statement-match/match-payments`
- POST: …

Add Transcoding support service for

---

src/main/java/org/spin/base/util/SessionManager.java
src/main/java/org/spin/grpc/service/SecurityServiceImplementation.java

The backend context store is different from the frontend context, since in the backend the zero store is set even when the organization is non-zero.
fixes https://github.com/solop-develop/adempiere-grpc-server/issues/512

fix: Warehouse context session.

---

src/main/java/org/spin/base/db/WhereClauseUtil.java
src/main/java/org/spin/base/util/ValueUtil.java

1. Open `Process Orders of selection` smart browse.
2. Displayed `Date Ordered` query criteria field.
3. Select any range.
https://github.com/solop-develop/frontend-core/assets/20288327/d0e71f96-1451-4212-8a69-f70c2b7834dc
fixes https://github.com/solop-develop/adempiere-grpc-server/issues/515

fix: Smart Browse search with range query criteria.

---

src/main/java/org/spin/grpc/service/UserInterfaceServiceImplementation.java

```sql
CASE WHEN '@INV_IsSOTrx@' = 'Y' THEN bp.PaymentRule ELSE bp.PaymentRulePO END AS BP_PaymentRule
```
```sql
CASE WHEN '' = 'Y' THEN bp.PaymentRule ELSE bp.PaymentRulePO END AS BP_PaymentRule
```
fixes https://github.com/solop-develop/frontend-core/issues/1476

fix: Smart Browser unparseable sql with missing context.

---

src/main/java/org/spin/base/db/WhereClauseUtil.java
src/main/java/org/spin/grpc/service/UserInterfaceServiceImplementation.java

https://github.com/solop-develop/frontend-core/assets/20288327/3ac66537-5fa7-403d-b32c-cde3bf40b21c
fixes https://github.com/solop-develop/frontend-core/issues/1478

fix: Smart Browser omit `isInfoOnly` fields from query criteria.

---

build.gradle

When request to unkown url, generates NPE 
```
Jul 11, 2023 10:51:25 AM io.grpc.netty.shaded.io.grpc.netty.NettyServerHandler onDataRead
WARNING: Exception in onDataRead()
java.lang.NullPointerException: Cannot invoke "io.grpc.netty.shaded.io.grpc.netty.NettyServerStream$TransportState.tag()" because "stream" is null
at io.grpc.netty.shaded.io.grpc.netty.NettyServerHandler.onDataRead(NettyServerHandler.java:516)
at io.grpc.netty.shaded.io.grpc.netty.NettyServerHandler.access$900(NettyServerHandler.java:111)
at io.grpc.netty.shaded.io.grpc.netty.NettyServerHandler$FrameListener.onHeadersRead(NettyServerHandler.java:853)
at io.grpc.netty.shaded.io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener.onHeadersRead(DefaultHttp2ConnectionDecoder.java:409)
at …
```

fix: NPE url not found.

---

src/main/java/org/spin/base/util/ReferenceInfo.java
src/main/java/org/spin/grpc/service/UserInterface.java

when you send an ID that does not exist in the type of field you want to query, for example `AD_ProcessPara_ID`, and the MProcessPara is not instantiated, it generates a `Null Pointer Exception`.

fix: Validate lookup reference to prevent NPE.

---

src/main/java/org/spin/base/util/RecordUtil.java

When the value of `SearchValue` is set via http GET method, it changes certain characters such as space to a `+`, so searches may not match.
In addition, the column names `Name`, `Value`, and `DocumentNo` are added to match the search value.

fix: (Transcoding) `Search Value` URL decode value.

---

src/main/java/org/spin/grpc/service/Dashboarding.java
src/main/proto/dashboarding.proto

Get main dashboards wihtout `Role ID` or `User ID`.
```bash
curl 'http://0.0.0.0/api/dashboard/dashboards?role_id=0&page_size=15' -H 'Accept: application/json, text/plain, */*' -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiIxMDAwMDk4IiwiQURfQ2xpZW50X0lEIjowLCJBRF9PcmdfSUQiOjAsIkFEX1JvbGVfSUQiOjAsIkFEX1VzZXJfSUQiOjEwMCwiTV9XYXJlaG91c2VfSUQiOjAsIkFEX0xhbmd1YWdlIjoiZXNfTVgiLCJpYXQiOjE2OTcwMzczNzMsImV4cCI6MTY5NzEyMzc3M30.sL4trGbkWXCvwTI4u0ATgFrRECUuM9xurjZq8G1FO5U'
```
```json
{
"code": 13,
"message": "Rol * No encontrado *",
"details": []
}
```

fix: (Transcoding) Main Dashboards with role and user from backend context.

---

src/main/java/org/spin/grpc/service/UserInterface.java

https://github.com/solop-develop/adempiere-grpc-server/assets/20288327/b75dafa9-abff-4ca4-be67-73be7246e547
https://github.com/solop-develop/adempiere-grpc-server/assets/20288327/55a316b8-fe76-4a67-aff8-946967fe6ef5
The price list is created with `AD_Org_ID=1000001`
```
SELECT ad_org_id, M_PriceList.M_PriceList_ID,NULL,COALESCE(M_PriceList.Name,'-1'),M_PriceList.IsActive, M_PriceList.UUID 
FROM M_PriceList 
WHERE 
M_PriceList.M_PriceList_ID=1000006 
AND M_PriceList.AD_Client_ID IN(0,1000001) 
AND M_PriceList.AD_Org_ID IN(0,1000004) 
AND (M_PriceList.M_PriceList_ID IS NULL 
OR M_PriceList.M_PriceList_ID NOT IN (
SELECT Record_ID 
FROM AD_Private_Access 
WHERE AD_Table_ID = 255 AND AD_User_ID <> 1001212 AND IsActive = 'Y'
)
)
```
fixes …

fix: Get diplay value and default value with access restriction.

---

src/main/java/org/spin/grpc/service/BusinessData.java

when the process no exists in the access table it generates NPE since it returns the `Boolean` object in null, and on this it tries to cascade to `boolean`.
fixes https://github.com/solop-develop/frontend-core/issues/1640

fix: When the process exists in the access table generates NPE.

---

src/main/java/org/spin/base/db/FromUtil.java
src/main/java/org/spin/base/util/RecordUtil.java
src/main/java/org/spin/form/import_file_loader/ImportFileLoaderServiceLogic.java
src/main/java/org/spin/grpc/service/CoreFunctionality.java
src/main/java/org/spin/grpc/service/MatchPOReceiptInvoice.java
src/main/java/org/spin/grpc/service/MaterialManagement.java
src/main/java/org/spin/grpc/service/PointOfSalesForm.java
src/main/java/org/spin/grpc/service/TimeRecord.java
src/main/java/org/spin/grpc/service/UserCustomization.java
src/main/java/org/spin/grpc/service/field/location_address/LocationAddressLogic.java
src/main/java/org/spin/grpc/service/form/ExpressMovement.java
src/main/java/org/spin/grpc/service/form/ExpressReceipt.java
src/main/java/org/spin/grpc/service/form/ExpressShipment.java
src/main/java/org/spin/grpc/service/form/PaymentAllocation.java
src/main/java/org/spin/grpc/service/form/bank_statement_match/BankStatementMatchConvertUtil.java
src/main/java/org/spin/pos/service/POSLogic.java
src/main/java/org/spin/pos/service/bank/BankManagement.java
src/main/java/org/spin/pos/service/pos/POS.java

When listing or getting values, they are done via http with the `GET` method, so the search value is sent in the url, and spaces are defined as `+`, among other characters that can change.
If `test 5` is sent, `test+5` will arrive, so it will never match the values stored in the database, maybe `Test 5`.

fix: `Search Value` decode url value.

---

src/main/java/org/spin/base/db/OrderByUtil.java
src/main/java/org/spin/dictionary/util/WindowUtil.java
src/main/java/org/spin/grpc/service/UserInterface.java

fixes https://github.com/solop-develop/frontend-core/issues/1671

fix: Order By clause to window records.

---

build.gradle

If display type isID, and reference is `Table` or `Search`, and column is `AD_Language` or `EntityType` with value, return builder value as null.
fixes https://github.com/solop-develop/frontend-core/issues/1699

fix: Convert ID value as string when is Table or Search.

---

src/main/java/org/spin/base/db/OperatorUtil.java
src/main/java/org/spin/base/db/WhereClauseUtil.java

When the filter has no operator, it is not set to the default operator, which is equal to.
fixes https://github.com/solop-develop/frontend-core/issues/1686

fix: NPE with default operator filter.

---

build.gradle

```json
{
"id": 2000059,
"name": "",
"instance_id": 2186193,
"is_error": true,
"summary": "ProcessError Font \"Arial\" is not available to the JVM. See the Javadoc for more details.",
"result_table_name": "",
"is_processing": false,
"last_run": "2023-12-21T21:36:34Z",
"logs": [],
"process_intance_parameters": []
}
```
https://github.com/solop-develop/adempiere-grpc-server/assets/20288327/1c051f9b-c040-4f6c-a891-142954e76b45
https://github.com/solop-develop/adempiere-grpc-server/assets/20288327/4def33ff-96fa-47ce-9ef6-d5d19fe9eee3
fixes https://github.com/solop-develop/frontend-core/issues/1091

fix: Generate report with arial font.

---

src/main/java/org/spin/base/util/RecordUtil.java

http://0.0.0.0:8080/api/user-interface/lookups/field/58065?search_value=&table_name=AD_Client&column_name=AD_Client_ID&page_size=15
```json
{
"code": 13,
"message": "org.postgresql.util.PSQLException: El índice de la columna está fuera de rango: 0, número de columnas: 5.",
"details": []
}
```
```log
===========> UserInterface.listLookupItems: org.postgresql.util.PSQLException: El índice de la columna está fuera de rango: 0, número de columnas: 5. [110]
org.adempiere.exceptions.AdempiereException: org.postgresql.util.PSQLException: El índice de la columna está fuera de rango: 0, número de columnas: 5.
at org.spin.grpc.service.UserInterface.listLookupItems(UserInterface.java:2318)
at org.spin.grpc.service.UserInterface.listLookupItems(UserInterface.java:2214)
at …
```

fix: SQL column index.

---

src/main/java/org/spin/grpc/service/LogsInfo.java
src/main/java/org/spin/log/LogsConvertUtil.java
src/main/java/org/spin/log/LogsServiceLogic.java
src/main/proto/logs.proto

* 13 de diciembre de 2023, 02:22:32 p. m. Se edita el campo `IsTotallyInvoiced`.
* 13 de diciembre de 2023, 02:18:18 p. m. Se edita el campo `IsAllowToInvoice`.
* 13 de diciembre de 2023, 02:04:55 p. m. Se editan los campos `DocStatus`, `DocAction`, `Weight`, `Volume`, `ProcessedOn`, `C_DocType_ID`, `IsApproved`, `TotalLines`, `GrandTotal`, y `Processed`
* 13 de diciembre de 2023, 02:04:55 p. m. Se edita el campo `Link_Order_ID`.
* 13 de diciembre de 2023, 02:04:54 p. m. Se edita el campo `C_Order_ID`.
fixes https://github.com/solop-develop/frontend-core/issues/1752
fixes https://github.com/solop-develop/frontend-core/issues/1753

fix: Record logs order.

---

.github/workflows/ci.yml
.github/workflows/publish.yml

```log
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, actions/setup-java@v3, gradle/gradle-build-action@v2, actions/upload-artifact@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
```
- `actions/checkout@v3` to `actions/checkout@v4`.
- `actions/setup-java@v3` to `actions/setup-java@v4`.
- `actions/upload-artifact@v3` to `actions/upload-artifact@v4`.
- `actions/donwload-artifact@v3` to `actions/donwload-artifact@v4`.

feat: Update github actions versions.

---

build.gradle
src/main/java/org/spin/grpc/service/UserInterface.java

```bash
curl --location --request POST 'http://192.168.5.101/api/user-interface/run-callout/186/DateOrdered/org.compiere.model.CalloutEngine.dateAcct;%20org.compiere.model.CalloutOrder.priceList' \
--header 'Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiIyMDE3NTI4IiwiQURfQ2xpZW50X0lEIjoxMDAwMDAxLCJBRF9PcmdfSUQiOjEwMDAwMTAsIkFEX1JvbGVfSUQiOjEwMDAwMjMsIkFEX1VzZXJfSUQiOjEwMDEzOTgsIk1fV2FyZWhvdXNlX0lEIjoxMDAwMDgwLCJBRF9MYW5ndWFnZSI6ImVzX01YIiwiaWF0IjoxNzA2MjgyNzE5LCJleHAiOjE3MDYzNjkxMTl9.7rEIUfi0j_mzv7CsIYTPUE_vncKs2fNjgBXPimsQUP8' \
--data '{
"tab_id": 186,
"column_name": "DateOrdered",
"context_attributes": {},
"callout": "org.compiere.model.CalloutEngine.dateAcct; org.compiere.model.CalloutOrder.priceList",
"value": …
```

fix: Field with multiple callouts.

---

src/main/java/org/spin/grpc/service/Dashboarding.java
src/main/proto/dashboarding.proto

Add sequence to list dashboards.
```json
{
"record_count": "22",
"dashboards": [
{
"id": 1000041,
"name": "Ventas",
"description": "Venta neta",
"file_name": "",
"dashboard_type": "chart",
"chart_type": "LC",
"sequence": 0,
"html": "",
"column_no": 0,
"line_no": 0,
"is_collapsible": true,
"is_open_by_default": true,
"is_event_required": false,
"browser_id": 0,
"window_id": 0
}
],
"next_page_token": ""
}
```
fixes https://github.com/solop-develop/frontend-core/issues/1748

feat: Add `Goal` chart sequence.

---

src/main/java/org/spin/grpc/service/core_functionality/CoreFunctionality.java

The record count always is zero
```json
{
"record_count": "0",
"languages": [
{
"language": "en_US",
"language_name": "English (USA)",
"language_iso": "en",
"country_code": "US",
"is_base_language": true,
"is_system_language": false,
"is_decimal_point": true,
"date_pattern": "MM/dd/yyyy",
"time_pattern": "h:mm:ss a z"
},
{
"language": "es_MX",
"language_name": "Spanish (Mexico)",
"language_iso": "es",
"country_code": "MX",
"is_base_language": false,
"is_system_language": true,
"is_decimal_point": true,
"date_pattern": "dd/MM/yyyy",
"time_pattern": "H:mm:ss z"
}
],
"next_page_token": ""
}
```
```json
{
"record_count": "2",
"languages": [
{
"language": "en_US",
"language_name": "English (USA)",
"language_iso": "en",
"country_code": "US",
"is_base_language": true,
"is_system_language": …
```

fix: List languages record count.

---

src/main/java/org/spin/base/db/WhereClauseUtil.java
src/main/java/org/spin/grpc/service/UserInterface.java

```bash
curl 'http://10.11.12.101/api/user-interface/default-value/field/1343?value=102' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:123.0) Gecko/20100101 Firefox/123.0' -H 'Accept: application/json, text/plain, */*' -H 'Accept-Language: es-MX,es;q=0.8,en-US;q=0.5,en;q=0.3' -H 'Accept-Encoding: gzip, deflate' -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiIyMDE3MTEwIiwiQURfQ2xpZW50X0lEIjoxMDAwMDAxLCJBRF9PcmdfSUQiOjEwMDAwMDEsIkFEX1JvbGVfSUQiOjEwMDAwMTcsIkFEX1VzZXJfSUQiOjEwMDEyMTIsIk1fV2FyZWhvdXNlX0lEIjoxMDAwMDI4LCJBRF9MYW5ndWFnZSI6ImVzX01YIiwiaWF0IjoxNzA4NjI4NDg3LCJleHAiOjE3MDg3MTQ4ODd9.J0ZGVviWmYIY_5fz8XX1yE0lJ7KVpLcZmE90-4Bfsuw' -H 'Origin: http://0.0.0.0:9527' -H 'Connection: keep-alive' -H 'Referer: http://0.0.0.0:9527/' -H 'Pragma: no-cache' -H 'Cache-Control: …
```

fix: Default value empty if `IsActive='Y'` restriction.

---

.github/workflows/ci.yml
build.gradle
docker/envoy_template.yaml
resources/envoy.yaml
src/main/java/org/spin/grpc/service/Security.java

When authenticating with OpenID through keycloack, the token generated from keycloack is now returned to the fronend and not the one generated by adempiere.
[open-id-session-id.xml.zip](https://github.com/adempiere/adempiere-grpc-utils/files/14578780/open-id-session-id.xml.zip)
fixes https://github.com/solop-develop/frontend-core/issues/1968

feat: Return `JWT` by keycloack.

---

src/main/java/org/spin/base/db/QueryUtil.java
src/main/java/org/spin/base/util/ReferenceInfo.java
src/main/java/org/spin/base/util/ReferenceUtil.java
src/main/java/org/spin/grpc/service/UserInterface.java

```
SQL Error [21000]: ERROR: more than one row returned by a subquery used as an expression
```
fixes https://github.com/solop-develop/frontend-core/issues/2011

fix: List entities with multiple subquery.

---

build.gradle
src/main/java/org/spin/base/db/WhereClauseUtil.java
src/main/java/org/spin/server/AllInOneServices.java

Original SQL:
```sql
SELECT C_BankAccount.C_BankAccount_ID,NULL,
COALESCE((SELECT COALESCE(C_Bank.Name,'')||' - '||COALESCE(C_Bank.RoutingNo,'') FROM C_Bank WHERE C_BankAccount.C_Bank_ID=C_Bank.C_Bank_ID),'-1') ||'_'|| COALESCE(C_BankAccount.AccountNo,'-1') ||'_'|| COALESCE((SELECT COALESCE(C_Currency.ISO_Code,'') FROM C_Currency WHERE C_BankAccount.C_Currency_ID=C_Currency.C_Currency_ID),'-1'),
C_BankAccount.IsActive,
C_BankAccount.UUID 
FROM C_BankAccount 
ORDER BY 3
```
Generate SQL
```sql
SELECT COUNT(*)
FROM C_BankAccount 
ORDER BY 3
```
https://github.com/adempiere/adempiere-grpc-utils/assets/20288327/375ef408-f9f4-4443-83b2-5d33335627bc
fixes https://github.com/solop-develop/frontend-core/issues/2012

fix: SQL Count without where clause.

---

src/main/java/org/spin/grpc/service/UserInterface.java

If the current callout is not in the list of callouts that modify the context, it generates a `Null Pointer Exception`.
```log
===========> UserInterface.runCallout: null [20]
at java.base/java.lang.String.startsWith(String.java:1428)
at java.base/java.lang.String.startsWith(String.java:1470)
at org.spin.grpc.service.UserInterface.lambda$26(UserInterface.java:2709)
at java.base/java.util.Arrays$ArrayList.forEach(Arrays.java:4390)
at org.spin.grpc.service.UserInterface.setAdditionalContext(UserInterface.java:2701)
at org.spin.grpc.service.UserInterface.lambda$22(UserInterface.java:2672)
at org.compiere.util.Trx.run(Trx.java:529)
at org.compiere.util.Trx.run(Trx.java:497)
at org.spin.grpc.service.UserInterface.runcallout(UserInterface.java:2563)
at …
```

fix: NPE With callout is not custom context.

---

src/main/java/org/spin/grpc/service/field/product/ProductInfo.java
src/main/java/org/spin/grpc/service/field/product/ProductInfoLogic.java
src/main/proto/product.proto

Add filters by Product Category, Product Group, Product Class and Product Classification.
https://github.com/solop-develop/adempiere-grpc-server/assets/20288327/439551ea-2969-4ad8-878f-e39d220d4b6e
fixes https://github.com/solop-develop/frontend-core/issues/1034

feat: `Product` info field filter by groups.

---

src/main/java/org/spin/grpc/service/Security.java
src/main/proto/security.proto

To prevent the frontend from constructing the `action_id` (as `reference_id`) or `action_uuid` (as `reference_uuid`) by searching inside process, smart browse, window, workflow or form, the attribute is rounded by placing it at the root of the structure.

feat: Add `action_uuid` on Menu structure.

---

src/main/java/org/spin/base/db/WhereClauseUtil.java

When sending a filter that does not exist as undefined, an sql error is generated because the filter key is not present as a column.
This validation was already present in smart browsers.

fix: Inexistent column as key filer.

---

src/main/java/org/spin/base/db/WhereClauseUtil.java
src/main/java/org/spin/base/query/Filter.java
src/main/java/org/spin/base/query/FilterManager.java

```bash
curl 'http://10.11.12.102/api/general-ledger/accounts/combinations?organization_id=12&account_id=50025&page_token=1&page_size=15&filters=%7B%22C_BPartner_ID%22:1000015%7D'   -H 'Accept: application/json, text/plain, */*'   -H 'Accept-Language: es-419,es;q=0.9,es-VE;q=0.8,en;q=0.7'   -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiIyMDE4MzAwIiwiQURfQ2xpZW50X0lEIjoxMSwiQURfT3JnX0lEIjowLCJBRF9Sb2xlX0lEIjoxMDIsIkFEX1VzZXJfSUQiOjEwMSwiTV9XYXJlaG91c2VfSUQiOjAsIkFEX0xhbmd1YWdlIjoiZXNfTVgiLCJpYXQiOjE3MTM5MDExMjEsImV4cCI6MTcxMzk4NzUyMX0.q_gJ5Oloj_sTKNoMvyOdslhi9Q4YXI17SdFXmlDKTWM'   -H 'Connection: keep-alive'
```
The filter
```json
{
"C_BPartner_ID": 1000015
}
```
Convert as
```json
[
{
"name": "C_BPartner_ID",
"operator": "equal",
"values": 1000015
}
]
```

fix: Filter manager without list.

---

src/main/java/org/spin/base/interim/ContextTemporaryWorkaround.java
src/main/java/org/spin/base/util/ContextManager.java
src/main/java/org/spin/grpc/service/Security.java
src/main/java/org/spin/grpc/service/core_functionality/CoreFunctionality.java

when using parallel stream to handle multiple threads to traverse a list, the context is not set correctly generating data inconsistency.

fix: Context with `parallelStream`.

---

build.gradle

```bash
curl 'http://192.168.3.53/api/user-interface/browser-items/50108?filters=[%7B%22name%22:%22CONTACT_IsActive%22,%22operator%22:%22equal%22,%22values%22:true%7D,%7B%22name%22:%22CONTACT_IsLoginUser%22,%22operator%22:%22equal%22,%22values%22:%22Y%22%7D]&context_attributes=%7B%7D&page_token=1&page_size=15' \
-H 'Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiIxMDAwMTYwIiwiQURfQ2xpZW50X0lEIjoxMSwiQURfT3JnX0lEIjo1MDAwNiwiQURfUm9sZV9JRCI6MTAyLCJBRF9Vc2VyX0lEIjoxMDAsIk1fV2FyZWhvdXNlX0lEIjo1MDAwNiwiQURfTGFuZ3VhZ2UiOiJlbl9VUyIsImlhdCI6MTcxNzU1MjI3MiwiZXhwIjoxNzE3NjM4NjcyfQ.o9mFygoEQgusNi4flFlRhSNH0sZbFgDvOTso-XjGqps'
```
```json
{
"code": 13,
"message": "class java.lang.Boolean cannot be cast to class java.lang.String (java.lang.Boolean …
```

fix: `Smart Browse` cast boolean to string.

---

src/main/java/org/spin/grpc/service/ui/BrowserLogic.java

fixes https://github.com/solop-develop/frontend-core/issues/1880

fix: Smart Browse process all records context no query criteria arguments.

---

src/main/java/org/spin/base/db/OrderByUtil.java
src/main/java/org/spin/base/util/LookupUtil.java
src/main/java/org/spin/grpc/service/UserInterface.java

When adding a lookup type field it sorts by the value of the Identifier, now it sorts by the display value
This is the generated sorting sql
```sql
ORDER BY p.C_SalesRegion_ID, p.C_BPartner_ID, p.C_ProjectCategory_ID
```
This is the generated sorting sql:
```sql
ORDER BY "DisplayColumn_P_C_SalesRegion_ID", "DisplayColumn_P_C_BPartner_ID", "DisplayColumn_P_C_ProjectCategory_ID"
```
fixes https://github.com/solop-develop/frontend-core/issues/2379

fix: Smart Browse `Order By` lookups by display columns.

---

build.gradle

The version of `adempiere-kafka-connector` is downgraded until the multi-tenant dictionary is stabilized.

fix: Downgrade `adempiere-kafka-connector` to 1.3.0 version.

---

src/main/java/org/spin/base/db/QueryUtil.java
src/main/java/org/spin/base/util/ReferenceUtil.java

when using a key reference that does not have table validation it generates an sql for the display column that is incorrect and prevents the flow.
```sql
SELECT	C_ProjectTask.*, 
AS "DisplayColumn_Responsible_ID"
FROM C_ProjectTask
```
Now it is just omitted from the sql query.
```sql
SELECT	C_ProjectTask.*
FROM C_ProjectTask
```

fix: Table reference without table validation.

---

src/main/java/org/spin/grpc/service/ReportManagement.java

```log
===========> ReportManagement.listPrintFormats: null [99]
at org.spin.grpc.service.ReportManagement.listPrintFormats(ReportManagement.java:699)
at org.spin.grpc.service.ReportManagement.listPrintFormats(ReportManagement.java:664)
at org.spin.backend.grpc.report_management.ReportManagementGrpc$MethodHandlers.invoke(ReportManagementGrpc.java:664)
at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:182)
at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListe …
```

fix: List `Print Formats` null pointer exception with table.

---

src/main/java/org/spin/grpc/service/field/field_management/FieldManagementLogic.java

As the request is a `GET` the `value` parameter of the default path is already `encodeURI` so this step is in addition to `ValueManager.getDecodeUrl()`.
https://github.com/user-attachments/assets/168d1c1e-fb51-4a62-8dcb-42ab9d9439f7
The problem lies in the fact that the `+` character has a special meaning in URL encoding. When you URL decode a string, the `+` character is replaced with a space (` `) character. This is because, in URL encoding, the `+` character is used to represent a space.
```
curl 'http://spdev01.solopapp.com:24610/api/fields/default-value/field/3482?value=V%2B' \
-H 'Accept-Language: es-419,es;q=0.9,es-VE;q=0.8,en;q=0.7' \
-H 'Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiIyMDIzMDk2IiwiQURfQ2xpZW50X0lEIjoxMDAwMDAxL …
```

Error in DefaultValue with Special Values

---

src/main/java/org/spin/base/db/WhereClauseUtil.java

```bash
curl 'http://0.0.0.0/api/fields/default-value/field/1004288?value=1000328' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:131.0) Gecko/20100101 Firefox/131.0' -H 'Accept: application/json, text/plain, */*' -H 'Accept-Language: es-MX,es;q=0.8,en-US;q=0.5,en;q=0.3' -H 'Accept-Encoding: gzip, deflate' -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiIyMDE2MDczIiwiQURfQ2xpZW50X0lEIjoxMDAwMDAxLCJBRF9PcmdfSUQiOjAsIkFEX1JvbGVfSUQiOjEwMDAwMDIsIkFEX1VzZXJfSUQiOjEwMDAwNjUsIk1fV2FyZWhvdXNlX0lEIjowLCJBRF9MYW5ndWFnZSI6ImVuX1VTIiwiaWF0IjoxNzI5MDQxMjM4LCJleHAiOjE3MjkxMjc2Mzh9.RGqB-XbCVTkUSBjXm-YW_Y0eAZriLNyd8Za9PH_c1N4' -H 'Origin: http://0.0.0.0:9527' -H 'Connection: keep-alive' -H 'Referer: http://0.0.0.0:9527/' -H 'Priority: u=0'
```
```json
{
"code": 13,
"message": …
```

fix: `IsActive` restriction with default value.

---

src/main/java/org/spin/grpc/service/SendNotifications.java

the account name is not the user's email address.
```
NOT VALID - EMail[From:solop.notificaciones@gmail.com,To:null,Subject=Order Print]
```
ref https://github.com/solop-develop/frontend-core/issues/1198

fix: Send email with `userId` without account name.

---

src/main/java/org/spin/grpc/service/UserInterface.java

```sql
SELECT COUNT(*)
FROM C_Invoice AS C_Invoice
WHERE C_Invoice.IsSOTrx='Y' AND C_DocTypeTarget_ID IN (select c_doctype_id from c_doctype where docbasetype in ('ARI', 'API','ARC','APC')) AND (((C_Invoice.C_Order_ID=1463671 AND C_Invoice.IsSOTrx='Y') OR
C_Invoice.C_Invoice_ID IN (
SELECT i.C_Invoice_ID from /* intentionally lowercase */ C_Invoice i
LEFT JOIN C_InvoiceLine il ON il.C_Invoice_ID = i.C_Invoice_ID
LEFT JOIN C_OrderLine ol ON ol.C_OrderLine_ID = il.C_OrderLine_ID
where ol.C_Order_ID=1463671 AND i.isSOTrx='Y'
))) AND C_Invoice.AD_Client_ID IN (0,1000001)
```
ref https://github.com/solop-develop/frontend-core/issues/2824

fix: Improves performance in the query count.

---

gradle.properties

Add support to import `Imports`
ref https://github.com/solop-develop/adempiere-solop/issues/66
closes https://github.com/solop-develop/adempiere-grpc-server/pull/963

feat: Update adempiere-solop libs to `3.9.4.001-spuy-0.0.4`.

---

gradle.properties

```sql
SELECT tn.Node_ID, tn.SeqNo FROM AD_TreeNodeMM tn
WHERE tn.AD_Tree_ID = 1000035 AND COALESCE(tn.Parent_ID, 0) = 0
```
```sql
SELECT tn.Node_ID, tn.SeqNo FROM AD_TreeNodeMM tn
WHERE tn.Node_ID > 0 AND tn.AD_Tree_ID = 1000035 AND COALESCE(tn.Parent_ID, 0) = 0
```
ref https://github.com/solop-develop/adempiere-solop/issues/147

fix: Infinity loop when `Node_ID` equal `0`.

---

src/main/java/org/spin/grpc/service/display_definition/DisplayDefinitionConvertUtil.java
src/main/java/org/spin/grpc/service/display_definition/DisplayDefinitionServiceLogic.java

```bash
curl --location --request GET 'http://0.0.0.0/api/display-definition/definitions/1000006/fields' \
--header 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:134.0) Gecko/20100101 Firefox/134.0' \
--header 'Accept: application/json, text/plain, */*' \
--header 'Accept-Language: es-MX,es;q=0.8,en-US;q=0.5,en;q=0.3' \
--header 'Accept-Encoding: gzip, deflate, br, zstd' \
--header 'Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiIzMDA5NDYxIiwiQURfQ2xpZW50X0lEIjoxMDAwMDAxLCJBRF9PcmdfSUQiOjEwMDAwMDMsIkFEX1JvbGVfSUQiOjEwMDAwMTcsIkFEX1VzZXJfSUQiOjEwMDEyMTIsIk1fV2FyZWhvdXNlX0lEIjoxMDAwMDQ1LCJBRF9MYW5ndWFnZSI6ImVzX01YIiwiaWF0IjoxNzM3NzQ1OTQ3LCJleHAiOjE3Mzc4MzIzNDd9.TjIP2SLgDAPkWejctYrXDykiZiOtxV_-mpzSLwLTaSM' \
--header 'Connection: keep-alive' \
--header 'Referer: …
```

fix: Display Definition Isert/Edit field attributes.

---

src/main/java/org/spin/grpc/service/display_definition/DisplayDefinitionConvertUtil.java
src/main/java/org/spin/grpc/service/display_definition/DisplayDefinitionServiceLogic.java

```curl
curl --location --request GET 'http://192.168.5.102/api/display-definition/1000027/entries/1000307' \
--header 'Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiIzMDEwMzM4IiwiQURfQ2xpZW50X0lEIjoxMDAwMDAxLCJBRF9PcmdfSUQiOjAsIkFEX1JvbGVfSUQiOjEwMDAwMDIsIkFEX1VzZXJfSUQiOjEwMDEyMTIsIk1fV2FyZWhvdXNlX0lEIjowLCJBRF9MYW5ndWFnZSI6ImVzX01YIiwiaWF0IjoxNzM4MDgwMjQ0LCJleHAiOjE3MzgxNjY2NDR9.kzapmliqMNx3Qa6XgCYPS4Mg_HNwdNCs-qrvRMPl9sM'
```
```json
{
"id": 1000307,
"uuid": "21d8cf86-9f79-11ea-9e44-c6ad1fcc20e4",
"title": "Prueba Medios",
"is_active": true,
"is_read_only": false,
"fields": {
"IsApproved": {
"value": false,
"display_value": "No"
},
"Value": {
"value": "1204b",
"display_value": null
},
"PlannedQty": {
"value": {
"type": "decimal",
"value": "100.00"
}, …
```

feat: Add additional fields on display definition.

---

src/main/java/org/spin/grpc/service/display_definition/DisplayDefinitionServiceLogic.java

```bash
curl --location --request DELETE 'http://0.0.0.0/api/display-definition/1000008/entries/1001005' \
--header 'accept: application/json, text/plain, */*' \
--header 'accept-language: es-419,es;q=0.9' \
--header 'authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiIzMDEwMzQ4IiwiQURfQ2xpZW50X0lEIjoxMDAwMDAxLCJBRF9PcmdfSUQiOjEwMDAwMTAsIkFEX1JvbGVfSUQiOjEwMDAwMDIsIkFEX1VzZXJfSUQiOjEwMDEyMTIsIk1fV2FyZWhvdXNlX0lEIjoxMDAwMDgwLCJBRF9MYW5ndWFnZSI6ImVzX01YIiwiaWF0IjoxNzM4MTg0Mjk4LCJleHAiOjE3MzgyNzA2OTh9.GpAeLMCguldPeYbt683yizpBsoiqztrZuQJKICOheB0' \
--header 'origin: http://localhost:9527' \
--header 'priority: u=1, i' \
--header 'referer: http://localhost:9527/' \
--header 'sec-ch-ua: "Google Chrome";v="131", "Chromium";v="131", "Not_A Brand";v="24"' \
--header 'sec-ch-ua-mobile: ?0' \ …
```

fix: Display definition delete entity.

---

src/main/java/org/spin/grpc/service/display_definition/DisplayDefinitionConvertUtil.java

```log
===========> DisplayDefinition.listDisplayDefinitionsMetadata: null [25]
at org.spin.backend.grpc.display_definition.FieldDefinition$Builder.setReadOnlyLogic(FieldDefinition.java:2762)
at org.spin.grpc.service.display_definition.DisplayDefinitionConvertUtil.convertFieldDefinitionByColumn(DisplayDefinitionConvertUtil.java:895)
at org.spin.grpc.service.display_definition.DisplayDefinitionConvertUtil.convertDefinitionMetadata(DisplayDefinitionConvertUtil.java:301)
at org.spin.grpc.service.display_definition.DisplayDefinitionServiceLogic.lambda$0(DisplayDefinitionServiceLogic.java:247)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.spin.grpc.service.display_definition.DisplayDefinitionServiceLogic.listDisplayDefinitionsMetadata(Displa …
```

fix: NPE on field definition without read only logic.

---

src/main/java/org/spin/base/db/QueryUtil.java

```bash
curl 'http://0.0.0.0/api/user-interface/entities/54808?search_value=&context_attributes=%7B%22C_Project_ID%22:1007938%7D&page_token=1&page_size=100&sort_by=' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:135.0) Gecko/20100101 Firefox/135.0' -H 'Accept: application/json, text/plain, */*' -H 'Accept-Language: es-MX,es;q=0.8,en-US;q=0.5,en;q=0.3' -H 'Accept-Encoding: gzip, deflate' -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiIzMDE5MTMzIiwiQURfQ2xpZW50X0lEIjoxMDAwMDAxLCJBRF9PcmdfSUQiOjEwMDAwMTAsIkFEX1JvbGVfSUQiOjEwMDAwMDIsIkFEX1VzZXJfSUQiOjEwMDEyMTIsIk1fV2FyZWhvdXNlX0lEIjoxMDAwMDgwLCJBRF9MYW5ndWFnZSI6ImVzX01YIiwiaWF0IjoxNzQwNTI5NjI0LCJleHAiOjE3NDA2MTYwMjR9.aFdQjNGlg8xQKqVZybvJ0voZPMw4dZO710BaZUUMZpc' -H 'Origin: http://0.0.0.0:9527' -H 'Connection: keep-alive' -H …
```

fix: NPE when field is null.

---

src/main/java/org/spin/grpc/service/UserInterface.java

If smart browse has searchProcess_ID it runs that process before searching
if the view has AD_PInstance_ID as a column then it sets the process instance id as a query criteria
It passes the search criteria as process parameter to the search process

feat: Run process before search in a smart browse

---

src/main/java/org/spin/grpc/service/field/business_partner/BusinessPartnerLogic.java

Added access filter to Business Partner Search, this way users can't see Partners from Orgs that they don't have access to.
Role: Field Services - Admin
Role Org access: 
Does not have access to D&D Org
Business Partners:
Only "Test DyD" has "D&D" Org 
Test BEFORE code change in VUE: 
https://github.com/user-attachments/assets/31e3683c-7fe9-4b25-a96e-841d33ed90c9
It finds 8 and 13 BPartners including "Test DyD" which should not appear because the org access
Test AFTER code change in VUE:
https://github.com/user-attachments/assets/6faada59-b6a1-46bf-ac82-bd6ed6fa6b10
it finds 7 and 12 BPartners, not finding "Test DyD" thanks to the org access
ref: https://github.com/solop-develop/adempiere-solop/issues/377

Add Access Filter to businessPartner Search

---

src/main/java/org/spin/grpc/service/PointOfSalesForm.java

If Shipment is created from POS, do not create InOutLine with charge when the order had a discount by amount.
Tested locally.
This change is only for the buttons in the POS for creating shipment, if the Document type is POS order or POS warehouse it still causes error.
https://www.loom.com/share/2446ede92fe649d3aeebea6da41e1fca?sid=7966202d-4723-439e-9fb2-5a4c498f94fb
ref: https://github.com/solop-develop/adempiere-solop/issues/493

When adding discount by amount in POS do not create InOutLine with charge

---

src/main/java/org/spin/base/util/AccessUtil.java
src/main/java/org/spin/grpc/service/display_definition/DisplayDefinitionServiceLogic.java

If role does not have access to a window of the table of Display Definition then don't show it
Role with access to:
-  "Business Partner" window
- "Sales Order" or any window that has c_BPartner_ID field
-  "Product" window
The Role should NOT have access to "Product Classification" window
With this configuration the role shows Display Definition for "Business Partner" but not for "Product Classification"
Tested locally:
https://www.loom.com/share/81ac9d417c3b4fcd804875dd6d6ce848?sid=0ea3c378-fcc5-47ae-86a5-c5d7d2831171
Ref: https://github.com/solop-develop/frontend-core/issues/802

Bugfix Don't show display definition if role does not have access to window

---

src/main/java/org/spin/grpc/service/ReportManagement.java

Checks for any PrintFormat that has the table to print or for any PrintFormat that has a ReportView that uses the same table to print
Report view "Report View with AD_Table C_Invoice":
PrintFormat "Print Format with C_Invoice ReportView" With the same Report View and does not have C_Invoice as Table:
When Listing the Print Formats in Invoice (Customer) it finds a normal print format and the new Print format that does not have the C_Invoice Table:

Finds PrintFormat by ReportView Table

---

src/main/java/com/solop/sp013/core/documents/FiscalDocumentLine.java
src/main/java/com/solop/sp013/core/model/validator/ElectronicInvoicing.java
src/main/java/com/solop/sp013/core/util/ElectronicInvoicingSummaryGrouping.java

Before it was setting the value 2 times, instead it sets the value and the ProductType
When processing Delete the existing Summary Line so it does not make duplicates
For Sending Summary Lines to Invoicy
* Sets the Value, Name and Description from the summary line, not from the Product or Charge because they can be null
* Only try to set the Info from Product or Charge if the Info is Null
* Description is only set from the Summary Line, not from product
Ref: https://github.com/solop-develop/adempiere-solop/issues/1019

Fix Electronic invoicing Summary Line creation
